# DARWIN HAMMER — match 103, survivor 1
# gen: 2
# parent_a: hybrid_infotaxis_minhash_m63_s1.py (gen1)
# parent_b: rbf_surrogate.py (gen0)
# born: 2026-05-29T23:26:46Z

import numpy as np
import math
import random
import sys
import pathlib

"""
This module combines the gradient-free entropy search helpers from hybrid_infotaxis_minhash_m63_s1.py
and the radial-basis surrogate model from rbf_surrogate.py.
The mathematical bridge between the two structures lies in the use of probability distributions and information theory,
where the entropy measures from hybrid_infotaxis_minhash_m63_s1.py can be applied to the similarity scores generated by the surrogate model.
"""

MAX64 = (1 << 64) - 1

def _hash(seed: int, token: str) -> int:
    data = seed.to_bytes(4, 'big') + token.encode('utf-8', errors='ignore')
    return int.from_bytes(hashlib.blake2b(data, digest_size=8).digest(), 'big')

def signature(tokens: Iterable[str], k: int = 128) -> List[int]:
    toks = {t for t in tokens if t}
    if k <= 0:
        raise ValueError('k must be positive')
    if not toks:
        return [MAX64] * k
    return [min(_hash(i, t) for t in toks) for i in range(k)]

def similarity(sig_a: List[int], sig_b: List[int]) -> float:
    if len(sig_a) != len(sig_b):
        raise ValueError('signatures must have equal length')
    if not sig_a:
        raise ValueError('signatures must not be empty')
    return sum(1 for a, b in zip(sig_a, sig_b) if a == b) / len(sig_a)

def shingles(text: str, width: int = 5) -> set[str]:
    words = text.split()
    if width <= 0:
        raise ValueError('width must be positive')
    if len(words) < width:
        return {' '.join(words)} if words else set()
    return {' '.join(words[i:i+width]) for i in range(len(words) - width + 1)}

def entropy(probabilities: List[float], eps: float = 1e-12) -> float:
    total = sum(probabilities)
    if total <= 0:
        raise ValueError('positive probability mass required')
    return -sum((p/total) * math.log(max(p/total, eps)) for p in probabilities if p > 0)

def expected_entropy(p_hit: float, hit_state: List[float], miss_state: List[float]) -> float:
    if not 0 <= p_hit <= 1:
        raise ValueError('p_hit must be in [0,1]')
    return p_hit * entropy(hit_state) + (1.0 - p_hit) * entropy(miss_state)

def gaussian(r: float, epsilon: float = 1.0) -> float:
    return math.exp(-((epsilon * r) ** 2))

def euclidean(a: list[float], b: list[float]) -> float:
    if len(a) != len(b):
        raise ValueError("vectors must have same dimension")
    return math.sqrt(sum((x - y) ** 2 for x, y in zip(a, b)))

def solve_linear(a: list[list[float]], b: list[float]) -> list[float]:
    n = len(b)
    m = [row[:] + [rhs] for row, rhs in zip(a, b)]
    for col in range(n):
        pivot = max(range(col, n), key=lambda r: abs(m[r][col]))
        if abs(m[pivot][col]) < 1e-12:
            raise ValueError("singular surrogate system")
        m[col], m[pivot] = m[pivot], m[col]
        div = m[col][col]
        m[col] = [v / div for v in m[col]]
        for row in range(n):
            if row == col:
                continue
            factor = m[row][col]
            m[row] = [v - factor * p for v, p in zip(m[row], m[col])]
    return [row[-1] for row in m]

def fit(points: Iterable[list[float]], values: Iterable[float], epsilon: float = 1.0, ridge: float = 1e-9) -> dict:
    centers = [tuple(map(float, p)) for p in points]
    y = [float(v) for v in values]
    if not centers or len(centers) != len(y):
        raise ValueError("points and values must be non-empty and same length")
    k = [[gaussian(euclidean(a, b), epsilon) + (ridge if i == j else 0.0) for j, b in enumerate(centers)] for i, a in enumerate(centers)]
    weights = solve_linear(k, y)
    return {'centers': centers, 'weights': weights}

def hybrid_search(points: Iterable[list[float]], values: Iterable[float], epsilon: float = 1.0, ridge: float = 1e-9, k: int = 128) -> dict:
    model = fit(points, values, epsilon, ridge)
    signatures = {}
    for point in points:
        text = ' '.join(map(str, point))
        tokens = shingles(text, k)
        signatures[tuple(point)] = signature(tokens, k)
    similarity_scores = {}
    for point, signature in signatures.items():
        scores = []
        for other_point, other_signature in signatures.items():
            if point == other_point:
                continue
            score = similarity(signature, other_signature)
            scores.append(score)
        similarity_scores[tuple(point)] = expected_entropy(1.0, scores, [1.0 - score for score in scores])
    return {'model': model, 'similarity_scores': similarity_scores}

def hybrid_predict(model: dict, point: list[float]) -> float:
    similarity_score = model['similarity_scores'].get(tuple(point), 0.0)
    return model['model']['weights'][0] * gaussian(euclidean(point, model['model']['centers'][0]), 1.0) + similarity_score

if __name__ == "__main__":
    points = [[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]]
    values = [1.0, 2.0, 3.0]
    epsilon = 1.0
    ridge = 1e-9
    k = 128
    model = hybrid_search(points, values, epsilon, ridge, k)
    print(hybrid_predict(model, [1.0, 2.0]))