# DARWIN HAMMER — match 218, survivor 0
# gen: 2
# parent_a: hybrid_temporal_motifs_possum_filter_m87_s0.py (gen1)
# parent_b: hybrid_doomsday_calendar_gini_coefficient_m49_s3.py (gen1)
# born: 2026-05-29T23:27:39Z

"""
This module fuses the Hybrid Temporal Motif algorithm (hybrid_temporal_motifs_possum_filter_m87_s0.py) 
and the Hybrid Doomsday Calendar with Gini Coefficient algorithm (hybrid_doomsday_calendar_gini_coefficient_m49_s3.py).
The mathematical bridge between the two algorithms lies in the application of the Gini Coefficient to 
the burst signals generated by the Hybrid Temporal Motif algorithm. The Gini Coefficient is used to 
measure the inequality of the burst signals, which can help in identifying significant patterns.

The governing equations of the Hybrid Temporal Motif algorithm are used to generate burst signals, 
while the Gini Coefficient is applied to these signals to measure their inequality.
"""

import numpy as np
import math
import datetime as dt
from collections import Counter
from dataclasses import dataclass
from typing import Iterable, Sequence, Tuple, List, Union

@dataclass(frozen=True)
class Entity:
    id: str
    lat: float
    lon: float
    category: str
    score: float = 0.0
    address_signature: str = ""

@dataclass(frozen=True)
class BurstSignal:
    key: str
    count: int
    z_score: float

def haversine_m(a: tuple[float, float], b: tuple[float, float]) -> float:
    lat1, lon1 = map(math.radians, a)
    lat2, lon2 = map(math.radians, b)
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    h = math.sin(dlat / 2) ** 2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2) ** 2
    return 2 * 6_371_000.0 * math.asin(min(1.0, math.sqrt(h)))

def gini_coefficient_numpy(values: np.ndarray) -> float:
    if values.ndim != 1:
        raise ValueError("values must be a 1‑D array")
    xs = np.sort(values.astype(float))
    if xs.size == 0 or xs.sum() == 0.0:
        return 0.0
    if xs[0] < 0:
        raise ValueError("values must be non‑negative")
    n = xs.size
    i = np.arange(1, n + 1)  # 1‑based index
    numerator = np.sum((2 * i - n - 1) * xs)
    denominator = n * xs.sum()
    return numerator / denominator

def detect_bursts(events: list[dict], key: str = 'category') -> list[BurstSignal]:
    counter = Counter(event[key] for event in events)
    mean = sum(counter.values()) / len(counter)
    variance = sum((count - mean) ** 2 for count in counter.values()) / len(counter)
    bursts = []
    for k, count in counter.items():
        z_score = (count - mean) / math.sqrt(variance)
        bursts.append(BurstSignal(k, count, z_score))
    return bursts

def hybrid_analysis(events: list[dict], key: str = 'category') -> Tuple[List[BurstSignal], float]:
    bursts = detect_bursts(events, key)
    burst_counts = np.array([burst.count for burst in bursts])
    gini = gini_coefficient_numpy(burst_counts)
    return bursts, gini

def sessionize_events(events: list[dict], gap_seconds: float = 1800.0) -> list[list[dict]]:
    sessions = []
    current_session = []
    for event in events:
        if not current_session or event['timestamp'] - current_session[-1]['timestamp'] <= gap_seconds:
            current_session.append(event)
        else:
            sessions.append(current_session)
            current_session = [event]
    if current_session:
        sessions.append(current_session)
    return sessions

def keep_candidate(candidate: Entity, selected: list[Entity], delta_m: float) -> bool:
    for existing in selected:
        same_kind = candidate.address_signature == existing.address_signature or candidate.category == existing.category
        if same_kind and haversine_m((candidate.lat, candidate.lon), (existing.lat, existing.lon)) <= delta_m:
            return False
    return True

def main():
    events = [
        {'category': 'A', 'timestamp': dt.datetime(2022, 1, 1, 12, 0, 0)},
        {'category': 'B', 'timestamp': dt.datetime(2022, 1, 1, 12, 1, 0)},
        {'category': 'A', 'timestamp': dt.datetime(2022, 1, 1, 12, 2, 0)},
        {'category': 'C', 'timestamp': dt.datetime(2022, 1, 1, 13, 0, 0)},
    ]
    bursts, gini = hybrid_analysis(events)
    print("Bursts:")
    for burst in bursts:
        print(burst)
    print(f"Gini Coefficient: {gini}")

if __name__ == "__main__":
    main()