# DARWIN HAMMER — match 44, survivor 1
# gen: 2
# parent_a: ternary_lens_router.py (gen0)
# parent_b: hybrid_decision_hygiene_shannon_entropy_m12_s0.py (gen1)
# born: 2026-05-29T23:23:38Z

"""
Hybrid algorithm combining ternary Command Envelope Router from ternary_lens_router.py and hybrid decision hygiene scoring with Shannon entropy calculation from hybrid_decision_hygiene_shannon_entropy_m12_s0.py.

The mathematical bridge between the two parent algorithms lies in using the Shannon entropy calculation to analyze the distribution of ternary vectors generated by the ternary Command Envelope Router. This allows for a more detailed understanding of the command envelope routing process, incorporating both the ternary vector representation and the information-theoretic properties of the vectors.
"""

import numpy as np
import re
import math
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

EVIDENCE_RE = re.compile(r"\b(?:evidence|verify|verified|confirm|confirmed|source|sourced|citation|receipt|hash|sha256|screenshot|record|log|document|proof|fact|facts|check|checked|audit)\b", re.I)
PLANNING_RE = re.compile(r"\b(?:plan|checklist|steps?|sequence|timeline|roadmap|phase|priority|prioritize|triage|criteria|protocol|procedure|schedule|budget|scope|test|smoke)\b", re.I)
DELAY_RE = re.compile(r"\b(?:pause|sleep|wait|tomorrow|later|hold|cool down|de[- ]?escalate|not now|first|after|review)\b", re.I)
SUPPORT_RE = re.compile(r"\b(?:ask|call|text|friend|friends|rowyn|kai|chance|doctor|therapist|lawyer|advocate|support|help|community|team|handoff|delegate)\b", re.I)
BOUNDARY_RE = re.compile(r"\b(?:boundary|boundaries|walk away|no contact|do not|don't|stop|limit|refuse|protect|safe|safety|lock|redact|privacy|permission|consent)\b", re.I)
OUTCOME_RE = re.compile(r"\b(?:done|shipped|finished|complete|resolved|succeeded|passed|paid|safe|sent|filed|closed|fixed|working|green|verified)\b", re.I)
IMPULSIVE_RE = re.compile(r"\b(?:rage|impulsive|panic|panicking|spiral|doom|fuck it|right now|immediately|tonight|destroy|revenge|scorched|burn it|quit|give up)\b", re.I)
SCARCITY_RE = re.compile(r"\b(?:broke|homeless|last\s+\$?\d+|\$\s?\d+\s+to my name|can't afford|cannot afford|rent due|no money|starving|desperate|no sleep|exhausted)\b", re.I)
RISK_RE = re.compile(r"\b(?:kill|die|suicide|suicidal|self[- ]?harm|overdose|hurt myself|danger|unsafe|crisis|collapse)\b", re.I)

CLASSIFICATIONS = {"usable_now", "research_only", "needs_conversion", "unsafe_for_fastpath", "unsupported"}
TERNARY_DIMS = 12

def counts(text: str) -> dict[str, int]:
    return {
        "evidence_count": len(EVIDENCE_RE.findall(text or "")),
        "planning_count": len(PLANNING_RE.findall(text or "")),
        "delay_count": len(DELAY_RE.findall(text or "")),
        "support_count": len(SUPPORT_RE.findall(text or "")),
        "boundary_count": len(BOUNDARY_RE.findall(text or "")),
        "outcome_count": len(OUTCOME_RE.findall(text or "")),
        "impulsive_count": len(IMPULSIVE_RE.findall(text or "")),
        "scarcity_count": len(SCARCITY_RE.findall(text or "")),
        "risk_count": len(RISK_RE.findall(text or "")),
    }

def score_features(c: dict[str, int]) -> tuple[int, str]:
    positive = (
        c["evidence_count"] * 1600
        + c["planning_count"] * 1200
        + c["delay_count"] * 1400
        + c["support_count"] * 1000
        + c["boundary_count"] * 1200
        + c["outcome_count"] * 800
    )
    negative = c["impulsive_count"] * 1500 + c["scarcity_count"] * 700 + c["risk_count"] * 1200
    score = max(-10000, min(10000, positive - negative))
    if c["risk_count"] and score < 2500:
        label = "critical_risk_or_pain_signal"
    elif score >= 7000:
        label = "high_decision_hygiene"
    elif score >= 3000:
        label = "improving_decision_hygiene"
    elif score <= -2500:
        label = "strained_decision_context"
    else:
        label = "neutral_or_unclear"
    return score, label

def shannon_entropy(observations: list[int], is_distribution: bool = False) -> float:
    if not observations: return 0.0
    if is_distribution:
        probs = [float(x) for x in observations]
        if any(p < 0 for p in probs) or abs(sum(probs) - 1.0) > 1e-6:
            raise ValueError("distribution must sum to 1")
    else:
        c = Counter(observations)
        total = sum(c.values())
        probs = [v / total for v in c.values()]
    return -sum(p * math.log2(p) for p in probs if p > 0)

def payload_hash(raw_command: str, normalized_intent: str, context: dict[str, Any]) -> str:
    payload = {
        "raw_command": raw_command,
        "normalized_intent": normalized_intent,
        "context": context,
    }
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(encoded).hexdigest()

def stable_primitive_id(raw_command: str, normalized_intent: str, context: dict[str, Any]) -> int:
    digest = payload_hash(raw_command, normalized_intent, context)
    return int(digest[:8], 16) % 25

def ternary_vector(raw_command: str, normalized_intent: str, context: dict[str, Any], dims: int = TERNARY_DIMS) -> list[int]:
    digest = hashlib.sha256((raw_command + "\0" + normalized_intent + "\0" + json.dumps(context, sort_keys=True)).encode()).digest()
    values = []
    for idx in range(dims):
        values.append((digest[idx] % 3) - 1)
    return values

def confidence_bps(raw_command: str, normalized_intent: str, context: dict[str, Any]) -> int:
    base = 4500
    if normalized_intent.strip():
        base += 1800
    if raw_command.strip():
        base += 1200
    if context:
        base += 800
    return max(0, min(9900, base))

def hybrid_analysis(raw_command: str, normalized_intent: str, context: dict[str, Any]) -> tuple[float, list[int], int, int]:
    ternary_vec = ternary_vector(raw_command, normalized_intent, context)
    c = counts(raw_command)
    score, label = score_features(c)
    entropy = shannon_entropy(ternary_vec)
    confidence = confidence_bps(raw_command, normalized_intent, context)
    return entropy, ternary_vec, score, confidence

def parse_context(text: str) -> dict[str, Any]:
    if not text:
        return {}
    try:
        value = json.loads(text)
    except json.JSONDecodeError as exc:
        raise SystemExit(f"context must be valid JSON: {exc}") from exc
    if not isinstance(value, dict):
        raise SystemExit("context must be a JSON object")
    return value

if __name__ == "__main__":
    raw_command = "I have a plan to achieve my goals, and I will review it regularly."
    normalized_intent = "plan and review goals"
    context = parse_context('{"goal": "success", "priority": "high"}')
    entropy, ternary_vec, score, confidence = hybrid_analysis(raw_command, normalized_intent, context)
    print(f"Entropy: {entropy}")
    print(f"Ternary Vector: {ternary_vec}")
    print(f"Score: {score}")
    print(f"Confidence: {confidence}")