# DARWIN HAMMER — match 103, survivor 0
# gen: 2
# parent_a: hybrid_infotaxis_minhash_m63_s1.py (gen1)
# parent_b: rbf_surrogate.py (gen0)
# born: 2026-05-29T23:26:46Z

"""
This module combines the gradient-free entropy search helpers from hybrid_infotaxis_minhash_m63_s1.py 
and the radial-basis surrogate model from rbf_surrogate.py. 
The mathematical bridge between the two structures lies in the use of probability distributions 
and information theory, where the entropy measures from hybrid_infotaxis_minhash_m63_s1.py can be 
applied to the similarity scores generated by minhash.py, and the radial-basis surrogate model 
can be used to predict the entropy of the system given a set of points in the input space.
"""

import numpy as np
import math
import random
import sys
import pathlib
from typing import Iterable, List, Tuple, Dict

MAX64 = (1 << 64) - 1

def _hash(seed: int, token: str) -> int:
    data = seed.to_bytes(4, 'big') + token.encode('utf-8', errors='ignore')
    import hashlib
    return int.from_bytes(hashlib.blake2b(data, digest_size=8).digest(), 'big')

def signature(tokens: Iterable[str], k: int = 128) -> List[int]:
    toks = {t for t in tokens if t}
    if k <= 0:
        raise ValueError('k must be positive')
    if not toks:
        return [MAX64] * k
    return [min(_hash(i, t) for t in toks) for i in range(k)]

def similarity(sig_a: List[int], sig_b: List[int]) -> float:
    if len(sig_a) != len(sig_b):
        raise ValueError('signatures must have equal length')
    if not sig_a:
        raise ValueError('signatures must not be empty')
    return sum(1 for a, b in zip(sig_a, sig_b) if a == b) / len(sig_a)

def shingles(text: str, width: int = 5) -> set[str]:
    words = text.split()
    if width <= 0:
        raise ValueError('width must be positive')
    if len(words) < width:
        return {' '.join(words)} if words else set()
    return {' '.join(words[i:i+width]) for i in range(len(words) - width + 1)}

def entropy(probabilities: List[float], eps: float = 1e-12) -> float:
    total = sum(probabilities)
    if total <= 0:
        raise ValueError('positive probability mass required')
    return -sum((p/total) * math.log(max(p/total, eps)) for p in probabilities if p > 0)

def gaussian(r: float, epsilon: float = 1.0) -> float:
    return math.exp(-((epsilon * r) ** 2))

def euclidean(a: List[float], b: List[float]) -> float:
    if len(a) != len(b):
        raise ValueError("vectors must have same dimension")
    return math.sqrt(sum((x - y) ** 2 for x, y in zip(a, b)))

def solve_linear(a: List[List[float]], b: List[float]) -> List[float]:
    n = len(b)
    m = [row[:] + [rhs] for row, rhs in zip(a, b)]
    for col in range(n):
        pivot = max(range(col, n), key=lambda r: abs(m[r][col]))
        if abs(m[pivot][col]) < 1e-12:
            raise ValueError("singular surrogate system")
        m[col], m[pivot] = m[pivot], m[col]
        div = m[col][col]
        m[col] = [v / div for v in m[col]]
        for row in range(n):
            if row == col:
                continue
            factor = m[row][col]
            m[row] = [v - factor * p for v, p in zip(m[row], m[col])]
    return [row[-1] for row in m]

class RBFSurrogate:
    def __init__(self, centers: List[Tuple[float, ...]], weights: List[float], epsilon: float = 1.0):
        self.centers = centers
        self.weights = weights
        self.epsilon = epsilon

    def predict(self, x: List[float]) -> float:
        return sum(w * gaussian(euclidean(x, c), self.epsilon) for w, c in zip(self.weights, self.centers))

def fit(points: Iterable[List[float]], values: Iterable[float], epsilon: float = 1.0, ridge: float = 1e-9) -> RBFSurrogate:
    centers = [tuple(map(float, p)) for p in points]
    y = [float(v) for v in values]
    if not centers or len(centers) != len(y):
        raise ValueError("points and values must be non-empty and same length")
    k = [[gaussian(euclidean(a, b), epsilon) + (ridge if i == j else 0.0) for j, b in enumerate(centers)] for i, a in enumerate(centers)]
    return RBFSurrogate(centers, solve_linear(k, y), epsilon)

def hybrid_search(points: List[List[float]], texts: List[str], k: int = 128) -> float:
    signatures = [signature(shingles(text, width=5), k) for text in texts]
    similarities = [similarity(signatures[i], signatures[j]) for i in range(len(signatures)) for j in range(i+1, len(signatures))]
    surr = fit(points, similarities)
    return surr.predict(points[0])

def grid_search(surr: RBFSurrogate, candidates: Iterable[List[float]], minimize: bool = True) -> Tuple[Tuple[float, ...], float]:
    scored = [(tuple(map(float, c)), surr.predict(c)) for c in candidates]
    if not scored:
        raise ValueError("candidates required")
    return min(scored, key=lambda kv: kv[1]) if minimize else max(scored, key=lambda kv: kv[1])

def entropy_prediction(points: List[List[float]], texts: List[str], k: int = 128) -> float:
    signatures = [signature(shingles(text, width=5), k) for text in texts]
    similarities = [similarity(signatures[i], signatures[j]) for i in range(len(signatures)) for j in range(i+1, len(signatures))]
    surr = fit(points, similarities)
    return surr.predict(points[0])

if __name__ == "__main__":
    points = [[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]]
    texts = ["apple banana", "banana orange", "orange grape"]
    surr = fit(points, [0.5, 0.7, 0.3])
    print(hybrid_search(points, texts))
    print(grid_search(surr, points))
    print(entropy_prediction(points, texts))