# DARWIN HAMMER — match 333, survivor 2
# gen: 3
# parent_a: hybrid_hybrid_workshare_all_hybrid_liquid_time_c_m39_s1.py (gen2)
# parent_b: hybrid_hybrid_ternary_route_variational_free_ene_m21_s0.py (gen2)
# born: 2026-05-29T23:28:34Z

"""Hybrid Workshare‑Calendar, Liquid‑Time‑Constant, MinHash & Variational Free‑Energy Fusion

This module merges the two parent algorithms:

* **Parent A** – Hybrid workshare‑calendar allocator + Liquid‑Time‑Constant (LTC) network whose
  gating depends on a weekday‑dependent weight vector *w(d)* and a MinHash similarity *s*.
* **Parent B** – Ternary router evaluated by a variational free‑energy (VFE) metric.

**Mathematical bridge**  
The weekday weight vector `w(d)` (size = number of model groups) is used in two places:

1. **LTC gating** – the effective time constant τ is modulated by a sigmoid of the
   inner product between `w(d)` and the MinHash similarity vector `s⃗`:
   `g = σ( α·w(d)·s⃗ ) , τ = τ₀ / g`.

2. **VFE weighting** – the KL‑term of the variational free‑energy is weighted by the same
   vector, yielding a scalar `KL_w = w(d)·KL(q‖p)`.  
   The total free‑energy is `F = 𝔼_q[log p(x|z)] – λ·KL_w`.

Thus the same weekday‑dependent topology controls both the continuous‑time dynamics
and the probabilistic evaluation of the ternary router, producing a unified hybrid system.
"""

import sys
import math
import random
import json
from pathlib import Path
from datetime import date, datetime, timezone
from typing import Any, Dict, List, Set, Tuple

import numpy as np

# ----------------------------------------------------------------------
# Core constants
# ----------------------------------------------------------------------
GROUPS: Tuple[str, ...] = ("codex", "groq", "cohere", "local_models")
BASE_TAU: float = 1.0          # baseline liquid time constant
ALPHA: float = 5.0             # gating steepness
LAMBDA: float = 0.7            # VFE weighting factor
MINHASH_K: int = 64            # number of hash functions for MinHash
MAX64: int = (1 << 64) - 1     # mask for 64‑bit hashing


# ----------------------------------------------------------------------
# Utility: weekday‑dependent weight vector (Parent A)
# ----------------------------------------------------------------------
def weekday_weight_vector(groups: Tuple[str, ...], dow: int) -> np.ndarray:
    """
    Normalised weight vector w(d) for the given weekday index ``dow`` (0=Sun … 6=Sat).

    The vector is generated by a sinusoidal pattern whose phase follows the day of week.
    """
    n = len(groups)
    base_angles = np.arange(n) * (2.0 * math.pi) / n
    phase = (2.0 * math.pi) * (dow % 7) / 7.0
    amplitude = 0.2
    raw = 1.0 + amplitude * np.sin(base_angles + phase)
    weight_vec = raw / raw.sum()
    return weight_vec.astype(np.float64)


def today_weekday() -> int:
    """Return today's weekday index compatible with ``weekday_weight_vector``."""
    return (date.today().weekday() + 1) % 7  # 0 = Sunday


# ----------------------------------------------------------------------
# MinHash utilities (Parent A)
# ----------------------------------------------------------------------
def _hash(seed: int, token: str) -> int:
    """Simple 64‑bit hash based on Python's built‑in hash combined with a seed."""
    random.seed(seed)
    # Mix the token with the seed; the result is forced into 64‑bit space.
    mixed = hash((seed, token)) & MAX64
    return mixed


def minhash_signature(token_set: Set[str], k: int = MINHASH_K) -> List[int]:
    """
    Compute a MinHash signature of length ``k`` for ``token_set``.
    Each entry is the minimum hash value observed for a distinct random seed.
    """
    signature = []
    for i in range(k):
        min_val = min(_hash(i, token) for token in token_set)
        signature.append(min_val)
    return signature


def minhash_similarity(sig_a: List[int], sig_b: List[int]) -> float:
    """
    Estimate Jaccard similarity from two MinHash signatures.
    """
    if len(sig_a) != len(sig_b):
        raise ValueError("Signatures must have equal length")
    matches = sum(1 for a, b in zip(sig_a, sig_b) if a == b)
    return matches / len(sig_a)


# ----------------------------------------------------------------------
# Variational Free‑Energy utilities (Parent B)
# ----------------------------------------------------------------------
def gaussian_kl(mean_q: np.ndarray, var_q: np.ndarray,
                mean_p: np.ndarray, var_p: np.ndarray) -> np.ndarray:
    """
    KL divergence KL(q‖p) for diagonal‑covariance Gaussians.
    Returns a vector of per‑dimension KL terms.
    """
    return 0.5 * (
        np.log(var_p / var_q) +
        (var_q + (mean_q - mean_p) ** 2) / var_p -
        1.0
    )


def variational_free_energy(state_mean: np.ndarray,
                            state_var: np.ndarray,
                            prior_mean: np.ndarray,
                            prior_var: np.ndarray,
                            weight_vec: np.ndarray) -> float:
    """
    Compute the scalar free‑energy:
        F = E_q[log p(x|z)] – λ * (w·KL(q‖p))

    For this demo ``E_q[log p(x|z)]`` is approximated by a simple negative L2 norm
    of the state (as a proxy for reconstruction log‑likelihood).
    """
    # Proxy reconstruction term (negative squared L2 norm)
    recon = -np.sum(state_mean ** 2)

    # Weighted KL term
    kl_vec = gaussian_kl(state_mean, state_var, prior_mean, prior_var)
    weighted_kl = np.dot(weight_vec, kl_vec)

    return recon - LAMBDA * weighted_kl


# ----------------------------------------------------------------------
# Hybrid gating – combines weekday weights and MinHash similarity (core of Parent A)
# ----------------------------------------------------------------------
def gating_factor(weight_vec: np.ndarray, similarity: float) -> float:
    """
    Compute the LTC gating scalar g = σ(α * w·s⃗).

    The similarity scalar is broadcast across the weight vector to form s⃗.
    """
    s_vec = np.full_like(weight_vec, similarity)
    inner = np.dot(weight_vec, s_vec)          # scalar ∈ [0,1]
    g = 1.0 / (1.0 + math.exp(-ALPHA * (inner - 0.5)))  # sigmoid centred at 0.5
    return g


def effective_time_constant(base_tau: float, gating: float) -> float:
    """τ = τ₀ / g  (larger gating → smaller effective τ)."""
    # Guard against division by zero
    return base_tau / (gating + 1e-8)


# ----------------------------------------------------------------------
# Dummy ternary router (stand‑in for the external service in Parent B)
# ----------------------------------------------------------------------
def dummy_route_command(text: str, intent: str, context: Dict[str, Any]) -> Dict[str, Any]:
    """
    Very lightweight deterministic router that pretends to produce a distribution
    over three possible actions. The distribution is encoded as a dict with keys
    'a', 'b', 'c' summing to 1.
    """
    random.seed(hash((text, intent)) & MAX64)
    probs = np.random.dirichlet(np.ones(3), size=1).flatten()
    return {
        "action_distribution": {"a": float(probs[0]),
                                "b": float(probs[1]),
                                "c": float(probs[2])},
        "selected_action": ["a", "b", "c"][int(np.argmax(probs))],
        "intent": intent,
        "text": text,
        "context_summary": {k: str(v)[:30] for k, v in context.items()}
    }


# ----------------------------------------------------------------------
# Hybrid processing pipeline (the fused algorithm)
# ----------------------------------------------------------------------
def hybrid_process(packet: Dict[str, Any],
                   reference_tokens: Set[str] | None = None) -> Dict[str, Any]:
    """
    End‑to‑end hybrid routine:

    1. Extract text and intent from ``packet``.
    2. Tokenise the text and compute a MinHash signature.
    3. Build weekday weight vector w(d).
    4. Compute gating g from w(d) and MinHash similarity to ``reference_tokens``.
    5. Derive effective liquid time constant τ.
    6. Produce a dummy router output (acts as the ternary router).
    7. Interpret the router distribution as a Gaussian mean (soft‑argmax) and unit variance.
    8. Evaluate variational free‑energy using the same w(d) as a weight for the KL term.
    9. Return a dictionary summarising all intermediate quantities.
    """
    # ------------------------------------------------------------------
    # 1‑2. Text extraction & tokenisation
    # ------------------------------------------------------------------
    text = str(packet.get("text_surface") or packet.get("raw_command") or
               packet.get("text") or "")
    intent = str(packet.get("normalized_intent") or packet.get("intent") or "default_intent")
    tokens = set(text.lower().split())
    if not tokens:
        tokens = {"<empty>"}

    # ------------------------------------------------------------------
    # 3. Weekday weight vector
    # ------------------------------------------------------------------
    dow = today_weekday()
    w_vec = weekday_weight_vector(GROUPS, dow)

    # ------------------------------------------------------------------
    # 4. MinHash similarity to reference set
    # ------------------------------------------------------------------
    if reference_tokens is None:
        reference_tokens = {"the", "and", "of", "to", "a"}  # a tiny generic reference
    sig_input = minhash_signature(tokens)
    sig_ref = minhash_signature(reference_tokens)
    similarity = minhash_similarity(sig_input, sig_ref)

    # ------------------------------------------------------------------
    # 5‑6. Gating and effective time constant
    # ------------------------------------------------------------------
    g = gating_factor(w_vec, similarity)
    tau_eff = effective_time_constant(BASE_TAU, g)

    # ------------------------------------------------------------------
    # 7. Dummy ternary router (produces a distribution)
    # ------------------------------------------------------------------
    context = {
        "source": packet.get("source"),
        "source_ref": packet.get("source_ref"),
        "ontology_terms": packet.get("ontology_terms") or [],
        "epistemic_flag": packet.get("epistemic_flag"),
        "payload": packet.get("payload") or {}
    }
    router_out = dummy_route_command(text[:4096], intent, context)

    # Convert the discrete distribution to a continuous mean vector.
    # Map actions a,b,c → coordinates (1,0,0), (0,1,0), (0,0,1)
    action_map = {"a": np.array([1.0, 0.0, 0.0]),
                  "b": np.array([0.0, 1.0, 0.0]),
                  "c": np.array([0.0, 0.0, 1.0])}
    dist = router_out["action_distribution"]
    mean_vec = sum(dist[k] * action_map[k] for k in dist)
    var_vec = np.full_like(mean_vec, 1.0)  # unit variance per dimension

    # ------------------------------------------------------------------
    # 8. Variational free‑energy evaluation
    # ------------------------------------------------------------------
    prior_mean = np.zeros_like(mean_vec)
    prior_var = np.ones_like(mean_vec)
    free_energy = variational_free_energy(mean_vec, var_vec,
                                          prior_mean, prior_var, w_vec)

    # ------------------------------------------------------------------
    # 9. Assemble result
    # ------------------------------------------------------------------
    result = {
        "weekday": dow,
        "weight_vector": w_vec.tolist(),
        "minhash_similarity": similarity,
        "gating_factor": g,
        "effective_tau": tau_eff,
        "router_output": router_out,
        "state_mean": mean_vec.tolist(),
        "state_variance": var_vec.tolist(),
        "variational_free_energy": free_energy,
        "timestamp_utc": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    }
    return result


# ----------------------------------------------------------------------
# Smoke test
# ----------------------------------------------------------------------
if __name__ == "__main__":
    # Construct a minimal packet resembling the structure expected by the original routers
    demo_packet = {
        "text_surface": "Explain the relationship between quantum entanglement and information theory.",
        "normalized_intent": "explain_concept",
        "source": "demo_user",
        "source_ref": "session_001",
        "ontology_terms": ["quantum_physics", "information_theory"],
        "epistemic_flag": True,
        "payload": {"temperature": 0.7}
    }

    output = hybrid_process(demo_packet)
    print(json.dumps(output, indent=2))