# DARWIN HAMMER — match 14, survivor 2
# gen: 1
# parent_a: workshare_allocator.py (gen0)
# parent_b: doomsday_calendar.py (gen0)
# born: 2026-05-29T23:19:36Z

"""Hybrid workshare‑calendar allocator.

This module fuses **workshare_allocator.py** (deterministic vs LLM token split) with
**doomsday_calendar.py** (weekday calculation).  The mathematical bridge is a
linear transformation: the LLM residual vector is multiplied by a day‑dependent
weight vector derived from the weekday (the “doomsday”).  In matrix form

    llm_allocation = llm_total * W(dow)

where `W(dow)` is a row‑stochastic matrix (here a 1‑D weight vector) whose
entries are a sinusoidal rotation of a base pattern, ensuring the sum of
weights equals 1.  This couples the calendar topology to the token allocation
topology without merely concatenating the two algorithms."""

from __future__ import annotations

import datetime as dt
import sys
from pathlib import Path
from typing import Any, Tuple, Sequence, Dict

import numpy as np
import math
import random

# ----------------------------------------------------------------------
# Constants (mirroring parent A)
# ----------------------------------------------------------------------
GROUPS: Tuple[str, ...] = ("codex", "groq", "cohere", "local_models")


def _pct(value: float) -> float:
    """Round a float to six decimal places (parent A utility)."""
    return round(float(value), 6)


# ----------------------------------------------------------------------
# Calendar helper (parent B)
# ----------------------------------------------------------------------
def doomsday(year: int, month: int, day: int) -> int:
    """
    Return weekday index where 0 = Sunday … 6 = Saturday.
    Equivalent to parent B implementation.
    """
    return (dt.date(year, month, day).weekday() + 1) % 7


def weekday_weight_vector(groups: Sequence[str], dow: int) -> np.ndarray:
    """
    Produce a normalized weight vector for *groups* based on the weekday ``dow``.
    The vector is generated by rotating a sinusoidal pattern; the rotation angle
    is proportional to ``dow`` (0‑6).  The result is stochastic (sums to 1) and
    serves as the linear operator that maps the LLM residual pool onto the
    individual group lanes.

    Mathematically:
        w_i(d) = [1 + α·sin(θ_i + φ(d))] / Σ_j[1 + α·sin(θ_j + φ(d))]
    where
        θ_i = 2π·i / N   (N = number of groups)
        φ(d) = 2π·d / 7   (weekday phase)
        α    = 0.2        (amplitude, chosen < 1 to keep positivity)

    Returns:
        np.ndarray of shape (N,) with dtype float64.
    """
    n = len(groups)
    if n == 0:
        raise ValueError("groups must contain at least one element")
    # Base angles equally spaced around the unit circle
    base_angles = np.arange(n) * (2.0 * math.pi) / n
    # Phase shift derived from weekday (0‑6 → 0‑2π)
    phase = (2.0 * math.pi) * (dow % 7) / 7.0
    amplitude = 0.2  # modest variation to keep all weights positive
    raw = 1.0 + amplitude * np.sin(base_angles + phase)
    # Normalise to make the vector stochastic
    weight_vec = raw / raw.sum()
    return weight_vec.astype(np.float64)


# ----------------------------------------------------------------------
# Hybrid allocation logic (fusion of parent A & B)
# ----------------------------------------------------------------------
def allocate_hybrid(
    *,
    total_units: float,
    date: dt.date,
    deterministic_target_pct: float = 90.0,
    groups: Tuple[str, ...] = GROUPS,
) -> Dict[str, Any]:
    """
    Allocate ``total_units`` between deterministic work and LLM residuals,
    then distribute the LLM portion across ``groups`` using a weekday‑dependent
    weight vector.

    The deterministic portion follows parent A exactly:
        deterministic_units = total_units * deterministic_target_pct / 100
        llm_units           = total_units - deterministic_units

    The LLM distribution uses the weight vector from ``weekday_weight_vector``:
        lane_i.llm_units = llm_units * w_i(dow)

    Returns a dictionary mirroring parent A's schema but enriched with calendar
    metadata (weekday and weight vector).
    """
    if total_units <= 0:
        raise ValueError("total_units must be positive")
    if not (0.0 <= deterministic_target_pct <= 100.0):
        raise ValueError("deterministic_target_pct must be between 0 and 100")
    if not groups:
        raise ValueError("groups required")

    # --- deterministic / LLM split (parent A) ---
    deterministic_units = total_units * deterministic_target_pct / 100.0
    llm_units = total_units - deterministic_units

    # --- calendar bridge (parent B) ---
    dow = doomsday(date.year, date.month, date.day)  # 0=Sunday…6=Saturday
    weight_vec = weekday_weight_vector(groups, dow)  # shape (N,)

    # --- per‑group allocation (linear transformation) ---
    llm_per_group = llm_units * weight_vec
    share_pct_per_group = weight_vec * 100.0

    lanes = [
        {
            "group": grp,
            "llm_units": _pct(llm_per_group[i]),
            "llm_share_pct": _pct(share_pct_per_group[i]),
            "proof_required": True,
            "weekday_weight": _pct(weight_vec[i]),
        }
        for i, grp in enumerate(groups)
    ]

    # --- jzloads (mirroring parent A, with added weekday info) ---
    jzloads: list[dict[str, Any]] = [
        {
            "kind": "OBJECT",
            "id": "project2501_hybrid_workshare_policy",
            "type": "workshare_policy",
            "deterministic_target_pct": _pct(deterministic_target_pct),
            "llm_residual_pct": _pct(100.0 - deterministic_target_pct),
        },
        {
            "kind": "EVENT",
            "id": "project2501_hybrid_workshare_allocation",
            "type": "allocation_computed",
            "total_units": _pct(total_units),
            "deterministic_units": _pct(deterministic_units),
            "llm_units": _pct(llm_units),
            "date": date.isoformat(),
            "weekday": dow,
        },
    ]

    for lane in lanes:
        jzloads.append(
            {
                "kind": "EDGE",
                "from": "project2501_hybrid_workshare_policy",
                "to": f"model_group:{lane['group']}",
                "type": "ASSIGNS_LLM_RESIDUAL_QUARTER",
                "llm_units": lane["llm_units"],
                "llm_share_pct": lane["llm_share_pct"],
                "weekday_weight": lane["weekday_weight"],
            }
        )

    return {
        "schema": "lucidota.project2501.hybrid_workshare_allocation.v1",
        "total_units": _pct(total_units),
        "deterministic_target_pct": _pct(deterministic_target_pct),
        "deterministic_units": _pct(deterministic_units),
        "llm_units": _pct(llm_units),
        "date": date.isoformat(),
        "weekday": dow,
        "weight_vector": [float(v) for v in weight_vec],
        "lanes": lanes,
        "jzloads": jzloads,
    }


def summarize_hybrid_savings(
    *,
    total_units: float,
    date: dt.date,
    deterministic_target_pct: float = 90.0,
    groups: Tuple[str, ...] = GROUPS,
) -> Dict[str, Any]:
    """
    Produce a high‑level summary analogous to parent A's ``summarize_savings``,
    but also reporting the weekday‑induced variation.
    """
    plan = allocate_hybrid(
        total_units=total_units,
        date=date,
        deterministic_target_pct=deterministic_target_pct,
        groups=groups,
    )
    return {
        "schema": "lucidota.project2501.hybrid_token_savings.v1",
        "baseline_llm_units": _pct(total_units),
        "planned_llm_units": plan["llm_units"],
        "deterministic_units": plan["deterministic_units"],
        "token_savings_pct": _pct((total_units - plan["llm_units"]) / total_units * 100.0),
        "date": date.isoformat(),
        "weekday": plan["weekday"],
        "per_group_llm_units": {lane["group"]: lane["llm_units"] for lane in plan["lanes"]},
        "per_group_weekday_weight": {
            lane["group"]: lane["weekday_weight"] for lane in plan["lanes"]
        },
    }


def demo_random_allocation(
    total_units: float = 1_000_000,
    start_year: int = 2024,
    end_year: int = 2026,
    trials: int = 5,
) -> None:
    """
    Run a quick Monte‑Carlo‑style demonstration: for a number of random dates
    within the given range, allocate workshare and print a concise report.
    This showcases the hybrid behaviour across weekdays.
    """
    for _ in range(trials):
        # random date
        year = random.randint(start_year, end_year)
        month = random.randint(1, 12)
        # ensure a valid day for the month
        day = random.randint(1, 28)  # safe for all months
        date = dt.date(year, month, day)

        alloc = allocate_hybrid(total_units=total_units, date=date)
        savings = summarize_hybrid_savings(total_units=total_units, date=date)

        print(
            f"Date {date.isoformat()} (weekday {alloc['weekday']}): "
            f"LLM units {alloc['llm_units']:,} "
            f"→ Savings {savings['token_savings_pct']}% "
            f"weights {', '.join(f'{g}:{w:.3f}' for g, w in zip(GROUPS, alloc['weight_vector']))}"
        )


# ----------------------------------------------------------------------
# Smoke test
# ----------------------------------------------------------------------
if __name__ == "__main__":
    # Use today's date for a deterministic run
    today = dt.date.today()
    try:
        result = allocate_hybrid(total_units=500_000, date=today)
        summary = summarize_hybrid_savings(total_units=500_000, date=today)
        print("Hybrid allocation result (truncated):")
        print({k: result[k] for k in ("total_units", "deterministic_units", "llm_units", "weekday", "lanes")})
        print("\nSummary:")
        print(summary)
        print("\nRunning demo_random_allocation()...")
        demo_random_allocation(trials=3)
    except Exception as exc:
        print(f"Error during smoke test: {exc}", file=sys.stderr)
        sys.exit(1)