# DARWIN HAMMER — match 1903, survivor 3
# gen: 5
# parent_a: hybrid_hybrid_nlms_omni_cha_hybrid_rectified_flo_m835_s3.py (gen4)
# parent_b: hybrid_hybrid_hybrid_minimu_hybrid_percyphon_hyb_m992_s0.py (gen3)
# born: 2026-05-29T23:39:38Z

"""Hybrid NLMS‑KAN & Bayesian Minimum‑Cost Tree Engine
====================================================

Parent A – *Hybrid NLMS‑KAN Flow Graph*  
 Provides a normalized‑least‑mean‑squares (NLMS) linear predictor that
 operates on non‑linear features generated by a Kolmogorov‑Arnold Network
 (KAN) built from spline‑like bases.

Parent B – *Hybrid Minimum‑Cost Tree / Bayesian Update*  
 Computes Bayesian posteriors `P(edge | evidence)` for graph edges and
 uses them to guide a minimum‑cost tree construction.  The posterior is
 updated with a classic Bayes rule using a likelihood derived from new
 evidence.

**Mathematical Bridge**  
For each graph node *i* we construct a feature vector  


x_i^g = Σ_{j∈N(i)}  impedance_{ij} · φ_j                (1)
z_i(t) = t·x1_i + (1‑t)·x0_i                             (2)
u_i(t) = [ x_i^g ; z_i(t) ]                             (3)
ψ_i(t) = KAN(u_i(t); Θ)                                 (4)
ŷ_i(t) = w·ψ_i(t)                                       (5)
e_i    = v_i – ŷ_i                                      (6)


The NLMS update (Parent A) is  


w ← w + μ·e_i·ψ_i / (‖ψ_i‖² + ε)                        (7)


From Parent B we have a Bayesian edge posterior  


m   = likelihood·prior + false_pos·(1‑prior)            (8)
p   = prior·likelihood / m                              (9)


We *couple* the two systems by **using the edge posterior as a node‑wise
modulation of the NLMS step size**:


μ_i = μ · ⟨p_edge⟩_{edges incident to i}                (10)


Thus the adaptive filter learns a linear combination of KAN‑encoded
graph‑temporal features while the confidence in the surrounding graph
structure (encoded by the Bayesian posterior) directly scales the learning
rate.

The code below implements:
1. `kan_transform` – a lightweight KAN‑style spline expansion.
2. `nlms_update` – the normalized LMS weight adaptation.
3. `bayes_update_edge` – Bayesian posterior update for an edge.
4. `hybrid_predict` – full forward pass (1‑5) for a node.
5. `hybrid_update_graph` – combines (6‑10) for every node and updates
   edge posteriors.

A minimal smoke test builds a random graph, runs one hybrid update step,
and prints the updated weight vector and edge posteriors.
"""

from __future__ import annotations

import math
import random
import sys
from pathlib import Path
from dataclasses import dataclass
from typing import Dict, List, Tuple, Set, FrozenSet

import numpy as np

# ----------------------------------------------------------------------
# Parent A – NLMS & KAN core
# ----------------------------------------------------------------------


def kan_transform(u: np.ndarray, theta: np.ndarray) -> np.ndarray:
    """
    Simple KAN‑style spline expansion.
    For each component of ``u`` we apply a quadratic B‑spline‑like basis
    and then a learned linear mixing given by ``theta``.
    The implementation uses a tanh non‑linearity as a surrogate.
    """
    # Quadratic “spline” basis (max(0, u)^2)
    spline = np.maximum(0.0, u) ** 2
    # Linear mixing and smooth non‑linearity
    return np.tanh(spline @ theta)


def nlms_update(
    w: np.ndarray,
    psi: np.ndarray,
    target: float,
    mu: float = 0.1,
    eps: float = 1e-6,
) -> Tuple[np.ndarray, float]:
    """
    Normalized LMS weight adaptation.
    Returns the updated weight vector and the instantaneous error.
    """
    pred = float(w @ psi)
    e = target - pred
    norm_sq = float(np.linalg.norm(psi) ** 2)
    w_new = w + mu * e * psi / (norm_sq + eps)
    return w_new, e


# ----------------------------------------------------------------------
# Parent B – Bayesian edge posterior utilities
# ----------------------------------------------------------------------


def bayes_marginal(prior: float, likelihood: float, false_positive: float) -> float:
    """Compute the marginal probability (8)."""
    return likelihood * prior + false_positive * (1.0 - prior)


def bayes_update(prior: float, likelihood: float, marginal: float) -> float:
    """Compute the posterior probability (9)."""
    return prior * likelihood / marginal


def bayes_update_edge(
    prior: float, likelihood: float, false_positive: float = 0.01
) -> float:
    """
    Full Bayesian update for a single edge.
    ``false_positive`` is a small constant modelling spurious evidence.
    """
    m = bayes_marginal(prior, likelihood, false_positive)
    if m <= 0.0:
        return prior  # safeguard
    return bayes_update(prior, likelihood, m)


# ----------------------------------------------------------------------
# Graph data structures
# ----------------------------------------------------------------------


NodeId = int
EdgeKey = FrozenSet[NodeId]


@dataclass
class Node:
    """Static node data."""
    pos: np.ndarray               # 2‑D position vector
    neighbors: List[NodeId]       # adjacent node identifiers
    impedance: Dict[NodeId, float]  # impedance weight per neighbour


def build_random_graph(num_nodes: int, seed: int = 0) -> Tuple[Dict[NodeId, Node], Dict[EdgeKey, float]]:
    """
    Creates a random undirected graph with symmetric impedances
    and uniform edge priors (0.5).
    """
    random.seed(seed)
    np.random.seed(seed)

    nodes: Dict[NodeId, Node] = {}
    for i in range(num_nodes):
        pos = np.random.rand(2)
        nodes[i] = Node(pos=pos, neighbors=[], impedance={})

    # Random edges (ensure connectivity)
    edges: Dict[EdgeKey, float] = {}
    for i in range(num_nodes):
        for j in range(i + 1, num_nodes):
            if random.random() < 0.3:  # 30 % edge probability
                imp = random.uniform(0.1, 1.0)
                nodes[i].neighbors.append(j)
                nodes[i].impedance[j] = imp
                nodes[j].neighbors.append(i)
                nodes[j].impedance[i] = imp
                edges[frozenset({i, j})] = 0.5  # prior probability

    # Guarantee at least a spanning tree if graph is too sparse
    if not edges:
        for i in range(num_nodes - 1):
            imp = random.uniform(0.1, 1.0)
            nodes[i].neighbors.append(i + 1)
            nodes[i].impedance[i + 1] = imp
            nodes[i + 1].neighbors.append(i)
            nodes[i + 1].impedance[i] = imp
            edges[frozenset({i, i + 1})] = 0.5

    return nodes, edges


# ----------------------------------------------------------------------
# Hybrid forward and learning passes
# ----------------------------------------------------------------------


def hybrid_predict(
    node_id: NodeId,
    nodes: Dict[NodeId, Node],
    w: np.ndarray,
    theta: np.ndarray,
    t: float,
) -> Tuple[float, np.ndarray]:
    """
    Computes the prediction ŷ_i(t) (5) and returns the KAN feature ψ_i(t).
    """
    node = nodes[node_id]

    # (1) impedance‑weighted neighbourhood vector (2‑D)
    x_g = np.zeros(2)
    for nbr in node.neighbors:
        imp = node.impedance[nbr]
        phi_j = nodes[nbr].pos
        x_g += imp * phi_j

    # Temporal states for rectified flow (2)
    x0 = node.pos
    # A simple forward state: add a small random drift
    x1 = x0 + 0.05 * np.random.randn(2)

    z = t * x1 + (1.0 - t) * x0

    # Concatenated raw vector (3)
    u = np.concatenate([x_g, z])

    # KAN expansion (4)
    psi = kan_transform(u, theta)

    # Linear prediction (5)
    y_hat = float(w @ psi)

    return y_hat, psi


def hybrid_update_graph(
    nodes: Dict[NodeId, Node],
    edges: Dict[EdgeKey, float],
    observations: Dict[NodeId, float],
    w: np.ndarray,
    theta: np.ndarray,
    mu: float = 0.1,
    eps: float = 1e-6,
    t: float = 0.5,
    false_positive: float = 0.01,
) -> Tuple[np.ndarray, Dict[EdgeKey, float]]:
    """
    Executes one hybrid learning step:
      * forward pass for every node,
      * NLMS weight adaptation with a node‑wise learning‑rate μ_i
        scaled by the average posterior of incident edges,
      * Bayesian edge posterior update using a likelihood derived from
        the absolute prediction error.
    Returns the updated weight vector and edge posterior dictionary.
    """
    w_curr = w.copy()
    for nid, target in observations.items():
        # Forward prediction
        y_hat, psi = hybrid_predict(nid, nodes, w_curr, theta, t)

        # Compute average posterior of incident edges
        incident_edges = [
            frozenset({nid, nbr}) for nbr in nodes[nid].neighbors
        ]
        if incident_edges:
            avg_post = np.mean([edges[ek] for ek in incident_edges])
        else:
            avg_post = 0.5  # fallback

        # Modulated learning rate (10)
        mu_i = mu * avg_post

        # NLMS update with μ_i
        w_curr, e = nlms_update(w_curr, psi, target, mu=mu_i, eps=eps)

        # Likelihood from error – larger error ⇒ smaller likelihood
        likelihood = math.exp(- (e ** 2))

        # Update posteriors of incident edges
        for ek in incident_edges:
            prior = edges[ek]
            post = bayes_update_edge(prior, likelihood, false_positive)
            edges[ek] = post

    return w_curr, edges


# ----------------------------------------------------------------------
# Smoke test
# ----------------------------------------------------------------------


if __name__ == "__main__":
    # Build a tiny random graph
    NUM_NODES = 6
    nodes, edges = build_random_graph(NUM_NODES, seed=42)

    # Random initial NLMS weight vector
    INPUT_DIM = 4               # length of u = [x_g (2), z (2)]
    HIDDEN_DIM = 8              # size of KAN feature vector ψ
    theta = np.random.randn(INPUT_DIM, HIDDEN_DIM) * 0.1
    w = np.zeros(HIDDEN_DIM)

    # Synthetic observations: true velocity = dot(pos, [1.2, -0.7]) + noise
    observations: Dict[NodeId, float] = {}
    true_coef = np.array([1.2, -0.7])
    for nid, node in nodes.items():
        true_vel = float(node.pos @ true_coef) + 0.01 * np.random.randn()
        observations[nid] = true_vel

    # Perform a single hybrid update
    w_updated, edges_updated = hybrid_update_graph(
        nodes,
        edges,
        observations,
        w,
        theta,
        mu=0.2,
        eps=1e-6,
        t=0.4,
        false_positive=0.02,
    )

    # Output results
    print("Updated NLMS weight vector (w):")
    print(w_updated)
    print("\nSample of updated edge posteriors:")
    for ek, post in list(edges_updated.items())[:5]:
        print(f"Edge {sorted(ek)} → posterior = {post:.4f}")

    sys.exit(0)