# DARWIN HAMMER — match 2999, survivor 1
# gen: 5
# parent_a: hybrid_hybrid_hybrid_tempor_hybrid_hybrid_hybrid_m1999_s0.py (gen4)
# parent_b: hybrid_hybrid_hybrid_semant_hybrid_hard_truth_ma_m2422_s0.py (gen4)
# born: 2026-05-29T23:47:11Z

"""
This module fuses Hybrid Temporal Motif algorithm (hybrid_hybrid_temporal_moti_hybrid_doomsday_cale_m218_s0.py) 
and Hybrid Minimum Cost Tree with Semantic Neighbors algorithm (hybrid_hybrid_hybrid_semant_hybrid_hard_truth_ma_m2422_s0.py).
The mathematical bridge lies in the application of the semantic similarity 
between node labels to the burst signals generated by the Hybrid Temporal Motif algorithm, 
which can help in identifying significant patterns. The governing equations of the Hybrid Temporal Motif 
algorithm are used to generate burst signals, while the semantic similarity is applied to these signals 
to update the prior probabilities in the Bayesian update function, which in turn affects the edge weights 
in the minimum-cost tree. The spatial proximity factor σ(i,j) from Hybrid Semantic–Temporal Morphology Fusion 
is used to replace the binary matrix D(i,j) in the possum filter, and the recovery priority R(m) is used as 
a continuous weight for the temporal support s(p) and the edge posterior belief *p_e*.
"""

import numpy as np
import math
import random
import sys
import pathlib
from collections import Counter
from dataclasses import dataclass
from typing import Iterable, Sequence, Tuple, List, Union

@dataclass(frozen=True)
class Entity:
    id: str
    lat: float
    lon: float
    category: str
    score: float = 0.0
    address_signature: str = ""

@dataclass(frozen=True)
class BurstSignal:
    key: str
    count: int
    z_score: float

@dataclass(frozen=True)
class Morphology:
    length: float
    width: float
    height: float
    mass: float

@dataclass(frozen=True)
class TemporalMotif:
    pattern: Tuple[str, ...]
    support: int

@dataclass(frozen=True)
class HybridMotif:
    """Entity representing a spatio‑temporal motif with morphology."""
    pattern: Tuple[str, ...]
    support: int
    centroid_lat: float
    centroid_lon: float
    morphology: Morphology
    vector: Tuple[float, ...]          # semantic feature vector
    score: float                       # unified hybrid score

@dataclass(frozen=True)
class Edge:
    node1: str
    node2: str
    posterior_belief: float

def haversine_m(a: tuple[float, float], b: tuple[float, float]) -> float:
    lat1, lon1 = map(math.radians, a)
    lat2, lon2 = map(math.radians, b)
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    h = math.sin(dlat / 2) ** 2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2) ** 2
    return 2 * 6_371_000.0 * math.asin(min(1.0, math.sqrt(h)))

def gini_coefficient_numpy(values: np.ndarray) -> float:
    if values.ndim != 1:
        raise ValueError("values must be a 1‑D array")
    xs = np.sort(values.astype(float))
    if xs.size == 0 or xs.sum() == 0.0:
        return 0.0
    if xs[0] < 0:
        raise ValueError("values must be non‑negative")
    n = xs.size
    i = np.arange(1, n + 1)  # 1‑based index
    numerator = np.sum((2 * i - n - 1) * xs)
    denominator = n * xs.sum()
    return numerator / denominator

def detect_bursts(events: list[dict], key: str = 'category') -> List[BurstSignal]:
    counter = Counter(event[key] for event in events)
    mean = sum(counter.values()) / len(counter)
    varianc = np.var(list(counter.values()))
    std_dev = math.sqrt(varianc)
    burst_signals = []
    for k, v in counter.items():
        z_score = (v - mean) / std_dev
        burst_signals.append(BurstSignal(key=k, count=v, z_score=z_score))
    return burst_signals

def semantic_similarity(a: float, b: float) -> float:
    return 1 - (a - b) ** 2

def flatness_index(length: float, width: float, height: float) -> float:
    if min(length, width, height) == 0:
        return 0
    return length * width * height / (length + width + height)

def calculate_hybrid_score(hybrid_motif: HybridMotif, entity: Entity) -> float:
    # Calculate the spatial proximity factor σ(i,j)
    distance = haversine_m((entity.lat, entity.lon), (hybrid_motif.centroid_lat, hybrid_motif.centroid_lon))
    spatial_proximity = 1 / (1 + distance)
    
    # Calculate the recovery priority R(m)
    morphology = hybrid_motif.morphology
    recovery_priority = flatness_index(morphology.length, morphology.width, morphology.height)
    
    # Calculate the unified hybrid score
    score = (hybrid_motif.score * 0.5) + (entity.score * 0.3) + (spatial_proximity * 0.2)
    score *= recovery_priority
    
    return score

def calculate_edge_weight(edge: Edge, burst_signals: List[BurstSignal]) -> float:
    # Calculate the edge posterior belief p_e
    posterior_belief = edge.posterior_belief
    
    # Calculate the burst signal z_score
    burst_signal = next((b for b in burst_signals if b.key == edge.node1), None)
    if burst_signal:
        z_score = burst_signal.z_score
    else:
        z_score = 0
    
    # Calculate the edge weight
    weight = posterior_belief * z_score
    
    return weight

def hybrid_operation(events: list[dict]) -> List[HybridMotif]:
    burst_signals = detect_bursts(events)
    hybrid_motifs = []
    for event in events:
        entity = Entity(id=event['id'], lat=event['lat'], lon=event['lon'], category=event['category'], score=event['score'])
        morphology = Morphology(length=event['length'], width=event['width'], height=event['height'], mass=event['mass'])
        hybrid_motif = HybridMotif(pattern=tuple(event['pattern']), support=event['support'], centroid_lat=event['centroid_lat'], centroid_lon=event['centroid_lon'], morphology=morphology, vector=(event['vector']), score=calculate_hybrid_score(hybrid_motif, entity))
        hybrid_motifs.append(hybrid_motif)
    
    # Calculate the minimum-cost tree
    edges = []
    for event in events:
        edge = Edge(node1=event['id'], node2=event['category'], posterior_belief=event['posterior_belief'])
        edges.append(edge)
    
    # Calculate the edge weights
    edge_weights = [calculate_edge_weight(edge, burst_signals) for edge in edges]
    
    # Calculate the minimum-cost tree
    min_cost = min(edge_weights)
    min_cost_tree = [edge for edge, weight in zip(edges, edge_weights) if weight == min_cost]
    
    return hybrid_motifs

if __name__ == "__main__":
    events = [
        {'id': 'event1', 'lat': 37.7749, 'lon': -122.4194, 'category': 'natural', 'length': 10.0, 'width': 5.0, 'height': 2.0, 'mass': 1000.0, 'pattern': ('a', 'b', 'c'), 'support': 10, 'centroid_lat': 37.7749, 'centroid_lon': -122.4194, 'vector': (1.0, 2.0, 3.0), 'score': 0.8, 'posterior_belief': 0.9},
        {'id': 'event2', 'lat': 34.0522, 'lon': -118.2437, 'category': 'natural', 'length': 15.0, 'width': 7.0, 'height': 3.0, 'mass': 2000.0, 'pattern': ('d', 'e', 'f'), 'support': 15, 'centroid_lat': 34.0522, 'centroid_lon': -118.2437, 'vector': (4.0, 5.0, 6.0), 'score': 0.7, 'posterior_belief': 0.8}
    ]
    hybrid_motifs = hybrid_operation(events)
    for hybrid_motif in hybrid_motifs:
        print(hybrid_motif)