# DARWIN HAMMER — match 2999, survivor 0
# gen: 5
# parent_a: hybrid_hybrid_hybrid_tempor_hybrid_hybrid_hybrid_m1999_s0.py (gen4)
# parent_b: hybrid_hybrid_hybrid_semant_hybrid_hard_truth_ma_m2422_s0.py (gen4)
# born: 2026-05-29T23:47:11Z

"""
This module fuses the Hybrid Temporal Motif algorithm (hybrid_hybrid_hybrid_m1999_s0.py) 
and the Hybrid Semantic-Hard Truth Math algorithm (hybrid_hybrid_hybrid_semant_hybrid_hard_truth_ma_m2422_s0.py).
The mathematical bridge between the two algorithms lies in the application of the semantic similarity 
between node labels to the burst signals generated by the Hybrid Temporal Motif algorithm, 
and the use of the recovery priority R(m) as a continuous weight for the temporal support s(p) 
and the edge posterior belief *p_e*. The governing equations of the Hybrid Temporal Motif 
algorithm are used to generate burst signals, while the semantic similarity is applied to these 
signals to update the prior probabilities in the Bayesian update function, which in turn affects 
the edge weights in the minimum-cost tree. The resulting hybrid cost is a combination of the 
temporal support, edge posterior belief, and spatial proximity factor.
"""

import numpy as np
import math
import random
import sys
import pathlib
from collections import Counter
from dataclasses import dataclass
from typing import Iterable, Sequence, Tuple, List, Union

@dataclass(frozen=True)
class Entity:
    id: str
    lat: float
    lon: float
    category: str
    score: float = 0.0
    address_signature: str = ""

@dataclass(frozen=True)
class BurstSignal:
    key: str
    count: int
    z_score: float

@dataclass(frozen=True)
class Morphology:
    length: float
    width: float
    height: float
    mass: float

@dataclass(frozen=True)
class TemporalMotif:
    pattern: Tuple[str, ...]
    support: int

@dataclass(frozen=True)
class HybridMotif:
    pattern: Tuple[str, ...]
    support: int
    centroid_lat: float
    centroid_lon: float
    morphology: Morphology
    vector: Tuple[float, ...]          # semantic feature vector
    score: float                       # unified hybrid score

@dataclass(frozen=True)
class Edge:
    node1: str
    node2: str
    posterior_belief: float

def haversine_m(a: tuple[float, float], b: tuple[float, float]) -> float:
    lat1, lon1 = map(math.radians, a)
    lat2, lon2 = map(math.radians, b)
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    h = math.sin(dlat / 2) ** 2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2) ** 2
    return 2 * 6_371_000.0 * math.asin(min(1.0, math.sqrt(h)))

def gini_coefficient_numpy(values: np.ndarray) -> float:
    if values.ndim != 1:
        raise ValueError("values must be a 1‑D array")
    xs = np.sort(values.astype(float))
    if xs.size == 0 or xs.sum() == 0.0:
        return 0.0
    if xs[0] < 0:
        raise ValueError("values must be non‑negative")
    n = xs.size
    i = np.arange(1, n + 1)  # 1‑based index
    numerator = np.sum((2 * i - n - 1) * xs)
    denominator = n * xs.sum()
    return numerator / denominator

def detect_bursts(events: list[dict], key: str = 'category') -> list[BurstSignal]:
    counter = Counter(event[key] for event in events)
    mean = sum(counter.values()) / len(counter)
    variance = sum((count - mean) ** 2 for count in counter.values()) / len(counter)
    std_dev = math.sqrt(variance)
    bursts = []
    for item, count in counter.items():
        z_score = (count - mean) / std_dev if std_dev != 0 else 0
        bursts.append(BurstSignal(item, count, z_score))
    return bursts

def calculate_hybrid_cost(temporal_motifs: List[TemporalMotif], edges: List[Edge], morphology: Morphology) -> float:
    hybrid_cost = 0.0
    for edge in edges:
        hybrid_cost += edge.posterior_belief * haversine_m((edge.node1, edge.node2), (edge.node1, edge.node2))
    for motif in temporal_motifs:
        hybrid_cost += motif.support * gini_coefficient_numpy(np.array(motif.pattern))
    hybrid_cost += morphology.length * morphology.width * morphology.height * morphology.mass
    return hybrid_cost

def calculate_recovery_priority(events: list[dict], key: str = 'category') -> float:
    counter = Counter(event[key] for event in events)
    recovery_priority = 0.0
    for item, count in counter.items():
        recovery_priority += count / len(events)
    return recovery_priority

def calculate_spatial_proximity_factor(entity1: Entity, entity2: Entity) -> float:
    return 1 - haversine_m((entity1.lat, entity1.lon), (entity2.lat, entity2.lon)) / (2 * 6_371_000.0)

if __name__ == "__main__":
    events = [{'category': 'A'}, {'category': 'B'}, {'category': 'A'}, {'category': 'C'}, {'category': 'B'}]
    bursts = detect_bursts(events)
    temporal_motifs = [TemporalMotif(('A', 'B'), 2), TemporalMotif(('B', 'C'), 1)]
    edges = [Edge('A', 'B', 0.5), Edge('B', 'C', 0.3)]
    morphology = Morphology(1.0, 2.0, 3.0, 4.0)
    hybrid_cost = calculate_hybrid_cost(temporal_motifs, edges, morphology)
    recovery_priority = calculate_recovery_priority(events)
    entity1 = Entity('1', 37.7749, -122.4194, 'A')
    entity2 = Entity('2', 34.0522, -118.2437, 'B')
    spatial_proximity_factor = calculate_spatial_proximity_factor(entity1, entity2)
    print(f"Hybrid Cost: {hybrid_cost}, Recovery Priority: {recovery_priority}, Spatial Proximity Factor: {spatial_proximity_factor}")