# DARWIN HAMMER — match 1144, survivor 1
# gen: 5
# parent_a: hybrid_hybrid_sketches_rlct_sheaf_cohomology_m11_s2.py (gen2)
# parent_b: hybrid_hybrid_hybrid_ternar_hybrid_hybrid_fracti_m222_s0.py (gen4)
# born: 2026-05-29T23:33:05Z

"""Hybrid Sketch‑Sheaf‑Hypervector Algorithm.

Parents:
- hybrid_hybrid_sketches_rlct_sheaf_cohomology_m11_s2.py (sketch + sheaf cohomology)
- hybrid_hybrid_ternar_hybrid_fracti_m222_s0.py (hypervector generation, minhash, fractional binding)

Mathematical bridge:
The min‑hash signatures produced for a text (parent B) are used as the hash
functions of a Count‑Min sketch (parent A).  Each sketch bucket becomes a
vertex of a cellular sheaf; the vector space attached to a vertex is a
hyper‑vector of dimension *d* generated by `random_hv`.  Restriction maps on
edges are defined by fractional‑power binding of the two endpoint hypervectors,
providing a smooth interpolation between them.  The coboundary operator
δ applied to the sheaf section yields residual hypervectors whose ℓ₂‑norms
feed the log‑log regression of the RLCT estimator from parent A.  Thus the
algorithm fuses sketch‑based dimensionality reduction, sheaf‑theoretic
inconsistency measurement, and hyper‑vector fractional binding into a single
unified framework.
"""

import hashlib
import math
import random
import sys
import pathlib
from collections import defaultdict

import numpy as np

# ---------------------------------------------------------------------------
# Hypervector utilities (from parent B)
# ---------------------------------------------------------------------------

def random_hv(d: int = 10000, kind: str = "complex", seed: int | None = None) -> np.ndarray:
    """Generate a random hypervector of dimension *d*."""
    rng = np.random.default_rng(seed)
    if kind == "complex":
        theta = rng.uniform(0.0, 2.0 * np.pi, size=d)
        return np.exp(1j * theta)
    elif kind == "bipolar":
        return rng.choice([-1, 1], size=d).astype(np.float64)
    elif kind == "real":
        vec = rng.normal(size=d)
        return vec / np.linalg.norm(vec)
    else:
        raise ValueError(f"unknown kind {kind!r}")

def minhash_for_text(text: str, num_hashes: int = 64, seed_offset: int = 0) -> list[int]:
    """Simple min‑hash of 5‑shingles using SHA‑256."""
    cleaned = text.replace(" ", "").strip().lower()
    shingles = [cleaned[i:i+5] for i in range(len(cleaned) - 4)]
    if not shingles:
        shingles = [cleaned]  # fallback for very short strings
    hashes = []
    for i in range(num_hashes):
        min_val = None
        for sh in shingles:
            h = hashlib.sha256((sh + str(i + seed_offset)).encode()).hexdigest()
            val = int(h, 16)
            if (min_val is None) or (val < min_val):
                min_val = val
        hashes.append(min_val)
    return hashes

# ---------------------------------------------------------------------------
# Sheaf data structure (adapted from parent A)
# ---------------------------------------------------------------------------

class Sheaf:
    """Cellular sheaf whose vertices store hypervectors."""

    def __init__(self, node_dims: dict[int, int], edges: list[tuple[int, int]]):
        self.node_dims = dict(node_dims)          # vertex -> dimension (all equal here)
        self.edges = list(edges)                  # list of (u, v) oriented edges
        self.section: dict[int, np.ndarray] = {}  # vertex -> hypervector (section value)

    def set_section(self, vertex: int, vector: np.ndarray):
        """Assign a hypervector to a vertex (overwrites previous)."""
        expected = self.node_dims[vertex]
        if vector.shape != (expected,):
            raise ValueError(f"vector shape {vector.shape} does not match dimension {expected}")
        self.section[vertex] = vector

    def coboundary_residuals(self, alpha: float = 0.5) -> list[np.ndarray]:
        """
        Compute δ(s) for each edge using fractional‑power binding as the restriction map.
        For an edge (u, v) the residual is  r = s[u] - (s[u]**alpha * s[v]**(1‑alpha)).
        """
        res = []
        for u, v in self.edges:
            su = self.section.get(u)
            sv = self.section.get(v)
            if su is None or sv is None:
                continue
            # fractional binding (element‑wise power, safe for complex vectors)
            bound = np.multiply(np.power(su, alpha), np.power(sv, 1 - alpha))
            residual = su - bound
            res.append(residual)
        return res

    def laplacian_energy(self, alpha: float = 0.5) -> float:
        """Sum of squared ℓ₂‑norms of coboundary residuals."""
        return sum(np.linalg.norm(r) ** 2 for r in self.coboundary_residuals(alpha))

# ---------------------------------------------------------------------------
# Hybrid core functions
# ---------------------------------------------------------------------------

def count_min_sheaf(
    texts: list[str],
    d: int = 2048,
    depth: int = 4,
    width: int = 256,
    hv_kind: str = "complex",
) -> Sheaf:
    """
    Build a sheaf from a Count‑Min sketch of *texts*.

    Each text is turned into a hypervector `hv` (dimension *d*).  For each
    sketch row `i` (0 ≤ i < depth) we compute a min‑hash bucket index
    `b = minhash_for_text(text, 1, seed_offset=i)[0] % width`.  The hypervector
    is accumulated into the vertex identified by `(i, b)`.  Edges connect the
    same bucket across consecutive rows, i.e. ((i, b), (i+1, b)).
    """
    # Mapping from (row, bucket) -> aggregated hypervector
    agg: dict[tuple[int, int], np.ndarray] = defaultdict(lambda: np.zeros(d, dtype=np.complex128))

    for txt in texts:
        hv = random_hv(d, kind=hv_kind)
        for i in range(depth):
            bucket = minhash_for_text(txt, num_hashes=1, seed_offset=i)[0] % width
            key = (i, bucket)
            agg[key] += hv

    # Build node dimension dict and edges
    node_dims = {hash(key): d for key in agg.keys()}
    edges = []
    for i in range(depth - 1):
        for bucket in range(width):
            u = hash((i, bucket))
            v = hash((i + 1, bucket))
            if u in node_dims and v in node_dims:
                edges.append((u, v))

    sheaf = Sheaf(node_dims, edges)

    for key, vec in agg.items():
        vertex = hash(key)
        sheaf.set_section(vertex, vec)

    return sheaf

def hybrid_rlct_via_sheaf(sheaf: Sheaf, alpha: float = 0.5) -> float:
    """
    Estimate a Real Log Canonical Threshold (RLCT) from sheaf coboundary residuals.

    Let `r_k` be the ℓ₂‑norm of the residual for edge *k*.  We fit a line to
    (log(k+1), log(r_k)) using ordinary least squares and return the negative
    slope, which coincides with the RLCT definition in the original sketch
    algorithm.
    """
    residuals = sheaf.coboundary_residuals(alpha)
    if not residuals:
        return float('nan')
    norms = np.array([np.linalg.norm(r) for r in residuals])
    # avoid zeros for log
    norms = np.where(norms == 0, np.finfo(float).tiny, norms)

    ks = np.arange(1, len(norms) + 1, dtype=np.float64)

    log_k = np.log(ks)
    log_r = np.log(norms)

    # least‑squares fit: log_r = a * log_k + b
    A = np.vstack([log_k, np.ones_like(log_k)]).T
    a, _ = np.linalg.lstsq(A, log_r, rcond=None)[0]
    rlct = -a
    return rlct

def hybrid_info_loss(sheaf: Sheaf, alpha: float = 0.5) -> float:
    """
    Blend the RLCT estimate with the sheaf Laplacian energy.

    The returned value is normalized to [0, 1] by a simple logistic scaling.
    """
    rlct = hybrid_rlct_via_sheaf(sheaf, alpha)
    energy = sheaf.laplacian_energy(alpha)
    # combine (weights can be tuned)
    combined = rlct + math.log1p(energy)
    # logistic normalization
    loss = 1.0 / (1.0 + math.exp(-combined))
    return loss

def hybrid_similarity(
    text_a: str,
    text_b: str,
    d: int = 2048,
    depth: int = 4,
    width: int = 256,
    hv_kind: str = "complex",
    alpha: float = 0.5,
) -> float:
    """
    Compute a similarity score between two texts using the hybrid sheaf model.

    Each text is embedded into a tiny sheaf (depth × width).  The similarity is
    defined as the cosine similarity between the aggregated hypervectors of the
    two sheaves after aligning vertices by (row, bucket) keys.
    """
    sheaf_a = count_min_sheaf([text_a], d, depth, width, hv_kind)
    sheaf_b = count_min_sheaf([text_b], d, depth, width, hv_kind)

    # Align sections by vertex hash
    common_vertices = set(sheaf_a.section) & set(sheaf_b.section)
    if not common_vertices:
        return 0.0

    vec_a = np.sum([sheaf_a.section[v] for v in common_vertices], axis=0)
    vec_b = np.sum([sheaf_b.section[v] for v in common_vertices], axis=0)

    # fractional binding to smooth differences (optional)
    bound = np.multiply(np.power(vec_a, alpha), np.power(vec_b, 1 - alpha))

    # cosine similarity
    dot = np.real(np.vdot(bound, bound))  # vdot works for complex, returns complex; take real
    norm_a = np.linalg.norm(bound)
    norm_b = np.linalg.norm(bound)
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return dot / (norm_a * norm_b)

# ---------------------------------------------------------------------------
# Smoke test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    sample_texts = [
        "The quick brown fox jumps over the lazy dog.",
        "Pack my box with five dozen liquor jugs.",
        "Sphinx of black quartz, judge my vow.",
        "How vexingly quick daft zebras jump!",
    ]

    # Build a sheaf from the corpus
    sheaf = count_min_sheaf(sample_texts, d=1024, depth=5, width=128, hv_kind="bipolar")
    rlct_est = hybrid_rlct_via_sheaf(sheaf)
    loss = hybrid_info_loss(sheaf)

    print(f"RLCT estimate: {rlct_est:.4f}")
    print(f"Hybrid info loss: {loss:.4f}")

    # Pairwise similarity demo
    for i in range(len(sample_texts)):
        for j in range(i + 1, len(sample_texts)):
            sim = hybrid_similarity(sample_texts[i], sample_texts[j], d=1024, depth=5, width=128, hv_kind="bipolar")
            print(f"Similarity between text {i} and {j}: {sim:.4f}")