# DARWIN HAMMER — match 5601, survivor 3
# gen: 5
# parent_a: hybrid_hybrid_hybrid_regret_hybrid_hybrid_hybrid_m1383_s0.py (gen4)
# parent_b: hybrid_hybrid_hdc_hybrid_hy_hybrid_hybrid_rbf_su_m182_s3.py (gen4)
# born: 2026-05-30T00:03:31Z

"""Hybrid Algorithm: Regret‑Weighted Strategy + RBF Surrogate Modulation
Parents:
- hybrid_hybrid_hybrid_regret_hybrid_hybrid_hybrid_m1383_s0 (Regret‑Weighted Strategy + Bayesian Kinetic Scoring)
- hybrid_hybrid_hdc_hybrid_hy_hybrid_hybrid_rbf_su_m182_s3 (High‑Dimensional Random Vectors + RBF Surrogate)

Mathematical Bridge:
The regret‑weighted probabilities generated by the regret engine are mapped to a
high‑dimensional binary modulation vector using the same symbolic hashing that
produces the random vectors of the second parent.  This vector is then used to
modulate the centres and weights of an RBF surrogate (via element‑wise binding
and similarity scaling).  The surrogate’s prediction supplies a likelihood that
updates the Bayesian posterior of each action, thereby closing the loop between
the two topologies.
"""

from __future__ import annotations

import math
import random
import sys
import pathlib
import hashlib
from dataclasses import dataclass
from typing import List, Sequence, Dict, Tuple

import numpy as np

# ----------------------------------------------------------------------
# Data structures (shared from Parent A)
# ----------------------------------------------------------------------
@dataclass(frozen=True)
class MathAction:
    id: str
    expected_value: float
    cost: float = 0.0
    risk: float = 0.0


@dataclass(frozen=True)
class MathCounterfactual:
    action_id: str
    outcome_value: float
    probability: float = 1.0


# ----------------------------------------------------------------------
# Vector utilities (from Parent B)
# ----------------------------------------------------------------------
Vector = List[int]
FloatVector = Sequence[float]


def random_vector(dim: int = 10000, seed: str | int | None = None) -> Vector:
    rng = random.Random(seed)
    return [1 if rng.getrandbits(1) else -1 for _ in range(dim)]


def symbol_vector(symbol: str, dim: int = 10000) -> Vector:
    seed = int.from_bytes(hashlib.sha256(symbol.encode("utf-8")).digest()[:8], "big")
    return random_vector(dim, seed)


def bind(a: Vector, b: Vector) -> Vector:
    if len(a) != len(b):
        raise ValueError("vectors must have equal length")
    return [x * y for x, y in zip(a, b)]


def bundle(vectors: List[Vector]) -> Vector:
    if not vectors:
        raise ValueError("at least one vector is required")
    dim = len(vectors[0])
    if any(len(v) != dim for v in vectors):
        raise ValueError("vectors must have equal length")
    sums = np.zeros(dim, dtype=int)
    for v in vectors:
        sums += np.array(v, dtype=int)
    return [1 if x >= 0 else -1 for x in sums]


def similarity(a: Vector, b: Vector) -> float:
    if len(a) != len(b):
        raise ValueError("vectors must have equal length")
    if not a:
        raise ValueError("vectors must not be empty")
    return sum(x * y for x, y in zip(a, b)) / len(a)


def gaussian(r: float, epsilon: float = 1.0) -> float:
    return math.exp(-((epsilon * r) ** 2))


def euclidean(a: FloatVector, b: FloatVector) -> float:
    if len(a) != len(b):
        raise ValueError("vectors must have same dimension")
    return math.sqrt(sum((x - y) ** 2 for x, y in zip(a, b)))


# ----------------------------------------------------------------------
# RBF surrogate (from Parent B)
# ----------------------------------------------------------------------
@dataclass
class RBFSurrogate:
    centers: List[FloatVector]
    weights: List[float]
    epsilon: float = 1.0

    def predict(self, x: FloatVector) -> float:
        return sum(
            w * gaussian(euclidean(x, c), self.epsilon)
            for w, c in zip(self.weights, self.centers)
        )


def modulate_surrogate(surrogate: RBFSurrogate, modulation_vector: Vector) -> RBFSurrogate:
    """Modulate centres (by binding sign) and weights (by similarity)."""
    # Bind each centre (treated as integer vector) with the modulation vector
    modulated_centers = [
        bind([int(round(coord)) for coord in c], modulation_vector) for c in surrogate.centers
    ]
    # Scale each weight by the similarity between the modulation vector and an
    # all‑ones reference vector (acts as a global intensity factor)
    ref = [1] * len(modulation_vector)
    intensity = similarity(modulation_vector, ref)
    modulated_weights = [w * intensity for w in surrogate.weights]
    return RBFSurrogate(modulated_centers, modulated_weights, surrogate.epsilon)


# ----------------------------------------------------------------------
# Core hybrid functions
# ----------------------------------------------------------------------
def compute_regret_weighted_strategy(
    actions: List[MathAction],
    counterfactuals: List[MathCounterfactual],
) -> Dict[str, float]:
    """Return a normalized probability distribution over actions."""
    if not actions:
        return {}
    # Map counterfactual contributions
    cf: Dict[str, float] = {
        c.action_id: c.outcome_value * c.probability for c in counterfactuals
    }
    # Adjusted value for each action
    adjusted: Dict[str, float] = {
        a.id: a.expected_value - a.cost - a.risk + cf.get(a.id, 0.0) for a in actions
    }
    # Numerical stability: subtract max before exponentiation
    best = max(adjusted.values())
    raw_weights = {k: math.exp(v - best) for k, v in adjusted.items()}
    total = sum(raw_weights.values())
    return {k: w / total for k, w in raw_weights.items()}


def build_modulation_vector(
    strategy: Dict[str, float],
    dim: int = 2048,
) -> Vector:
    """
    Convert a regret‑weighted probability distribution into a high‑dimensional
    binary modulation vector.  Each action contributes its symbolic vector,
    signed by the sign of its probability weight, and all contributions are
    bundled (majority vote) into a single vector.
    """
    if not strategy:
        raise ValueError("strategy must contain at least one action")
    signed_vectors: List[Vector] = []
    for action_id, prob in strategy.items():
        base = symbol_vector(action_id, dim)
        sign = 1 if prob >= 0 else -1
        signed = bind(base, [sign] * dim)
        signed_vectors.append(signed)
    return bundle(signed_vectors)


def hybrid_bayesian_update(
    actions: List[MathAction],
    counterfactuals: List[MathCounterfactual],
    surrogate: RBFSurrogate,
    feature_vec: FloatVector,
    dim: int = 2048,
) -> Dict[str, float]:
    """
    End‑to‑end hybrid operation:
    1. Compute regret‑weighted strategy.
    2. Build modulation vector and modulate the RBF surrogate.
    3. Obtain a surrogate prediction for the supplied feature vector.
    4. Use the prediction as a likelihood to update the Bayesian posterior
       over actions (simple multiplicative update followed by normalization).
    Returns the posterior probability distribution over action ids.
    """
    # Step 1: regret‑weighted probabilities
    strategy = compute_regret_weighted_strategy(actions, counterfactuals)

    # Step 2: modulation
    mod_vec = build_modulation_vector(strategy, dim=dim)
    mod_surrogate = modulate_surrogate(surrogate, mod_vec)

    # Step 3: surrogate prediction (scalar likelihood factor)
    likelihood = math.exp(mod_surrogate.predict(feature_vec))

    # Step 4: Bayesian update (prior = strategy)
    unnorm = {aid: prob * likelihood for aid, prob in strategy.items()}
    total = sum(unnorm.values())
    if total == 0:
        # fallback to uniform if numerical collapse occurs
        return {aid: 1.0 / len(unnorm) for aid in unnorm}
    return {aid: val / total for aid, val in unnorm.items()}


def elect_leaders_via_bayesian_graph(
    posterior: Dict[str, float],
    top_n: int = 3,
) -> List[Tuple[str, float]]:
    """
    Select the top‑N actions according to the posterior distribution.
    Returns a list of (action_id, probability) sorted descending.
    """
    return sorted(posterior.items(), key=lambda kv: kv[1], reverse=True)[:top_n]


# ----------------------------------------------------------------------
# Smoke test
# ----------------------------------------------------------------------
if __name__ == "__main__":
    # Define a tiny problem instance
    actions = [
        MathAction(id="A", expected_value=5.0, cost=1.0, risk=0.5),
        MathAction(id="B", expected_value=3.0, cost=0.5, risk=0.2),
        MathAction(id="C", expected_value=4.0, cost=0.8, risk=0.3),
    ]
    counterfactuals = [
        MathCounterfactual(action_id="A", outcome_value=1.0, probability=0.6),
        MathCounterfactual(action_id="C", outcome_value=-0.5, probability=0.9),
    ]

    # Randomly initialise an RBF surrogate (small for the test)
    dim_feat = 5
    centers = [np.random.rand(dim_feat).tolist() for _ in range(4)]
    weights = [random.uniform(-1, 1) for _ in range(4)]
    surrogate = RBFSurrogate(centers=centers, weights=weights, epsilon=1.5)

    # Feature vector for prediction
    x = np.random.rand(dim_feat).tolist()

    # Run hybrid pipeline
    posterior = hybrid_bayesian_update(
        actions, counterfactuals, surrogate, feature_vec=x, dim=1024
    )
    leaders = elect_leaders_via_bayesian_graph(posterior, top_n=2)

    print("Posterior distribution:")
    for aid, prob in posterior.items():
        print(f"  {aid}: {prob:.4f}")

    print("\nTop leaders:")
    for aid, prob in leaders:
        print(f"  {aid}: {prob:.4f}")

    sys.exit(0)