# DARWIN HAMMER — match 630, survivor 1
# gen: 5
# parent_a: hybrid_hybrid_hybrid_hybrid_hybrid_nlms_omni_cha_m362_s0.py (gen4)
# parent_b: hybrid_hybrid_hybrid_liquid_hybrid_hybrid_sheaf__m187_s1.py (gen3)
# born: 2026-05-29T23:30:07Z

"""Hybrid NLMS‑Omni‑Chaotic‑Sprint + Diffusion‑Forcing Sheaf Signature

This module fuses the core mathematics of two parent algorithms:

* **Parent A** – `hybrid_hybrid_hybrid_hybrid_hybrid_nlms_omni_cha_m362_s0.py`  
  Provides an NLMS adaptive filter, a store dynamics model and a
  bandit‑propensity mechanism.

* **Parent B** – `hybrid_hybrid_hybrid_liquid_hybrid_hybrid_sheaf__m187_s1.py`  
  Provides a set‑wise Min‑Hash signature, a similarity measure and a
  diffusion‑forcing noise schedule (`alpha_bars`).

**Mathematical bridge**

The NLMS weight vector `w ∈ ℝⁿ` is interpreted as a *velocity field* that
scales the diffusion‑forcing schedule generated by Parent B:


α̂_t = α_t * s(w) ,   s(w) = 1 + mean(|w|)          (1)


where `α_t` is the original schedule value at step `t` and `s(w)` is a
scalar derived from the NLMS weights.

The signature similarity `sim ∈ [0,1]` (Parent B) is fed back into the
store dynamics of Parent A, modulating its inflow/outflow coefficients:


α_store' = α_store * (1 + λ·sim)                     (2)
β_store' = β_store * (1 - λ·sim)                     (3)


with a small coupling constant `λ`.  The same similarity also rescales
bandit propensities, biasing action selection toward more “similar”
contexts.

The three functions below demonstrate this hybrid operation; additional
helpers implement the individual pieces from the parents.  All
dependencies are limited to the Python standard library and NumPy."""

import numpy as np
import math
import random
import sys
import pathlib
import hashlib
from dataclasses import dataclass, field
from typing import Callable, Dict, List, Tuple

# ----------------------------------------------------------------------
# Data structures (adapted from Parent A)
# ----------------------------------------------------------------------
@dataclass(frozen=True)
class BanditAction:
    action_id: str
    propensity: float
    expected_reward: float
    confidence_bound: float
    algorithm: str = "hybrid"

@dataclass(frozen=True)
class BanditUpdate:
    context_id: str
    action_id: str
    reward: float
    propensity: float

@dataclass
class StoreState:
    level: float = 0.0
    alpha: float = 1.0
    beta: float = 1.0
    dt: float = 1.0
    base: float = 1.0

# ----------------------------------------------------------------------
# NLMS core (Parent A)
# ----------------------------------------------------------------------
def nlms_predict(weights: np.ndarray, x: np.ndarray) -> float:
    """Linear prediction y = w·x."""
    return float(weights @ x)


def nlms_update(
    weights: np.ndarray,
    x: np.ndarray,
    target: float,
    mu: float = 0.5,
    eps: float = 1e-9,
) -> Tuple[np.ndarray, float]:
    """Normalized LMS weight update."""
    if not (0.0 < mu < 2.0):
        raise ValueError("mu must be in the interval (0, 2)")
    y = nlms_predict(weights, x)
    error = target - y
    power = float(x @ x) + eps
    delta = mu * error * x / power
    new_weights = weights + delta
    return new_weights, error

# ----------------------------------------------------------------------
# Signature & similarity (Parent B)
# ----------------------------------------------------------------------
def _hash(seed: int, token: str) -> int:
    data = seed.to_bytes(4, "big") + token.encode("utf-8", errors="ignore")
    return int.from_bytes(hashlib.blake2b(data, digest_size=8).digest(), "big")


def signature(tokens: List[str], k: int = 128) -> List[int]:
    """Min‑Hash style signature of a token list."""
    toks = {t for t in tokens if t}
    if k <= 0:
        raise ValueError("k must be positive")
    if not toks:
        return [2**64 - 1] * k
    return [min(_hash(i, t) for t in toks) for i in range(k)]


def similarity(sig_a: List[int], sig_b: List[int]) -> float:
    """Fraction of equal components between two signatures."""
    if len(sig_a) != len(sig_b):
        raise ValueError("signatures must have equal length")
    if not sig_a:
        raise ValueError("signatures must not be empty")
    return sum(1 for a, b in zip(sig_a, sig_b) if a == b) / len(sig_a)

# ----------------------------------------------------------------------
# Diffusion‑forcing schedule (Parent B) with NLMS scaling (bridge)
# ----------------------------------------------------------------------
def scaled_noise_schedule(
    T: int,
    weights: np.ndarray,
    schedule: str = "cosine",
) -> np.ndarray:
    """
    Produce a diffusion‑forcing schedule α_t ∈ (0,1] and scale it by a
    factor derived from the NLMS weight vector (Eq. 1).

    Parameters
    ----------
    T : int
        Number of diffusion steps.
    weights : np.ndarray
        Current NLMS weight vector.
    schedule : {"cosine", "linear"}
        Base schedule type.

    Returns
    -------
    np.ndarray
        Scaled schedule of shape (T+1,).
    """
    if schedule == "cosine":
        s = 0.008
        steps = np.arange(T + 1, dtype=np.float64)
        f = np.cos(((steps / T) + s) / (1.0 + s) * np.pi / 2.0) ** 2
        alpha = f / f[0]
    elif schedule == "linear":
        beta_start = 1e-4
        beta_end = 0.02
        betas = np.linspace(beta_start, beta_end, T, dtype=np.float64)
        alpha = np.cumprod(1.0 - betas)
        alpha = np.concatenate(([1.0], alpha))
    else:
        raise ValueError(f"unknown schedule {schedule}")

    # Bridge: scaling factor from NLMS weights
    scale = 1.0 + np.mean(np.abs(weights))
    return np.clip(alpha * scale, 1e-9, 1.0)


# ----------------------------------------------------------------------
# Store dynamics (Parent A) modulated by signature similarity (bridge)
# ----------------------------------------------------------------------
def hybrid_store_update(
    state: StoreState,
    inflow: float,
    outflow: float,
    noise_factor: float,
    similarity_score: float,
    lambda_sim: float = 0.2,
) -> StoreState:
    """
    Update the store level using Eq. 2‑3 to modulate α,β with the
    signature similarity, then apply a simple Euler step with the
    provided inflow/outflow and an external noise factor.

    Returns a new StoreState (immutable‑style update).
    """
    # Modulate α and β with similarity
    new_alpha = state.alpha * (1.0 + lambda_sim * similarity_score)
    new_beta = state.beta * (1.0 - lambda_sim * similarity_score)

    # Euler integration of the store level
    dlevel = (new_alpha * inflow - new_beta * outflow) * state.dt
    # Add a stochastic term proportional to the diffusion schedule factor
    dlevel += noise_factor * random.gauss(0.0, 1.0)

    return StoreState(
        level=state.level + dlevel,
        alpha=new_alpha,
        beta=new_beta,
        dt=state.dt,
        base=state.base,
    )

# ----------------------------------------------------------------------
# Bandit action selection using similarity‑biased propensities
# ----------------------------------------------------------------------
def select_action(
    actions: List[BanditAction],
    similarity_score: float,
    temperature: float = 0.1,
) -> BanditAction:
    """
    Adjust each action's propensity by (1 + λ·sim) and draw a
    categorical sample using a softmax with temperature.
    """
    lambda_sim = 0.3
    adjusted = np.array(
        [
            a.propensity * (1.0 + lambda_sim * similarity_score)
            for a in actions
        ],
        dtype=np.float64,
    )
    # Prevent overflow
    max_adj = np.max(adjusted)
    exp_vals = np.exp((adjusted - max_adj) / temperature)
    probs = exp_vals / exp_vals.sum()
    choice_idx = np.random.choice(len(actions), p=probs)
    return actions[choice_idx]

# ----------------------------------------------------------------------
# High‑level hybrid step (demonstrates integration of all pieces)
# ----------------------------------------------------------------------
def hybrid_step(
    weights: np.ndarray,
    x: np.ndarray,
    target: float,
    store: StoreState,
    actions: List[BanditAction],
    tokens_a: List[str],
    tokens_b: List[str],
    T: int = 10,
) -> Tuple[np.ndarray, StoreState, BanditAction]:
    """
    Perform one hybrid iteration:
    1. NLMS weight update.
    2. Compute scaled diffusion schedule using the updated weights.
    3. Compute signature similarity between two token sets.
    4. Update the store with inflow/outflow derived from NLMS error.
    5. Select a bandit action biased by the similarity.

    Returns the new weight vector, new store state and chosen action.
    """
    # 1. NLMS update
    new_weights, error = nlms_update(weights, x, target)

    # 2. Scaled schedule – take the last value as a proxy noise factor
    schedule = scaled_noise_schedule(T, new_weights, schedule="cosine")
    noise_factor = schedule[-1]

    # 3. Signature similarity (bridge)
    sig_a = signature(tokens_a)
    sig_b = signature(tokens_b)
    sim = similarity(sig_a, sig_b)

    # 4. Store update – use absolute error as inflow, constant outflow
    inflow = abs(error)
    outflow = 0.5  # arbitrary constant
    new_store = hybrid_store_update(
        state=store,
        inflow=inflow,
        outflow=outflow,
        noise_factor=noise_factor,
        similarity_score=sim,
    )

    # 5. Bandit action selection
    chosen = select_action(actions, similarity_score=sim)

    return new_weights, new_store, chosen

# ----------------------------------------------------------------------
# Smoke test
# ----------------------------------------------------------------------
if __name__ == "__main__":
    # Initialise deterministic RNG for reproducibility
    random.seed(42)
    np.random.seed(42)

    # Dummy NLMS state
    dim = 5
    w = np.zeros(dim, dtype=np.float64)
    x = np.random.randn(dim)
    target = 0.3

    # Store state
    store = StoreState(level=0.0, alpha=1.0, beta=1.0, dt=0.1)

    # Bandit actions
    actions = [
        BanditAction(action_id="A", propensity=0.2, expected_reward=0.0, confidence_bound=0.1),
        BanditAction(action_id="B", propensity=0.5, expected_reward=0.0, confidence_bound=0.1),
        BanditAction(action_id="C", propensity=0.3, expected_reward=0.0, confidence_bound=0.1),
    ]

    # Token sequences for signatures
    tokens1 = ["alpha", "beta", "gamma", "delta"]
    tokens2 = ["beta", "epsilon", "zeta", "alpha"]

    # Run a single hybrid step
    w_new, store_new, act = hybrid_step(
        weights=w,
        x=x,
        target=target,
        store=store,
        actions=actions,
        tokens_a=tokens1,
        tokens_b=tokens2,
        T=20,
    )

    # Print results – just to verify execution (no external I/O required)
    print("New weights:", w_new)
    print("Store level:", store_new.level)
    print("Chosen action:", act.action_id)