# DARWIN HAMMER — match 1379, survivor 2
# gen: 5
# parent_a: hybrid_hybrid_doomsday_cale_hybrid_hybrid_endpoi_m709_s0.py (gen3)
# parent_b: hybrid_hybrid_voronoi_parti_hybrid_hybrid_hybrid_m104_s7.py (gen4)
# born: 2026-05-29T23:35:52Z

"""
Hybrid Multivector SSM Gini Engine

This module fuses the two parent algorithms:

* **Parent A** – ``hybrid_hybrid_doomsday_cale_hybrid_hybrid_endpoi_m709_s0.py`` 
  (hybrid Doomsday-SSM Gini Engine) which combines a vectorised Sakamoto 
  calendar, a linear State Space Model (SSM), and a Gini coefficient 
  calculation.
* **Parent B** – ``hybrid_hybrid_voronoi_parti_hybrid_hybrid_hybrid_m104_s7.py`` 
  (hybrid Voronoi partition multivector) which implements a geometric 
  product of multivectors using bit-mask blades.

The mathematical bridge between the two parents lies in the representation 
of the health vector in the SSM as a multivector. The SSM's health vector 
``hₜ ∈ ℝᴺ`` is reinterpreted as a multivector, where each component of ``hₜ`` 
corresponds to a blade in the multivector. The geometric product of 
multivectors is then used to evolve the multivector state ``mₜ``:

``mₜ = geometric_product(mₜ₋₁, mv_A)``

The Gini coefficient of the scores generated by the SSM is used to 
quantify the inequality of the generated scores.

"""

from __future__ import annotations

import datetime as dt
import math
import random
import sys
from pathlib import Path
from typing import Iterable, List, Tuple

import numpy as np

# ----------------------------------------------------------------------
# Parent A – vectorised Doomsday (Sakamoto) implementation
# ----------------------------------------------------------------------
def weekday_sakamoto(
    years: np.ndarray,
    months: np.ndarray,
    days: np.ndarray,
) -> np.ndarray:
    """
    Compute weekday indices for vectorised (year, month, day) arrays using
    Tomohiko Sakamoto's algorithm.  Result: 0 = Sunday … 6 = Saturday.
    """
    y = years.astype(np.int64)
    m = months.astype(np.int64)
    d = days.astype(np.int64)

    m_adj = np.where(m < 3, m + 12, m)
    y_adj = np.where(m < 3, y - 1, y)

    t = np.array([0, 3, 2, 5, 0, 3, 5, 1, 4, 6, 2, 4], dtype=np.int64)

    w = (y_adj + y_adj // 4 - y_adj // 100 + y_adj // 400 + t[m_adj - 1] + d) % 7
    return w.astype(np.int8)

def gini_coefficient(y: np.ndarray) -> float:
    """
    Compute the Gini coefficient of a 1-D array.
    """
    if y.size == 0:
        return 0.0

    y = y.flatten()
    if np.any(y < 0):
        y = np.abs(y)

    y = y / np.sum(y)
    n = len(y)

    gini = 0.0
    for i in range(n):
        gini += (2 * (i + 1) - n - 1) * y[i]
    gini /= (n * (n - 1))

    return gini

# ----------------------------------------------------------------------
# Parent B – multivector implementation
# ----------------------------------------------------------------------
def _grade(blade: int) -> int:
    """Number of set bits = grade of the blade."""
    return bin(blade).count('1')

def _blade_sign(a: int, b: int) -> int:
    """
    Sign of the geometric product of two basis blades a and b
    under a Euclidean metric (e_i^2 = +1).
    """
    sign = 1
    a_bits = bin(a)[2:][::-1]
    b_bits = bin(b)[2:][::-1]
    max_len = max(len(a_bits), len(b_bits))
    a_bits = a_bits.ljust(max_len, '0')
    b_bits = b_bits.ljust(max_len, '0')

    for i in range(max_len):
        if a_bits[i] == '1' and b_bits[i] == '1':
            sign *= -1

    return sign

def geometric_product(mv_a: dict, mv_b: dict) -> dict:
    """
    Euclidean Clifford geometric product using bit-mask blades.
    Returns a new multivector.
    """
    result = {}
    for blade_a, coeff_a in mv_a.items():
        for blade_b, coeff_b in mv_b.items():
            blade_res = blade_a ^ blade_b
            sign = _blade_sign(blade_a, blade_b)
            coeff_res = coeff_a * coeff_b * sign
            result[blade_res] = result.get(blade_res, 0.0) + coeff_res
    # prune near-zero entries
    return {b: c for b, c in result.items() if abs(c) > 1e-10}

# ----------------------------------------------------------------------
# Hybrid Multivector SSM Gini Engine
# ----------------------------------------------------------------------
class MultivectorSSM:
    def __init__(self, num_endpoints: int, num_steps: int):
        self.num_endpoints = num_endpoints
        self.num_steps = num_steps
        self.A = np.eye(num_endpoints)
        self.B = np.zeros((num_endpoints, 1))
        self.C = np.zeros((1, num_endpoints))
        self.mv_state = {0: 1.0}

    def evolve(self, x: float):
        mv_A = {i: self.A[i, i] for i in range(self.num_endpoints)}
        mv_state_new = geometric_product(self.mv_state, mv_A)
        self.mv_state = mv_state_new

        # Update health vector
        h = np.zeros(self.num_endpoints)
        for blade, coeff in self.mv_state.items():
            h[blade] = coeff

        # SSM update
        h_new = np.dot(self.A, h) + self.B * x
        y = np.dot(self.C, h_new)

        return y

    def run(self, years: np.ndarray, months: np.ndarray, days: np.ndarray):
        x = weekday_sakamoto(years, months, days)
        scores = np.zeros(self.num_steps)
        for i in range(self.num_steps):
            scores[i] = self.evolve(x[i])

        return scores

def hybrid_multivector_ssm_gini_engine(
    years: np.ndarray, months: np.ndarray, days: np.ndarray, num_endpoints: int
):
    engine = MultivectorSSM(num_endpoints, len(years))
    scores = engine.run(years, months, days)
    gini = gini_coefficient(scores)

    return gini

if __name__ == "__main__":
    np.random.seed(0)
    years = np.random.randint(2020, 2025, size=10)
    months = np.random.randint(1, 13, size=10)
    days = np.random.randint(1, 29, size=10)

    gini = hybrid_multivector_ssm_gini_engine(years, months, days, 5)
    print(gini)