from __future__ import annotations
from datetime import datetime, timezone
import math
from .validators import register, _res

def _bool(eq, ok): return _res(eq, 1.0 if ok else 0.0, 1.0, 'ge')
def _ratio(a,b): return 1.0 if b==0 else float(a)/float(b)

def _reg(eq, fn=None, name=None):
    if fn is None: return register(eq,name)
    return register(eq,name)(fn)

_reg('EQ-002', lambda chain_valid=False: _bool('EQ-002', chain_valid), 'LedgerIntegrity')
_reg('EQ-004', lambda actor_set=(): _bool('EQ-004', len(set(actor_set))<=1), 'SingleWriterDiscipline')
_reg('EQ-005', lambda violations=(): _res('EQ-005', sum(violations or []),0,'le'), 'LaneDisciplineViolation')
@_reg('EQ-006', name='ConfidenceCalibrationError')
def _(bins=(), total_samples=1): return _res('EQ-006', sum(abs(b.get('accuracy',0)-b.get('confidence',0))*b.get('count',1) for b in bins)/max(total_samples,1),0.05,'le')
_reg('EQ-007', lambda answer_counts=None,k=1: _res('EQ-007', max((answer_counts or {0:0}).values())/max(k,1),0.6,'ge'), 'SelfConsistencyConfidence')
_reg('EQ-008', lambda steel_man_evidence_cites=0,steel_man_quality=0,passes_self_consistency=False: _bool('EQ-008', steel_man_evidence_cites>=1 and steel_man_quality>=0.7 and passes_self_consistency))
_reg('EQ-009', lambda enumerated_unknowns=0,suspected_unknown_unknowns=0: _res('EQ-009', enumerated_unknowns/max(enumerated_unknowns+suspected_unknown_unknowns,1),0.75,'ge'))
_reg('EQ-010', lambda uptime_ratio=1,error_rate=0,latency_p99=0,latency_budget=1,cost_overrun_ratio=0: _res('EQ-010', 1/(1+math.exp(-5*(uptime_ratio-error_rate-(latency_p99/max(latency_budget,1))*0.1-cost_overrun_ratio))),0.5,'ge'))
_reg('EQ-011', lambda f1_new=0,f1_old=0,ece_new=1,ece_old=1,latency_p99_new=0,latency_budget=1,adv_f1_new=0,clean_f1_new=0,ram_new_mb=0,pool_budget_mb=1: _bool('EQ-011', f1_new-f1_old>=0.03 and ece_new<=ece_old and latency_p99_new<=latency_budget and adv_f1_new>=0.85 and ram_new_mb<=pool_budget_mb))
_reg('EQ-012', lambda kl_divergence=0: _res('EQ-012', kl_divergence,0.15,'le'))
_reg('EQ-013', lambda confidence_at_threshold=0,empirical_accuracy_at_threshold=0: _res('EQ-013', abs(confidence_at_threshold-empirical_accuracy_at_threshold),0.05,'le'))
_reg('EQ-014', lambda tokens=0,cost_per_token=0,evi=1: _res('EQ-014', tokens*cost_per_token/max(evi,1e-9),1.0,'le'))
_reg('EQ-016', lambda concepts_used=(),global_vocab=(): _res('EQ-016', sum(1 for c in concepts_used if c in set(global_vocab))/max(len(concepts_used),1),1.0,'ge'))
_reg('EQ-017', lambda cross_domain_imports=0,total_imports=1: _res('EQ-017', 1-cross_domain_imports/max(total_imports,1),0.95,'ge'))
_reg('EQ-018', lambda delta_concept_yamls=0,companion_rfc_ratified=False: _bool('EQ-018', delta_concept_yamls==0 or companion_rfc_ratified))
_reg('EQ-019', lambda **kw: _bool('EQ-019', all(kw.values())))
_reg('EQ-020', lambda law_functions_import_soul_field=False: _bool('EQ-020', not law_functions_import_soul_field), 'SoulLawIsolation')
@_reg('EQ-021', name='MemoryStaleness')
def _(last_verified_iso='1970-01-01T00:00:00+00:00', max_age_days=30):
    age=(datetime.now(timezone.utc)-datetime.fromisoformat(last_verified_iso.replace('Z','+00:00'))).total_seconds()/86400
    return _res('EQ-021', age, max_age_days, 'le')
_reg('EQ-022', lambda required_fields=(),provided_fields=(): _res('EQ-022', len(set(required_fields)&set(provided_fields))/max(len(required_fields),1),1.0,'ge'))
_reg('EQ-023', lambda tokens_used=0,tokens_budgeted=1: _res('EQ-023', tokens_used/max(tokens_budgeted,1),1.0,'le'))
_reg('EQ-024', lambda signature_valid=False: _bool('EQ-024', signature_valid))
_reg('EQ-025', lambda pass_rate=0,suite_threshold=0.9,adversarial_pass_rate=0,clean_pass_rate=0: _bool('EQ-025', pass_rate>=suite_threshold and adversarial_pass_rate>=0.85 and clean_pass_rate>=suite_threshold))
_reg('EQ-026', lambda injection_signature_hit=False,operator_stop_kill=False: _res('EQ-026', float(bool(injection_signature_hit or operator_stop_kill)),0,'le'))
_reg('EQ-028', lambda ledger_ops_emitted=0,disk_mutations=0: _res('EQ-028', _ratio(ledger_ops_emitted,disk_mutations),1.0,'ge'))
_reg('EQ-029', lambda f1_adversarial=0,f1_clean=0: _bool('EQ-029', f1_adversarial>=0.85 and f1_clean>=0.9))
_reg('EQ-030', lambda signature_hits_last_24h=0: _res('EQ-030', signature_hits_last_24h,2.999999,'le'))
_reg('EQ-031', lambda from_state='',to_state='',allowed_transitions=(): _bool('EQ-031', [from_state,to_state] in allowed_transitions))
_reg('EQ-032', lambda required_evidence=(),attached_evidence=(): _bool('EQ-032', set(required_evidence).issubset(set(attached_evidence))))
_reg('EQ-033', lambda **kw: _bool('EQ-033', True))
_reg('EQ-034', lambda **kw: _bool('EQ-034', True))
_reg('EQ-035', lambda steps_with_decision_trace=0,total_steps=1: _res('EQ-035', _ratio(steps_with_decision_trace,total_steps),1.0,'ge'))
@_reg('EQ-036')
def _(consent_timestamp_iso='1970-01-01T00:00:00+00:00', max_age_seconds=300):
    age=(datetime.now(timezone.utc)-datetime.fromisoformat(consent_timestamp_iso.replace('Z','+00:00'))).total_seconds(); return _res('EQ-036',age,max_age_seconds,'le')
_reg('EQ-037', lambda observed_claims=0,inferred_claims=0,not_proven_claims=0: _res('EQ-037',(observed_claims+0.3*inferred_claims)/max(observed_claims+inferred_claims+not_proven_claims,1),0.8,'ge'))
_reg('EQ-038', lambda **kw: _bool('EQ-038', True))
_reg('EQ-039', lambda observed_ratio_now=0,observed_ratio_baseline=0: _res('EQ-039', observed_ratio_now-observed_ratio_baseline,-0.1,'ge'))
_reg('EQ-040', lambda confidence=0,evidence_strength=0,case_relevance=0,cost=0,dismissed_pattern_match=0: _res('EQ-040', confidence*evidence_strength*case_relevance-cost*0.1-dismissed_pattern_match,0,'ge'))
_reg('EQ-041', lambda dismissal_carries_cited_disproof=False,falsification_criteria_met=False: _bool('EQ-041', dismissal_carries_cited_disproof and falsification_criteria_met))
_reg('EQ-042', lambda **kw: _bool('EQ-042', True))
_reg('EQ-043', lambda source_independence_a=0,source_independence_b=0,structural_incompatibility=0: _res('EQ-043', min(source_independence_a,source_independence_b,structural_incompatibility),0.7,'ge'))
_reg('EQ-044', lambda deterministic_contradictions=0,slm_inferential_contradictions=0: _res('EQ-044', _ratio(deterministic_contradictions,deterministic_contradictions+slm_inferential_contradictions),0.7,'ge'))
_reg('EQ-045', lambda claims_outside_allowed_sources=0: _res('EQ-045', claims_outside_allowed_sources,0,'le'))
_reg('EQ-046', lambda cited_claims=0,total_claims=0: _res('EQ-046', _ratio(cited_claims,total_claims),1.0,'ge'))
_reg('EQ-047', lambda word_count=0,counter_evidence_cites=0,passes_sc_vote=False: _bool('EQ-047', word_count>=100 and counter_evidence_cites>=1 and passes_sc_vote))
_reg('EQ-048', lambda outbound_contains_banned_identifier=False: _bool('EQ-048', not outbound_contains_banned_identifier))
_reg('EQ-049', lambda **kw: _bool('EQ-049', True))
_reg('EQ-050', lambda ledger_revenue=0,platform_payout=0,processor_fees=0: _res('EQ-050', abs(ledger_revenue-platform_payout-processor_fees),0.01,'le'))
_reg('EQ-051', lambda refund_phrase_score=0,dispute_signature=0,fan_history_anomaly=0,payment_window_anomaly=0: _res('EQ-051', refund_phrase_score+dispute_signature+fan_history_anomaly+payment_window_anomaly,1.0,'le'))
_reg('EQ-052', lambda asset_scope_within_consent=False,consent_active=False,consent_not_expired=False: _bool('EQ-052', asset_scope_within_consent and consent_active and consent_not_expired))
_reg('EQ-053', lambda cross_enclave_reads_with_broker=0,total_cross_enclave_reads=0: _res('EQ-053', _ratio(cross_enclave_reads_with_broker,total_cross_enclave_reads),1.0,'ge'), 'EnclaveIntegrity')
_reg('EQ-054', lambda epsilon_used=0,epsilon_total_budget=1: _res('EQ-054', epsilon_used/max(epsilon_total_budget,1e-9),1.0,'le'))
_reg('EQ-055', lambda **kw: _bool('EQ-055', True))
_reg('EQ-056', lambda name_match=0,dob_match=0,address_match=0,source_independence=0,public_record_corroboration=0: _res('EQ-056', min(name_match,dob_match,address_match,source_independence,public_record_corroboration),0.8,'ge'))
_reg('EQ-057', lambda **kw: _bool('EQ-057', True))
_reg('EQ-058', lambda files_with_current_sha256=0,total_files=1: _res('EQ-058', _ratio(files_with_current_sha256,total_files),0.95,'ge'))
_reg('EQ-059', lambda influence_score=0,uncertainty_reduction=0,case_relevance=0,opsec_self_risk=0: _res('EQ-059', influence_score*uncertainty_reduction*case_relevance-opsec_self_risk,0,'ge'))
_reg('EQ-060', lambda actor_ppr_weights=(),downstream_dependencies=(),all_have_legal_basis=False: _res('EQ-060', 0.0 if not all_have_legal_basis else sum(actor_ppr_weights)*sum(downstream_dependencies),0.1,'ge'))
_reg('EQ-061', lambda signal_strengths=(): _res('EQ-061', sum(signal_strengths)/max(len(signal_strengths),1),0.8,'le'))
_reg('EQ-062', lambda prior_before_cycle_1=0,posterior_after_cycle_3=0: _res('EQ-062', posterior_after_cycle_3-prior_before_cycle_1,0.1,'ge'))
_reg('EQ-063', lambda **kw: _bool('EQ-063', True))
_reg('EQ-064', lambda claims_per_kb_text=0,observed_ratio=1: _res('EQ-064', 1.0 if claims_per_kb_text>5 and observed_ratio<0.5 else 0.0,0,'le'))
_reg('EQ-065', lambda evidence_score=0,provenance_score=0,countersearch_score=0,audit_score=0: _res('EQ-065', evidence_score*provenance_score*countersearch_score*audit_score,0.1,'ge'), 'TruthInfra')
_reg('EQ-066', lambda expected_value=0,evidence_strength=0,option_value=0,risk=0,uncertainty=0,audit_debt=0: _res('EQ-066', expected_value*evidence_strength+option_value-risk-uncertainty-audit_debt,0,'ge'))
_reg('EQ-067', lambda lawful_vector=0,evidence_basis=0,human_approval=0,collateral_risk=0: _res('EQ-067', lawful_vector*evidence_basis*human_approval-collateral_risk,0,'ge'))
_reg('EQ-068', lambda hypothesis_update=0,contradiction_reduction=0,decision_improvement=0: _res('EQ-068', hypothesis_update+contradiction_reduction+decision_improvement,0,'ge'))
_reg('EQ-069', lambda claims_emitted=0,claims_with_evidence=0: _res('EQ-069', max(0,claims_emitted-claims_with_evidence),0,'le'), 'Slop')
_reg('EQ-072', lambda expected_value=0,risk=0,uncertainty=0,audit_debt=0,parent_fitness=0: _res('EQ-072', expected_value-risk-uncertainty-audit_debt, parent_fitness, 'ge'))
_reg('EQ-073', lambda sketch_estimate=0,true_value=1: _res('EQ-073', abs(sketch_estimate-true_value)/max(abs(true_value),1e-9),0.05,'le'))
_reg('EQ-074', lambda same_source_count=0,cluster_size=1: _res('EQ-074', _ratio(same_source_count,cluster_size),0.8,'ge'))
_reg('EQ-075', lambda abstained_calls=0,total_calls=1: _res('EQ-075', _ratio(abstained_calls,total_calls),0.4,'le'))
_reg('EQ-076', lambda **kw: _bool('EQ-076', True))
_reg('EQ-077', lambda **kw: _bool('EQ-077', True))
_reg('EQ-078', lambda source_score=0,corroboration_score=0,provenance_score=0,timestamp_score=0: _res('EQ-078', 1/(1+math.exp(-(source_score+corroboration_score+provenance_score+timestamp_score))),0.5,'ge'))
_reg('EQ-079', lambda r_evidence=0,corroboration=0,source_independence=0,temporal_fit=0,incentive_fit=0,contradiction_weight=0,provenance_gap=0,synthetic_risk=0: _res('EQ-079', r_evidence*corroboration*source_independence*temporal_fit*incentive_fit-contradiction_weight-provenance_gap-synthetic_risk,0,'ge'))
_reg('EQ-080', lambda unresolved_weighted_count=0: _res('EQ-080', math.exp(-0.5*unresolved_weighted_count),0.5,'ge'))
_reg('EQ-081', lambda action_utilities=None: _res('EQ-081', max(min(v) for v in (action_utilities or {'noop':[0]}).values()),0,'ge'))
_reg('EQ-082', lambda match_confidence=0,case_basis_strength=0,subject_class_allowed=False: _res('EQ-082', 0 if not subject_class_allowed else match_confidence*case_basis_strength,0.7,'ge'))
_reg('EQ-083', lambda subject_class_in_allowed=False,source_tier_permitted=False,case_id_present=False: _bool('EQ-083', subject_class_in_allowed and source_tier_permitted and case_id_present))
_reg('EQ-084', lambda resolution_kind='',cited_evidence_count=0,falsification_criteria_met=False: _bool('EQ-084', resolution_kind=='execute' or (resolution_kind=='disprove_with_evidence' and cited_evidence_count>0 and falsification_criteria_met)))
_reg('EQ-085', lambda refusal_matches_vibes_pattern=False,cite_count=0,refusal_kind='': _res('EQ-085', 0.0 if refusal_kind=='SAFETY_GATE' else float(refusal_matches_vibes_pattern and cite_count==0),0,'le'), 'RefusalsByVibes')
_reg('EQ-086', lambda directives_disproved_delta=0: _res('EQ-086', directives_disproved_delta,0.2,'le'))
_reg('EQ-088', lambda closed_wos=0,total_wos=1: _res('EQ-088', _ratio(closed_wos,total_wos),0.8,'ge'))
_reg('EQ-090', lambda delta_signature_observations=0,delta_time_hours=1: _res('EQ-090', delta_signature_observations/max(delta_time_hours,1e-9),2.0,'le'))
@_reg('EQ-091')
def _(drift_scores=(),call_volume_shares=()):
    if len(drift_scores)!=len(call_volume_shares): raise ValueError('mismatched lengths')
    return _res('EQ-091', sum(d*s for d,s in zip(drift_scores,call_volume_shares)),0.05,'le')
_reg('EQ-092', lambda fork_attempts_detected=0,total_appends=1: _res('EQ-092', 1-fork_attempts_detected/max(total_appends,1),1.0,'ge'))
_reg('EQ-093', lambda **kw: _bool('EQ-093', all(v is True or (isinstance(v,(int,float)) and v>=0.95) or k=='packet_strength' and v>=0.8 for k,v in kw.items())), 'CaseShipReadiness')
_reg('EQ-094', lambda **kw: _bool('EQ-094', all(v for k,v in kw.items() if k!='quarantine_active') and not kw.get('quarantine_active', False)), 'SystemHealth')
_reg('EQ-095', lambda **kw: _bool('EQ-095', all(kw.values())))
_reg('EQ-096', lambda executed_and_ledgered=False,disproved_with_evidence=False,disproved_cited_count=0,disproved_falsification_met=False: _bool('EQ-096', executed_and_ledgered or (disproved_with_evidence and disproved_cited_count>0 and disproved_falsification_met)))
_reg('EQ-097', lambda unsupported_claims=0,refusals_without_cite=0,unknown_displayed_as_ok=0: _res('EQ-097', unsupported_claims+refusals_without_cite+unknown_displayed_as_ok,0,'le'))
_reg('EQ-098', lambda failed_without_ledger_op=0: _res('EQ-098', failed_without_ledger_op,0,'le'))
_reg('EQ-099', lambda unknown_displayed_as_ok_panels=0: _res('EQ-099', unknown_displayed_as_ok_panels,0,'le'))
_reg('EQ-100', lambda vibes_refusal_count=0: _res('EQ-100', vibes_refusal_count,0,'le'), 'CatchAllMoralismDetector')
