# DARWIN HAMMER — match 5083, survivor 3
# gen: 6
# parent_a: physarum_network.py (gen0)
# parent_b: hybrid_hybrid_hybrid_fold_c_state_space_duality_m407_s1.py (gen5)
# born: 2026-05-29T23:59:41Z

"""Hybrid Physarum‑State‑Space Algorithm
This module fuses the core topologies of two parent algorithms:

* **physarum_network.py** – provides a flux computation based on edge conductance,
  length and pressure difference, and an update rule that grows conductance with
  |flux| (the “Physarum” adaptation rule).

* **hybrid_hybrid_hybrid_fold_c_state_space_duality_m407_s1.py** – defines a
  state‑space system whose transition matrix **A** is adapted by a pheromone‑
  infotaxis mechanism driven by a multi‑armed bandit policy.

**Mathematical bridge**  
The conductance matrix **C** of the Physarum network is interpreted as the
state‑transition matrix **A** of the state‑space model.  Fluxes generated by the
Physarum dynamics act as external inputs to the state update, while the
pheromone‑infotaxis updates modify the same matrix **A** (i.e. the conductances)
according to bandit‑derived “pheromone” levels.  Thus a single matrix
simultaneously obeys the Physarum growth law and the pheromone‑driven adaptation
law, yielding a unified hybrid dynamics.

The implementation below provides three high‑level functions that demonstrate the
hybrid operation:
1. `compute_fluxes` – Physarum fluxes on all edges.
2. `update_transition_matrix` – pheromone‑infotaxis adaptation of the shared
   matrix **A**.
3. `hybrid_step` – a full time‑step that updates conductances, the transition
   matrix, and the system state.
"""

import math
import random
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
import numpy as np

# ----------------------------------------------------------------------
# Bandit‑related data structures (from parent B)
# ----------------------------------------------------------------------
@dataclass(frozen=True)
class BanditAction:
    action_id: str
    propensity: float
    expected_reward: float
    confidence_bound: float
    algorithm: str

@dataclass(frozen=True)
class BanditUpdate:
    context_id: str
    action_id: str
    reward: float
    propensity: float

# Global policy: maps action_id -> [cumulative_reward, count]
_POLICY: dict = defaultdict(lambda: [0.0, 0.0])

def reset_policy() -> None:
    """Reset the bandit policy."""
    _POLICY.clear()

def _reward(action: str) -> float:
    """Average reward for an action."""
    total, n = _POLICY[action]
    return total / n if n else 0.0

def _count(action: str) -> float:
    """Number of times an action has been selected."""
    return _POLICY[action][1]

def _hybrid_store_factor(action_id: str, count: float, log_count_ratio: float) -> float:
    """Hybrid store factor used for pheromone scaling."""
    return log_count_ratio * count

def _pheromone_infotaxis(pheromone: float, log_count_ratio: float) -> float:
    """Pheromone infotaxis term."""
    return pheromone * log_count_ratio if pheromone != 0 and log_count_ratio != 0 else 0.0

# ----------------------------------------------------------------------
# Physarum‑related primitives (from parent A)
# ----------------------------------------------------------------------
def flux(conductance: float,
         edge_length: float,
         pressure_a: float,
         pressure_b: float,
         eps: float = 1e-12) -> float:
    """Compute flux on a single edge."""
    if edge_length <= 0:
        raise ValueError('edge_length must be positive')
    return conductance / max(edge_length, eps) * (pressure_a - pressure_b)

def update_conductance(conductance: float,
                       q: float,
                       dt: float = 1.0,
                       gain: float = 1.0,
                       decay: float = 0.05) -> float:
    """Physarum conductance adaptation."""
    if dt < 0 or decay < 0:
        raise ValueError('dt and decay must be non‑negative')
    return max(0.0, conductance + dt * (gain * abs(q) - decay * conductance))

# ----------------------------------------------------------------------
# Hybrid operations
# ----------------------------------------------------------------------
def compute_fluxes(conductance_mat: np.ndarray,
                   edge_len_mat: np.ndarray,
                   pressure_vec: np.ndarray) -> np.ndarray:
    """
    Compute the flux on every directed edge (i → j) using the Physarum rule.
    Returns a matrix Q where Q[i, j] = flux from i to j (zero if no edge).
    """
    n = conductance_mat.shape[0]
    flux_mat = np.zeros_like(conductance_mat, dtype=float)
    for i in range(n):
        for j in range(n):
            g = conductance_mat[i, j]
            if g > 0:
                l = edge_len_mat[i, j]
                q = flux(g, l, pressure_vec[i], pressure_vec[j])
                flux_mat[i, j] = q
    return flux_mat

def update_transition_matrix(A: np.ndarray,
                             pheromone_mat: np.ndarray,
                             log_count_ratio_mat: np.ndarray,
                             alpha: float = 0.1) -> np.ndarray:
    """
    Apply pheromone‑infotaxis to the shared transition / conductance matrix.
    The update is element‑wise:
        A_new = A + α * (pheromone ⊙ log_count_ratio)
    where ⊙ denotes element‑wise multiplication.
    """
    infotaxis = _pheromone_infotaxis(pheromone_mat, log_count_ratio_mat)
    return A + alpha * infotaxis

def hybrid_step(state: np.ndarray,
                A: np.ndarray,
                conductance_mat: np.ndarray,
                edge_len_mat: np.ndarray,
                pressure_vec: np.ndarray,
                pheromone_mat: np.ndarray,
                log_count_ratio_mat: np.ndarray,
                dt: float = 1.0) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Perform one hybrid iteration:
      1. Compute Physarum fluxes Q.
      2. Update conductances using Q (Physarum growth rule).
      3. Update the shared matrix A via pheromone infotaxis.
      4. Propagate the state: x_{t+1} = A @ x_t + Σ_i Q[:, i] (total inflow).

    Returns the tuple (new_state, new_A, new_conductance_mat).
    """
    # 1. Fluxes
    Q = compute_fluxes(conductance_mat, edge_len_mat, pressure_vec)

    # 2. Conductance update (edge‑wise)
    new_conductance = np.copy(conductance_mat)
    n = conductance_mat.shape[0]
    for i in range(n):
        for j in range(n):
            g = conductance_mat[i, j]
            if g > 0:
                new_conductance[i, j] = update_conductance(g, Q[i, j], dt=dt)

    # 3. Transition matrix update (pheromone side)
    new_A = update_transition_matrix(A, pheromone_mat, log_count_ratio_mat)

    # 4. State propagation
    # Input term: net inflow to each node = Σ_j Q[j, i] - Σ_j Q[i, j]
    inflow = Q.sum(axis=0) - Q.sum(axis=1)
    new_state = new_A @ state + inflow

    return new_state, new_A, new_conductance

# ----------------------------------------------------------------------
# Simple bandit utilities (used to generate pheromone and log‑count matrices)
# ----------------------------------------------------------------------
def select_action(actions: list[BanditAction]) -> BanditAction:
    """ε‑greedy selection based on expected_reward."""
    eps = 0.1
    if random.random() < eps:
        return random.choice(actions)
    # pick max expected reward
    return max(actions, key=lambda a: a.expected_reward)

def record_bandit_update(update: BanditUpdate) -> None:
    """Update the global policy with a new observation."""
    total, count = _POLICY[update.action_id]
    _POLICY[update.action_id][0] = total + update.reward
    _POLICY[update.action_id][1] = count + 1

def build_pheromone_and_logratio(n: int) -> tuple[np.ndarray, np.ndarray]:
    """
    Construct synthetic pheromone and log‑count‑ratio matrices from the bandit
    policy.  For demonstration we map action counts onto a square matrix.
    """
    pheromone = np.zeros((n, n), dtype=float)
    log_ratio = np.zeros((n, n), dtype=float)
    actions = list(_POLICY.keys())
    for idx, act in enumerate(actions):
        i = idx % n
        j = (idx // n) % n
        cnt = _count(act)
        pheromone[i, j] = cnt  # raw count as pheromone strength
        # avoid log(0); add 1
        log_ratio[i, j] = math.log(cnt + 1) - math.log(1)  # = log(cnt+1)
    return pheromone, log_ratio

# ----------------------------------------------------------------------
# Smoke test
# ----------------------------------------------------------------------
if __name__ == "__main__":
    # Simple 3‑node network
    n_nodes = 3
    # Initial conductance matrix (directed edges)
    C = np.array([[0.0, 1.0, 0.5],
                  [0.2, 0.0, 1.5],
                  [1.0, 0.3, 0.0]])
    # Edge lengths (positive)
    L = np.array([[1.0, 1.2, 0.8],
                  [1.1, 1.0, 0.9],
                  [0.7, 1.3, 1.0]])
    # Pressures at nodes (arbitrary)
    p = np.array([1.0, 0.5, 0.2])

    # Initial state vector
    x = np.array([0.0, 0.0, 0.0])

    # Initialise a dummy bandit policy with two actions
    reset_policy()
    _POLICY["a1"] = [0.0, 0]   # total reward, count
    _POLICY["a2"] = [0.0, 0]

    # Simulate a few steps, recording synthetic rewards
    for step in range(5):
        # Simulate a bandit reward (random)
        reward = random.random()
        action = random.choice(list(_POLICY.keys()))
        record_bandit_update(BanditUpdate(context_id="test",
                                          action_id=action,
                                          reward=reward,
                                          propensity=1.0))

        # Build pheromone and log‑ratio matrices from current policy
        pheromone_mat, log_ratio_mat = build_pheromone_and_logratio(n_nodes)

        # Hybrid iteration
        x, A, C = hybrid_step(state=x,
                              A=C,                     # A shares the conductance matrix
                              conductance_mat=C,
                              edge_len_mat=L,
                              pressure_vec=p,
                              pheromone_mat=pheromone_mat,
                              log_count_ratio_mat=log_ratio_mat,
                              dt=0.5)

        print(f"Step {step+1}")
        print("State:", x)
        print("Transition/Conductance matrix A:\n", A)
        print("-" * 40)