# DARWIN HAMMER — match 4629, survivor 3
# gen: 6
# parent_a: hybrid_hybrid_hybrid_percyp_hybrid_hybrid_hybrid_m576_s2.py (gen5)
# parent_b: hybrid_workshare_allocator_doomsday_calendar_m14_s2.py (gen1)
# born: 2026-05-29T23:57:04Z

"""Hybrid Morphology‑Calendar Store Dynamics
================================================

Parents
-------
* **Parent A** – ``hybrid_hybrid_hybrid_percyp_hybrid_hybrid_hybrid_m576_s2.py``  
  Provides geometric morphology, sphericity/flatness coefficients, and a
  stylometric interaction factor ϕ.

* **Parent B** – ``hybrid_workshare_allocator_doomsday_calendar_m14_s2.py``  
  Provides a weekday‑dependent weight vector `W(dow)` that maps a token pool
  onto a fixed set of groups.

Mathematical Bridge
-------------------
The bridge fuses the two topologies by using the weekday weight vector as a
linear operator on the inflow/outflow token vectors before they are fed into
the store dynamics of Parent A.  Concretely, for a store value `S` we compute


α = 1 + sphericity          # geometry‑driven inflow gain
β = 1 + flatness            # geometry‑driven outflow loss
ϕ ∈ [0.5, 1.5]              # stylometric interaction factor
W(d) ∈ ℝⁿ, Σ_i W_i(d) = 1   # weekday weight vector (n = number of groups)

I = Σ_i W_i(d)·inflow_i      # weighted total inflow
O = Σ_i W_i(d)·outflow_i     # weighted total outflow

Δ = α·(ϕ·I) – β·((2‑ϕ)·O)
S_new = max(0, S + dt·Δ)


Thus the physical shape (α,β) and linguistic context (ϕ) modulate a
calendar‑driven allocation (`W(d)`) that finally updates the store.  The
resulting system reacts simultaneously to morphology, text, and the day of
the week.

The module below implements this hybrid model and exposes three public
functions that demonstrate the combined operation.
"""

import hashlib
import math
import random
import sys
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Sequence, Tuple

import numpy as np

# ----------------------------------------------------------------------
# Constants (from Parent B)
# ----------------------------------------------------------------------
GROUPS: Tuple[str, ...] = ("codex", "groq", "cohere", "local_models")
_AMPLITUDE = 0.2  # sinusoidal amplitude for weekday weight generation


# ----------------------------------------------------------------------
# Parent A – Geometry & Stylometry primitives
# ----------------------------------------------------------------------
@dataclass(frozen=True)
class Morphology:
    """Simple rectangular‑prism morphology."""
    length: float
    width: float
    height: float
    mass: float = 1.0  # unused but kept for compatibility


def _sphericity(m: Morphology) -> float:
    """Return a dimension‑less sphericity in [0, 1].

    For a rectangular prism we approximate sphericity as the ratio of the
    smallest to the largest edge length.
    """
    edges = np.array([m.length, m.width, m.height], dtype=float)
    if edges.max() == 0:
        return 0.0
    return edges.min() / edges.max()


def _flatness(m: Morphology) -> float:
    """Flatness is defined as 1 − sphericity."""
    return 1.0 - _sphericity(m)


def _alpha_beta(m: Morphology) -> Tuple[float, float]:
    """Compute geometry‑driven coefficients α and β."""
    sph = _sphericity(m)
    flt = _flatness(m)
    alpha = 1.0 + sph
    beta = 1.0 + flt
    return alpha, beta


_FUNCTION_WORDS = {
    "the", "and", "of", "to", "a", "in", "that", "is", "it", "for",
    "on", "with", "as", "was", "but", "be", "at", "by", "he", "she"
}


def _stylometric_factor(text: str) -> float:
    """
    Compute a stylometric interaction factor ϕ ∈ [0.5, 1.5].

    The factor is linearly mapped from the proportion of function words in the
    supplied text: a higher proportion yields a larger ϕ.
    """
    words = [w.strip(".,!?:;\"'").lower() for w in text.split()]
    if not words:
        return 1.0
    func_cnt = sum(1 for w in words if w in _FUNCTION_WORDS)
    ratio = func_cnt / len(words)          # ∈ [0, 1]
    phi = 0.5 + ratio * 1.0                # map to [0.5, 1.5]
    return max(0.5, min(1.5, phi))


# ----------------------------------------------------------------------
# Parent B – Calendar weight vector
# ----------------------------------------------------------------------
def _weekday_index(year: int, month: int, day: int) -> int:
    """
    Return weekday index where 0 = Sunday … 6 = Saturday.
    """
    # datetime.weekday(): Monday=0 … Sunday=6 → shift
    return (datetime(year, month, day).weekday() + 1) % 7


def weekday_weight_vector(groups: Sequence[str], dow: int) -> np.ndarray:
    """
    Produce a normalized weight vector for *groups* based on the weekday ``dow``.
    The vector is generated by rotating a sinusoidal pattern; the rotation angle
    is proportional to ``dow`` (0‑6).  The result is stochastic (sums to 1).

    Mathematically:
        w_i(d) = [1 + α·sin(θ_i + φ(d))] / Σ_j[1 + α·sin(θ_j + φ(d))]
    where
        θ_i = 2π·i / N   (N = number of groups)
        φ(d) = 2π·d / 7   (weekday phase)
        α    = 0.2        (amplitude)
    """
    n = len(groups)
    theta = 2.0 * math.pi * np.arange(n) / n
    phi = 2.0 * math.pi * dow / 7.0
    raw = 1.0 + _AMPLITUDE * np.sin(theta + phi)
    weights = raw / raw.sum()
    return weights


# ----------------------------------------------------------------------
# Hybrid core functions
# ----------------------------------------------------------------------
def compute_geometry_coeffs(morph: Morphology) -> Tuple[float, float]:
    """
    Public wrapper returning (α, β) for a given morphology.
    """
    return _alpha_beta(morph)


def allocate_tokens_by_weekday(
    total_tokens: float,
    dow: int,
    groups: Sequence[str] = GROUPS,
) -> np.ndarray:
    """
    Distribute *total_tokens* across *groups* using the weekday weight vector.
    Returns an array of shape (len(groups),) whose sum equals *total_tokens*.
    """
    w = weekday_weight_vector(groups, dow)
    return total_tokens * w


def hybrid_store_update(
    store: float,
    inflow_vec: np.ndarray,
    outflow_vec: np.ndarray,
    morph: Morphology,
    dow: int,
    text: str,
    dt: float = 1.0,
) -> float:
    """
    Perform one hybrid update step.

    Parameters
    ----------
    store: current store value (non‑negative scalar)
    inflow_vec, outflow_vec: raw token vectors of shape (n_groups,)
    morph: morphology instance providing α, β
    dow: weekday index (0 = Sunday … 6 = Saturday)
    text: arbitrary string used for stylometric factor ϕ
    dt: time step multiplier

    Returns
    -------
    Updated store value (guaranteed non‑negative).
    """
    if inflow_vec.shape != outflow_vec.shape:
        raise ValueError("inflow and outflow vectors must have the same shape")

    # Geometry coefficients
    alpha, beta = compute_geometry_coeffs(morph)

    # Stylometric interaction factor
    phi = _stylometric_factor(text)

    # Weekday‑dependent weighting
    w = weekday_weight_vector(GROUPS, dow)
    weighted_in = np.dot(w, inflow_vec)   # scalar total inflow after weighting
    weighted_out = np.dot(w, outflow_vec) # scalar total outflow after weighting

    # Hybrid differential equation
    delta = alpha * (phi * weighted_in) - beta * ((2.0 - phi) * weighted_out)

    new_store = max(0.0, store + dt * delta)
    return new_store


# ----------------------------------------------------------------------
# Demonstration utilities (three public functions)
# ----------------------------------------------------------------------
def simulate_hybrid_process(
    steps: int,
    init_store: float,
    morph: Morphology,
    base_date: Tuple[int, int, int],
    text_supplier,
    rng: random.Random = random,
) -> List[float]:
    """
    Run a simple simulation of the hybrid store for *steps* iterations.

    *text_supplier* is a callable returning a string for each step (e.g. a
    random sentence generator).  The date advances one day per step.
    Returns the list of store values (including the initial one).
    """
    store_history = [init_store]
    year, month, day = base_date
    for step in range(steps):
        dow = _weekday_index(year, month, day)

        # Random token pools for demonstration
        inflow = rng.random() * 100.0
        outflow = rng.random() * 80.0
        inflow_vec = allocate_tokens_by_weekday(inflow, dow)
        outflow_vec = allocate_tokens_by_weekday(outflow, dow)

        text = text_supplier()
        new_store = hybrid_store_update(
            store=store_history[-1],
            inflow_vec=inflow_vec,
            outflow_vec=outflow_vec,
            morph=morph,
            dow=dow,
            text=text,
            dt=1.0,
        )
        store_history.append(new_store)

        # advance date by one day (simple overflow handling)
        try:
            dt_obj = datetime(year, month, day) + dt.timedelta(days=1)
        except Exception:
            dt_obj = datetime(year, month, day)  # fallback, should not happen
        year, month, day = dt_obj.year, dt_obj.month, dt_obj.day

    return store_history


def random_text_generator(rng: random.Random = random) -> str:
    """
    Very small mock‑up generator that returns a pseudo‑sentence composed of
    function and content words.  Used for the demonstration simulation.
    """
    func = list(_FUNCTION_WORDS)
    content = ["planet", "quantum", "algorithm", "neuron", "gravity", "matrix"]
    words = []
    for _ in range(rng.randint(5, 12)):
        if rng.random() < 0.4:
            words.append(rng.choice(func))
        else:
            words.append(rng.choice(content))
    return " ".join(words).capitalize() + "."


def example_usage() -> None:
    """
    Run a short example that prints the store trajectory for 10 days.
    """
    morph = Morphology(length=2.3, width=1.7, height=0.9)
    trajectory = simulate_hybrid_process(
        steps=10,
        init_store=50.0,
        morph=morph,
        base_date=(2026, 5, 29),
        text_supplier=lambda: random_text_generator(),
    )
    for day, val in enumerate(trajectory):
        print(f"Day {day:2d}: store = {val:.3f}")


# ----------------------------------------------------------------------
# Smoke test
# ----------------------------------------------------------------------
if __name__ == "__main__":
    example_usage()