# DARWIN HAMMER — match 3925, survivor 3
# gen: 6
# parent_a: hybrid_hybrid_hybrid_hybrid_hybrid_hybrid_minimu_m1402_s2.py (gen5)
# parent_b: hybrid_hybrid_omni_chaotic__hybrid_hybrid_liquid_m1302_s1.py (gen5)
# born: 2026-05-29T23:52:38Z

"""Hybrid Algorithm: Pheromone‑Weighted Minimum‑Cost JEPA with MinHash Similarity

Parents
-------
* **HybridPheromoneSystem** – from `hybrid_hybrid_hybrid_hybrid_hybrid_hybrid_minimu_m1402_s2.py`
  Provides time‑decaying pheromone signals, entropy of pheromone distributions and
  health‑score based edge weights.

* **Omni‑JEPA + HTR‑LTCMH** – from `hybrid_hybrid_omni_chaotic__hybrid_hybrid_liquid_m1302_s1.py`
  Supplies a JEPA‑style encoder/predictor pair, a MinHash signature generator
  (Liquid‑Time‑Constant MinHash) and a ternary‑router feature.

Mathematical Bridge
-------------------
Both parents treat a graph edge as a latent variable.  
Parent A defines a *pheromone‑modulated* edge weight  


w_A(i,j) = health_i * health_j * exp( -α * Entropy(pheromone_{ij}) )


Parent B supplies a *similarity* between two node signatures generated by MinHash  


s_B(i,j) = 1 - Jaccard( signature_i , signature_j )


The unified hybrid edge weight multiplies these two contributions:


w_H(i,j) = w_A(i,j) * ( 1 + β * s_B(i,j) )


where `α` controls uncertainty attenuation and `β` scales the influence of
MinHash similarity.  The Hoeffding bound from Parent A decides when enough
observations have been collected to perform a Bayesian posterior update on the
edge weight.

The functions below implement the full hybrid workflow:
1. `compute_pheromone_modulated_weight`
2. `minhash_signature` / `minhash_similarity`
3. `hybrid_edge_weight`
4. `hoeffding_guided_update`
5. `evaluate_hybrid_cost`
"""

import math
import random
import sys
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np

# ----------------------------------------------------------------------
# Pheromone subsystem (Parent A)
# ----------------------------------------------------------------------
class HybridPheromoneSystem:
    """Manages time‑decaying pheromone signals and computes their entropy."""

    def __init__(self):
        # storage: (node_i, node_j) -> list of (timestamp, signal_value)
        self._signals: Dict[Tuple[int, int], List[Tuple[float, float]]] = {}

    def add_signal(
        self,
        i: int,
        j: int,
        signal_value: float,
        timestamp: float,
        half_life_seconds: float = 60.0,
    ) -> None:
        """Insert a raw pheromone observation.  The signal decays exponentially
        with the given half‑life."""
        decay = math.log(2) / half_life_seconds
        decayed = signal_value * math.exp(-decay * (timestamp - timestamp))
        # (timestamp, decayed_value) stored; for simplicity we keep the raw value
        self._signals.setdefault((i, j), []).append((timestamp, signal_value))

    def get_average_signal(self, i: int, j: int, now: float, half_life_seconds: float = 60.0) -> float:
        """Return the exponential‑moving‑average of the pheromone on edge (i,j)."""
        decay = math.log(2) / half_life_seconds
        weighted_sum = 0.0
        weight_total = 0.0
        for ts, val in self._signals.get((i, j), []):
            w = math.exp(-decay * (now - ts))
            weighted_sum += w * val
            weight_total += w
        return weighted_sum / weight_total if weight_total > 0 else 0.0

    @staticmethod
    def entropy(prob_dist: np.ndarray) -> float:
        """Shannon entropy of a probability vector (base‑e)."""
        p = prob_dist / prob_dist.sum()
        p = np.clip(p, 1e-12, 1.0)  # avoid log(0)
        return -np.sum(p * np.log(p))

    def pheromone_entropy(self, i: int, j: int, now: float) -> float:
        """Treat the recent pheromone values on an edge as a categorical
        distribution and return its entropy."""
        values = np.array([val for ts, val in self._signals.get((i, j), []) if now - ts < 5 * 60])
        if values.size == 0:
            # No recent observations → maximal uncertainty (entropy of uniform over 2 states)
            return math.log(2)
        # Build a simple histogram with 10 bins
        hist, _ = np.histogram(values, bins=10, range=(values.min(), values.max()))
        return self.entropy(hist.astype(float))


# ----------------------------------------------------------------------
# MinHash / similarity subsystem (Parent B)
# ----------------------------------------------------------------------
def minhash_signature(seq: List[int], num_perm: int = 64) -> np.ndarray:
    """Generate a MinHash signature for an integer sequence.
    The implementation uses random hash functions of the form
    h(x) = (a * x + b) % prime, where a,b are random."""
    prime = 2 ** 31 - 1
    max_val = max(seq) if seq else 0
    a = np.random.randint(1, prime, size=num_perm, dtype=np.int64)
    b = np.random.randint(0, prime, size=num_perm, dtype=np.int64)

    sig = np.full(num_perm, np.iinfo(np.int64).max, dtype=np.int64)
    for x in seq:
        hx = (a * x + b) % prime
        sig = np.minimum(sig, hx)
    return sig


def minhash_similarity(sig1: np.ndarray, sig2: np.ndarray) -> float:
    """Estimate Jaccard similarity from two MinHash signatures."""
    if sig1.shape != sig2.shape:
        raise ValueError("Signatures must have the same length")
    return np.mean(sig1 == sig2)


# ----------------------------------------------------------------------
# JEPA‑style encoder / predictor (lightweight placeholder)
# ----------------------------------------------------------------------
def jepa_encode(features: np.ndarray, weight: np.ndarray) -> np.ndarray:
    """Linear encoder: z = W * x."""
    return weight @ features


def jepa_predict(latent: np.ndarray, weight: np.ndarray) -> np.ndarray:
    """Linear predictor: ŷ = W * z."""
    return weight @ latent


# ----------------------------------------------------------------------
# Hybrid edge weight computation
# ----------------------------------------------------------------------
def compute_pheromone_modulated_weight(
    health_i: float,
    health_j: float,
    pheromone_entropy: float,
    alpha: float = 0.5,
) -> float:
    """Parent A contribution."""
    return health_i * health_j * math.exp(-alpha * pheromone_entropy)


def hybrid_edge_weight(
    health_i: float,
    health_j: float,
    pher_entropy: float,
    minhash_sim: float,
    alpha: float = 0.5,
    beta: float = 0.3,
) -> float:
    """Full hybrid weight w_H(i,j) = w_A(i,j) * (1 + β * s_B(i,j))."""
    w_a = compute_pheromone_modulated_weight(health_i, health_j, pher_entropy, alpha)
    return w_a * (1.0 + beta * minhash_sim)


# ----------------------------------------------------------------------
# Hoeffding‑guided Bayesian update (Parent A)
# ----------------------------------------------------------------------
def hoeffding_bound(n: int, delta: float = 0.05) -> float:
    """Hoeffding bound ε = sqrt( (1/(2n)) * ln(2/δ) )."""
    if n <= 0:
        return float("inf")
    return math.sqrt((1.0 / (2 * n)) * math.log(2.0 / delta))


def hoeffding_guided_update(
    observations: List[float],
    prior_mean: float,
    prior_var: float,
    delta: float = 0.05,
) -> Tuple[float, float, bool]:
    """
    Perform a Bayesian Gaussian update on the edge weight if the Hoeffding
    bound indicates sufficient samples.

    Returns (posterior_mean, posterior_var, updated_flag).
    """
    n = len(observations)
    eps = hoeffding_bound(n, delta)
    sample_mean = np.mean(observations) if n > 0 else 0.0
    sample_var = np.var(observations, ddof=1) if n > 1 else 1.0

    # If the empirical mean lies within ε of the prior mean, we consider the data
    # informative enough to update.
    if abs(sample_mean - prior_mean) <= eps:
        # Conjugate Gaussian update (known variance = sample_var)
        precision_prior = 1.0 / prior_var
        precision_lik = n / sample_var
        post_var = 1.0 / (precision_prior + precision_lik)
        post_mean = post_var * (precision_prior * prior_mean + precision_lik * sample_mean)
        return post_mean, post_var, True
    else:
        return prior_mean, prior_var, False


# ----------------------------------------------------------------------
# Cost evaluation (combines all pieces)
# ----------------------------------------------------------------------
def evaluate_hybrid_cost(
    nodes: List[Dict],
    edges: List[Tuple[int, int]],
    pher_system: HybridPheromoneSystem,
    now: float,
    alpha: float = 0.5,
    beta: float = 0.3,
) -> float:
    """
    Compute total hybrid cost = sum over edges of hybrid_edge_weight.
    Nodes must contain:
        - 'health': float
        - 'seq': List[int]   (for MinHash)
    """
    # Pre‑compute MinHash signatures for all nodes
    signatures = {
        idx: minhash_signature(node["seq"])
        for idx, node in enumerate(nodes)
    }

    total = 0.0
    for i, j in edges:
        hi = nodes[i]["health"]
        hj = nodes[j]["health"]
        entropy = pher_system.pheromone_entropy(i, j, now)
        sim = minhash_similarity(signatures[i], signatures[j])
        w = hybrid_edge_weight(hi, hj, entropy, sim, alpha, beta)
        total += w
    return total


# ----------------------------------------------------------------------
# Smoke test
# ----------------------------------------------------------------------
if __name__ == "__main__":
    # Seed reproducibility
    random.seed(0)
    np.random.seed(0)

    # Create a tiny synthetic graph
    N = 5
    nodes = []
    for idx in range(N):
        nodes.append(
            {
                "health": random.uniform(0.5, 1.5),
                # Random integer sequence to feed MinHash
                "seq": random.sample(range(1, 100), k=10),
            }
        )

    # Fully connect the graph (undirected, no self‑loops)
    edges = [(i, j) for i in range(N) for j in range(i + 1, N)]

    # Initialise pheromone system and add some synthetic signals
    pher = HybridPheromoneSystem()
    now_ts = 1_000_000.0
    for (i, j) in edges:
        for _ in range(random.randint(1, 4)):
            val = random.expovariate(1.0)  # positive signal
            ts = now_ts - random.uniform(0, 300)  # within last 5 minutes
            pher.add_signal(i, j, val, ts, half_life_seconds=120.0)

    # Evaluate hybrid cost
    total_cost = evaluate_hybrid_cost(
        nodes,
        edges,
        pher_system=pher,
        now=now_ts,
        alpha=0.7,
        beta=0.4,
    )
    print(f"Hybrid total cost over {len(edges)} edges: {total_cost:.4f}")

    # Demonstrate Hoeffding‑guided update on a single edge
    edge_obs = [random.gauss(1.0, 0.2) for _ in range(30)]
    prior_mu = 1.0
    prior_sigma2 = 0.5 ** 2
    post_mu, post_sigma2, updated = hoeffding_guided_update(edge_obs, prior_mu, prior_sigma2)
    print(f"Hoeffding update performed: {updated}")
    print(f"Posterior mean={post_mu:.4f}, variance={post_sigma2:.6f}")