# DARWIN HAMMER — match 5766, survivor 0
# gen: 6
# parent_a: hybrid_hybrid_hybrid_hybrid_hybrid_hybrid_hybrid_m1275_s3.py (gen5)
# parent_b: hybrid_hybrid_hybrid_doomsd_hybrid_hybrid_hybrid_m2673_s2.py (gen5)
# born: 2026-05-30T00:04:42Z

"""Hybrid Algorithm integrating Bayesian decision hygiene (Parent A) with Doomsday‑calendar Gini, pheromone entropy and MST (Parent B).

Mathematical Bridge
-------------------
* **Prior** – Weekday frequency distribution generated by the Doomsday algorithm
  (Parent B) is normalised to a probability vector `π`.
* **Evidence Likelihood** – For each weekday a synthetic pheromone count is
  transformed into a Shannon entropy `H_i`.  The likelihood contribution is
  `L_i = exp(-H_i) * e_i` where `e_i` is the normalised pheromone count
  (Parent B).
* **Feature Likelihood** – Two feature vectors are first restricted by an
  identity‑sheaf map, then a perceptual hash is built, a Hamming‑distance
  derived angle `θ` feeds a Gaussian beam `g(θ)`.  The Fisher information of
  the beam `I(θ)` weights a structural‑similarity (SSIM) score between the
  vectors, giving `ℓ = I(θ)·SSIM` (Parent A).
* **Bayesian Fusion** – Posterior for each weekday:
  `posterior_i ∝ π_i · L_i · ℓ`.  Normalisation yields a proper distribution.
* **Dispersion Metric** – Combines inequality (`Gini` of the original
  frequencies) with uncertainty (`entropy` of the pheromone evidence):
  `Δ = sqrt(Gini² + H_norm²)`.
* **Graph‑Theoretic Cost** – Posterior probabilities are used as node weights
  in a Euclidean minimum‑cost spanning tree (MST); the total weighted edge
  length is the final cost.

The code below implements this unified pipeline with three public functions:
`hybrid_posterior`, `dispersion_metric`, and `mst_weighted_cost`.  A small
smoke test is executed when run as a script.
"""

import math
import random
import sys
from pathlib import Path
from typing import List, Tuple, Dict

import numpy as np

# ----------------------------------------------------------------------
# Parent B – Doomsday calendar, Gini, entropy, MST utilities
# ----------------------------------------------------------------------


def weekday_counts(start_year: int = 2000, end_year: int = 2020) -> Dict[int, int]:
    """Count the weekday (0=Mon … 6=Sun) of Jan 1 for each year in [start_year, end_year]."""
    counts = {i: 0 for i in range(7)}
    for year in range(start_year, end_year + 1):
        # Zeller's congruence for Gregorian calendar, month=January (13, year-1)
        q = 1
        m = 13
        K = (year - 1) % 100
        J = (year - 1) // 100
        h = (q + (13 * (m + 1)) // 5 + K + K // 4 + J // 4 + 5 * J) % 7
        # h = 0 => Saturday, 1 => Sunday, … 5 => Thursday, 6 => Friday
        # Convert to Monday=0 … Sunday=6
        dow = (h + 5) % 7
        counts[dow] += 1
    return counts


def normalize(dist: Dict[int, int]) -> np.ndarray:
    """Return a normalized probability vector from a count dictionary."""
    total = sum(dist.values())
    if total == 0:
        raise ValueError("Distribution empty")
    return np.array([dist[i] / total for i in range(7)], dtype=float)


def gini_coefficient(values: List[float]) -> float:
    """Gini coefficient of a non‑negative list."""
    if not values:
        return 0.0
    sorted_vals = sorted(values)
    n = len(values)
    cumvals = np.cumsum(sorted_vals)
    gini = (n + 1 - 2 * np.sum(cumvals) / cumvals[-1]) / n
    return gini


def shannon_entropy(probs: np.ndarray) -> float:
    """Shannon entropy in nats."""
    eps = np.finfo(float).eps
    probs = np.clip(probs, eps, 1.0)
    return -np.sum(probs * np.log(probs))


def pheromone_evidence(prior: np.ndarray, scale: float = 1.0) -> Tuple[np.ndarray, float]:
    """
    Generate synthetic pheromone counts proportional to the prior,
    compute their normalized distribution and the overall entropy.
    """
    raw = prior * np.random.exponential(scale=scale, size=prior.shape)
    evidence = raw / raw.sum()
    entropy = shannon_entropy(evidence)
    return evidence, entropy


# ----------------------------------------------------------------------
# Parent A – Bayesian decision hygiene, perceptual hash, Fisher‑weighted SSIM
# ----------------------------------------------------------------------


def compute_phash(values: List[float]) -> int:
    """64‑bit perceptual hash of a float list."""
    if not values:
        return 0
    avg = sum(values) / len(values)
    bits = 0
    for v in values[:64]:
        bits = (bits << 1) | int(v >= avg)
    return bits


def hamming_distance(a: int, b: int) -> int:
    """Hamming distance between two integer hashes."""
    return (a ^ b).bit_count()


def angle_from_hamming(dist: int, bits: int = 64) -> float:
    """Map Hamming distance to an angle in [0, π]."""
    return (dist / bits) * math.pi


def gaussian_beam(theta: float, sigma: float = 0.5) -> float:
    """Gaussian beam evaluated at angle theta."""
    return math.exp(-theta * theta / (2 * sigma * sigma))


def fisher_information(theta: float, sigma: float = 0.5) -> float:
    """Fisher information of the Gaussian beam with respect to theta."""
    # I(θ) = (d/dθ log g(θ))^2
    if sigma == 0:
        return 0.0
    dlog = -theta / (sigma * sigma)
    return dlog * dlog


def ssim(x: np.ndarray, y: np.ndarray) -> float:
    """Simple SSIM approximation for 1‑D vectors."""
    C1 = 0.01 ** 2
    C2 = 0.03 ** 2
    mu_x, mu_y = x.mean(), y.mean()
    sigma_x = x.var()
    sigma_y = y.var()
    sigma_xy = ((x - mu_x) * (y - mu_y)).mean()
    numerator = (2 * mu_x * mu_y + C1) * (2 * sigma_xy + C2)
    denominator = (mu_x * mu_x + mu_y * mu_y + C1) * (sigma_x + sigma_y + C2)
    return numerator / denominator if denominator != 0 else 0.0


def fisher_weighted_similarity(vec1: List[float], vec2: List[float]) -> float:
    """Compute I(θ)·SSIM where θ derives from perceptual‑hash Hamming distance."""
    ph1 = compute_phash(vec1)
    ph2 = compute_phash(vec2)
    ham = hamming_distance(ph1, ph2)
    theta = angle_from_hamming(ham)
    I = fisher_information(theta)
    s = ssim(np.array(vec1, dtype=float), np.array(vec2, dtype=float))
    return I * s


def bayes_update(prior: np.ndarray, likelihood: np.ndarray) -> np.ndarray:
    """Posterior ∝ prior × likelihood, normalised."""
    unnorm = prior * likelihood
    total = unnorm.sum()
    if total == 0:
        return np.full_like(prior, 1.0 / prior.size)
    return unnorm / total


# ----------------------------------------------------------------------
# Hybrid core functions
# ----------------------------------------------------------------------


def hybrid_posterior(
    vec_a: List[float],
    vec_b: List[float],
    start_year: int = 2000,
    end_year: int = 2020,
) -> np.ndarray:
    """
    Compute the posterior distribution over weekdays by fusing:
    * Doomsday prior (Parent B)
    * Pheromone‑entropy likelihood (Parent B)
    * Fisher‑weighted SSIM likelihood from feature vectors (Parent A)
    """
    # 1️⃣ Doomsday prior
    counts = weekday_counts(start_year, end_year)
    prior = normalize(counts)                     # π_i

    # 2️⃣ Pheromone evidence → likelihood L_i
    pher_evidence, entropy = pheromone_evidence(prior)
    L_pher = np.exp(-entropy) * pher_evidence      # shape (7,)

    # 3️⃣ Feature similarity → single scalar likelihood ℓ
    feature_likelihood = fisher_weighted_similarity(vec_a, vec_b)  # ∈ [0,1] approx
    L_feat = np.full_like(prior, feature_likelihood)               # broadcast

    # 4️⃣ Combine all likelihood components (element‑wise product)
    combined_likelihood = L_pher * L_feat

    # 5️⃣ Bayesian update
    posterior = bayes_update(prior, combined_likelihood)
    return posterior


def dispersion_metric(start_year: int = 2000, end_year: int = 2020) -> float:
    """
    Compute a unified dispersion metric Δ that blends:
    * Gini coefficient of Doomsday weekday frequencies
    * Normalised Shannon entropy of pheromone evidence
    """
    counts = weekday_counts(start_year, end_year)
    freq_vals = list(counts.values())
    gini = gini_coefficient(freq_vals)

    prior = normalize(counts)
    _, entropy = pheromone_evidence(prior)
    # Normalise entropy to [0,1] (max entropy = ln(7))
    H_norm = entropy / math.log(7)

    return math.sqrt(gini * gini + H_norm * H_norm)


def mst_weighted_cost(
    points: List[Tuple[float, float]],
    posterior: np.ndarray,
) -> float:
    """
    Build a Euclidean minimum‑cost spanning tree where each node i
    (corresponding to weekday i) carries weight w_i = posterior_i.
    Edge cost = Euclidean distance * (w_i + w_j)/2.
    Returns total weighted cost.
    """
    n = len(points)
    if n != 7:
        raise ValueError("Exactly 7 points (one per weekday) required.")
    # Compute all edges
    edges = []
    for i in range(n):
        for j in range(i + 1, n):
            xi, yi = points[i]
            xj, yj = points[j]
            dist = math.hypot(xi - xj, yi - yj)
            weight = (posterior[i] + posterior[j]) / 2.0
            edges.append((dist * weight, i, j))

    # Kruskal's algorithm
    parent = list(range(n))

    def find(u):
        while parent[u] != u:
            parent[u] = parent[parent[u]]
            u = parent[u]
        return u

    def union(u, v):
        ru, rv = find(u), find(v)
        if ru != rv:
            parent[rv] = ru
            return True
        return False

    edges.sort(key=lambda e: e[0])
    total_cost = 0.0
    for cost, i, j in edges:
        if union(i, j):
            total_cost += cost
            if sum(1 for k in range(n) if find(k) == find(0)) == n:
                break
    return total_cost


# ----------------------------------------------------------------------
# Smoke test
# ----------------------------------------------------------------------


if __name__ == "__main__":
    # Random feature vectors for two hypothetical items
    vec1 = [random.random() for _ in range(128)]
    vec2 = [random.random() for _ in range(128)]

    # Compute posterior over weekdays
    post = hybrid_posterior(vec1, vec2)
    print("Posterior distribution over weekdays:", post)

    # Dispersion metric Δ
    delta = dispersion_metric()
    print("Dispersion metric Δ:", delta)

    # Generate 7 planar points (e.g., vertices of a regular heptagon)
    angle_step = 2 * math.pi / 7
    pts = [(math.cos(i * angle_step), math.sin(i * angle_step)) for i in range(7)]

    # MST weighted cost
    cost = mst_weighted_cost(pts, post)
    print("Weighted MST cost:", cost)