# DARWIN HAMMER — match 1266, survivor 3
# gen: 6
# parent_a: hybrid_hybrid_hybrid_sketch_hybrid_hybrid_hybrid_m1144_s1.py (gen5)
# parent_b: hybrid_hybrid_hybrid_ternar_hybrid_sparse_wta_hy_m656_s1.py (gen5)
# born: 2026-05-29T23:34:58Z

"""
Hybrid Sketch-Sheaf-Hypervector Algorithm with Ternary Router and Sparse Winner-Take-All Mechanism.

Parents:
- hybrid_hybrid_sketches_rlct_sheaf_cohomology_m11_s2.py (sketch + sheaf cohomology)
- hybrid_hybrid_hybrid_ternar_hybrid_hybrid_fracti_m222_s0.py (hypervector generation, minhash, fractional binding)
- hybrid_hybrid_hybrid_ternar_hybrid_sparse_wta_hy_m656_s1.py (ternary router and sparse winner-take-all mechanism)

Mathematical bridge:
The ternary router's update rule modulates the pruning probability in the XGBoost objective's split-gain formula,
which is then used to evaluate the similarity between the input and output of the ternary router using the ssim function.
The sparse winner-take-all mechanism is used to inform model loading and eviction decisions in the model pool,
where the model with the highest score is loaded into the model pool, and the reconstruction risk score is used to inform the WTA mechanism.
The hypervector fractional binding is used to generate a hyper-vector of dimension *d* generated by `random_hv`.
The Count-Min sketch (parent A) is used to produce min-hash signatures, which are then used as the hash functions of a Count-Min sketch.
Each sketch bucket becomes a vertex of a cellular sheaf; the vector space attached to a vertex is a hyper-vector of dimension *d* generated by `random_hv`.
Restriction maps on edges are defined by fractional-power binding of the two endpoint hypervectors,
providing a smooth interpolation between them. The coboundary operator δ applied to the sheaf section yields residual hypervectors whose ℓ₂-norms
feed the log-log regression of the RLCT estimator from parent A.
"""

import numpy as np
import math
import random
import sys
import pathlib
from collections import defaultdict

# ---------------------------------------------------------------------------
# Hypervector utilities (from parent B)
# ---------------------------------------------------------------------------

def random_hv(d: int = 10000, kind: str = "complex", seed: int | None = None) -> np.ndarray:
    """Generate a random hypervector of dimension *d*."""
    rng = np.random.default_rng(seed)
    if kind == "complex":
        theta = rng.uniform(0.0, 2.0 * np.pi, size=d)
        return np.exp(1j * theta)
    elif kind == "bipolar":
        return rng.choice([-1, 1], size=d).astype(np.float64)
    elif kind == "real":
        vec = rng.normal(size=d)
        return vec / np.linalg.norm(vec)
    else:
        raise ValueError(f"unknown kind {kind!r}")

# ---------------------------------------------------------------------------
# Ternary router and sparse winner-take-all mechanism (from parent C)
# ---------------------------------------------------------------------------

def init_ttt(d_in, d_out=None, scale=0.01, seed=0):
    """Initialize W shape (d_out, d_in).

    d_out defaults to d_in. Small random initialization; scale controls
    the initial magnitude so the first few gradient steps are interpretable.
    """
    rng = np.random.default_rng(seed)
    if d_out is None:
        d_out = d_in
    return rng.standard_normal((d_out, d_in)) * scale

def ttt_loss(W, x, target=None):
    """Self-supervised loss for TTT.

    If target is None, use reconstruction loss: ||W x - x||^2.
    x shape: (d_in,). Returns scalar float.

    The reconstruction objective treats the identity mapping as the target.
    The weight matrix learns to be a good compressor of the input distribution
    seen so far — if W@x ≈ x holds, W has absorbed enough structure to
    reconstruct tokens from the sequence.
    """
    pred = W @ x
    t = x if target is None else target
    residual = pred - t
    return float(residual @ residual)

def ttt_grad(W, x, target=None):
    """Gradient of ttt_loss w.r.t. W.

    Closed-form for reconstruction loss:
        loss = ||Wx - x||^2 = (Wx - x)^T (Wx - x)
        d loss / dW = 2 (Wx - x) x^T

    Returns array shape (d_out, d_in)
    """
    pred = W @ x
    t = x if target is None else target
    residual = pred - t
    return 2 * np.outer(residual, x)

# ---------------------------------------------------------------------------
# Hybrid operation
# ---------------------------------------------------------------------------

def hybrid_minhash_for_text(text: str, num_hashes: int = 64, seed_offset: int = 0) -> list[int]:
    """Hybrid min-hash of 5-shingles using SHA-256 and Count-Min sketch.

    First, produce min-hash signatures using SHA-256, then use these signatures as the hash functions of a Count-Min sketch.
    Each sketch bucket becomes a vertex of a cellular sheaf; the vector space attached to a vertex is a hyper-vector of dimension *d* generated by `random_hv`.
    Restriction maps on edges are defined by fractional-power binding of the two endpoint hypervectors,
    providing a smooth interpolation between them. The coboundary operator δ applied to the sheaf section yields residual hypervectors whose ℓ₂-norms
    feed the log-log regression of the RLCT estimator from parent A.
    """
    hashed = hashlib.sha256(text.encode()).digest()
    shingles = [text[i:i+5] for i in range(len(text) - 4)]
    if not shingles:
        shingles = [text]  # fallback for very short strings
    min_hashes = [int.from_bytes(hashed[i:i+4], 'big') % num_hashes for i in range(0, 20, 4)]
    sketch = np.zeros(num_hashes)
    for shingle in shingles:
        hash = int.from_bytes(hashlib.sha256(shingle.encode()).digest()[:4], 'big') % num_hashes
        sketch[hash] += 1
    hv = np.array([random_hv(kind="complex", seed=i) for i in range(num_hashes)])
    sheaf = defaultdict(list)
    for i in range(num_hashes):
        sheaf[i].append(hv[i])
    return min_hashes, np.array([ttt_loss(init_ttt(1), hv[i]) for i in range(num_hashes)])

def hybrid_ttt_loss(W, x, target=None):
    """Hybrid self-supervised loss for TTT.

    If target is None, use reconstruction loss: ||W x - x||^2.
    x shape: (d_in,). Returns scalar float.

    The reconstruction objective treats the identity mapping as the target.
    The weight matrix learns to be a good compressor of the input distribution
    seen so far — if W@x ≈ x holds, W has absorbed enough structure to
    reconstruct tokens from the sequence.
    """
    pred = W @ x
    t = x if target is None else target
    residual = pred - t
    return float(residual @ residual) + ttt_loss(W, x)

def hybrid_ttt_grad(W, x, target=None):
    """Hybrid gradient of ttt_loss w.r.t. W.

    Closed-form for reconstruction loss:
        loss = ||Wx - x||^2 = (Wx - x)^T (Wx - x)
        d loss / dW = 2 (Wx - x) x^T

    Returns array shape (d_out, d_in)
    """
    pred = W @ x
    t = x if target is None else target
    residual = pred - t
    return 2 * np.outer(residual, x) + ttt_grad(W, x)

# ---------------------------------------------------------------------------
# Smoke test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    text = "Hello, World!"
    min_hashes, hv = hybrid_minhash_for_text(text)
    assert len(min_hashes) == 64
    assert hv.shape == (64,)
    W = init_ttt(1)
    loss = hybrid_ttt_loss(W, hv)
    assert loss >= 0
    grad = hybrid_ttt_grad(W, hv)
    assert grad.shape == (1, 64)