# DARWIN HAMMER — match 5771, survivor 0
# gen: 6
# parent_a: hybrid_hybrid_hybrid_rlct_g_hybrid_hybrid_hybrid_m2460_s0.py (gen4)
# parent_b: hybrid_hybrid_hybrid_hybrid_hybrid_hybrid_hybrid_m2723_s3.py (gen5)
# born: 2026-05-30T00:04:36Z

"""
Hybrid Algorithm Fusion of:
- Parent Algorithm A: RLCT (log‑log regression) + pheromone infotaxis.
- Parent Algorithm B: Tree metric based health scoring with privacy‑risk weighting.

Mathematical Bridge
------------------
Algorithm A supplies a scalar **rlct_factor** obtained from a log‑log regression of
training loss versus problem size *n*.  This factor quantifies how quickly the
system “grok‑s” and is used to *scale* the health scores generated by Algorithm B.

Algorithm B defines a node health as  

    h_node = (1 - (reconstruction_risk * failure_rate)) *
             (1 - recovery_priority) *
             log(count + 1)

We replace the plain `log(count + 1)` term with a *geometrically‑weighted* version
that incorporates the RLCT factor and a Clifford‑style multivector magnitude
(approximated here by the Euclidean norm of a 2‑D vector).  The fused health becomes  

    h_fused = rlct_factor * ||mv|| * (1 - (reconstruction_risk * failure_rate)) *
              (1 - recovery_priority) * log(count + 1)

where `mv` is a 2‑D multivector built from the pheromone signal strength and the
edge length to the node.  The resulting healths are normalised to obtain work‑share
fractions, which drive both model tier allocation (Algorithm B) and pheromone
update dynamics (Algorithm A).

The code below implements this unified system, exposing three core functions:
`estimate_rlct`, `compute_fused_health`, and `allocate_work_share`, together with
support utilities for pheromone handling and tree metric computation.
"""

import math
import random
import sys
from pathlib import Path
from typing import Dict, List, Tuple, Any

import numpy as np

# ----------------------------------------------------------------------
# Types
# ----------------------------------------------------------------------
Point = Tuple[float, float]
Edge = Tuple[str, str]

# ----------------------------------------------------------------------
# Core utilities from Parent A
# ----------------------------------------------------------------------
def estimate_rlct(train_losses_per_n: List[float], n_values: List[float]) -> float:
    """
    Perform the log‑log regression used in Algorithm A to obtain the RLCT exponent.
    Returns a single float scaling factor.
    """
    losses = np.asarray(train_losses_per_n, dtype=np.float64)
    ns = np.asarray(n_values, dtype=np.float64)

    if np.any(ns <= np.e):
        raise ValueError("All n_values must be > e for log(log(n)) to be positive")
    if losses.shape != ns.shape:
        raise ValueError("train_losses_per_n and n_values must have the same length")

    y = np.log(np.maximum(losses, 1e-300))
    x = np.log(np.log(ns))

    x_c = x - x.mean()
    y_c = y - y.mean()
    var_x = (x_c ** 2).sum()
    if var_x < 1e-15:
        raise ValueError("n_values have no variance in log(log(n)) space")

    return float((x_c * y_c).sum() / var_x)


def calculate_pheromone_signal(
    pheromone_store: Dict[str, Dict[str, float]],
    surface_key: str,
    signal_kind: str,
    signal_value: float,
    half_life_seconds: float,
    elapsed_seconds: float = 1.0,
) -> float:
    """
    Initialise or retrieve a pheromone signal and apply exponential decay.
    """
    if surface_key not in pheromone_store:
        pheromone_store[surface_key] = {}
    store = pheromone_store[surface_key]

    if signal_kind not in store:
        store[signal_kind] = signal_value

    decay_factor = math.pow(0.5, elapsed_seconds / half_life_seconds)
    store[signal_kind] *= decay_factor
    return store[signal_kind]

# ----------------------------------------------------------------------
# Core utilities from Parent B
# ----------------------------------------------------------------------
def length(a: Point, b: Point) -> float:
    """Euclidean distance between two points."""
    return math.hypot(a[0] - b[0], a[1] - b[1])


def tree_metrics(
    nodes: Dict[str, Point],
    edges: List[Edge],
    root: str,
) -> Tuple[Dict[str, List[str]], Dict[Edge, float], Dict[str, float]]:
    """
    Build adjacency list, compute edge lengths, and root‑to‑node distances.
    Returns (adjacency, edge_lengths, root_distances).
    """
    adjacency: Dict[str, List[str]] = {k: [] for k in nodes}
    edge_lengths: Dict[Edge, float] = {}
    for u, v in edges:
        adjacency[u].append(v)
        adjacency[v].append(u)
        edge_lengths[(u, v)] = edge_lengths[(v, u)] = length(nodes[u], nodes[v])

    # BFS to compute root distances
    root_distances: Dict[str, float] = {root: 0.0}
    visited = {root}
    queue = [root]
    while queue:
        current = queue.pop(0)
        for neighbor in adjacency[current]:
            if neighbor not in visited:
                root_distances[neighbor] = root_distances[current] + edge_lengths[(current, neighbor)]
                visited.add(neighbor)
                queue.append(neighbor)

    return adjacency, edge_lengths, root_distances

# ----------------------------------------------------------------------
# Hybrid Fusion Functions
# ----------------------------------------------------------------------
def compute_fused_health(
    nodes: Dict[str, Point],
    edges: List[Edge],
    root: str,
    counts: Dict[str, int],
    failures: Dict[str, int],
    failure_threshold: float,
    unique_qi: Dict[str, int],
    total_records: int,
    recovery_priority: Dict[str, float],
    rlct_factor: float,
    pheromone_store: Dict[str, Dict[str, float]],
) -> Dict[str, float]:
    """
    Compute the fused health for each node using:
    - RLCT scaling (rlct_factor)
    - A multivector magnitude built from pheromone strength and edge length
    - Privacy‑risk and failure terms from Algorithm B
    Returns a dict mapping node identifiers to raw health values.
    """
    _, edge_lengths, root_distances = tree_metrics(nodes, edges, root)

    healths: Dict[str, float] = {}
    for node in nodes:
        # ----- privacy / failure terms -----
        recon_risk = unique_qi.get(node, 0) / total_records
        fail_rate = failures.get(node, 0) / failure_threshold
        term1 = 1.0 - (recon_risk * fail_rate)
        term2 = 1.0 - recovery_priority.get(node, 0.0)

        # ----- count term -----
        cnt = counts.get(node, 0)
        log_count = math.log(cnt + 1)

        # ----- multivector magnitude (approximation) -----
        # Use pheromone strength on the node's surface as one component,
        # and the distance from root as the other.
        pheromone_val = calculate_pheromone_signal(
            pheromone_store,
            surface_key=node,
            signal_kind="signal",
            signal_value=1.0,          # initialise with unit strength if absent
            half_life_seconds=30.0,
            elapsed_seconds=1.0,
        )
        distance = root_distances.get(node, 0.0)
        mv_norm = math.hypot(pheromone_val, distance)  # |mv| = sqrt(p^2 + d^2)

        # ----- fused health -----
        raw = rlct_factor * mv_norm * term1 * term2 * log_count
        healths[node] = max(raw, 0.0)  # enforce non‑negative health

    return healths


def allocate_work_share(healths: Dict[str, float]) -> Dict[str, float]:
    """
    Normalise raw health values into work‑share fractions that sum to 1.
    """
    total = sum(healths.values())
    if total == 0.0:
        # If all healths are zero, distribute uniformly
        n = len(healths)
        return {k: 1.0 / n for k in healths}
    return {k: v / total for k, v in healths.items()}


def update_pheromone_store(
    pheromone_store: Dict[str, Dict[str, float]],
    decay_seconds: float = 1.0,
) -> None:
    """
    Apply a global decay step to all stored pheromone signals.
    """
    for surface_key, signals in pheromone_store.items():
        for kind, val in list(signals.items()):
            # Use a fixed half‑life of 30 s for simplicity
            half_life = 30.0
            decay_factor = math.pow(0.5, decay_seconds / half_life)
            signals[kind] = val * decay_factor

# ----------------------------------------------------------------------
# Example usage / smoke test
# ----------------------------------------------------------------------
if __name__ == "__main__":
    # Dummy training loss data for RLCT estimation
    n_vals = [10, 20, 40, 80, 160]
    losses = [0.8, 0.6, 0.45, 0.33, 0.25]

    rlct = estimate_rlct(losses, n_vals)
    print(f"Estimated RLCT factor: {rlct:.4f}")

    # Simple tree definition
    nodes = {
        "root": (0.0, 0.0),
        "A": (1.0, 2.0),
        "B": (3.0, 1.0),
        "C": (4.0, 4.0),
    }
    edges = [("root", "A"), ("root", "B"), ("A", "C")]
    root_id = "root"

    # Privacy / failure / count mock data
    counts = {"root": 100, "A": 50, "B": 30, "C": 20}
    failures = {"root": 2, "A": 1, "B": 0, "C": 3}
    failure_threshold = 10.0
    unique_qi = {"root": 5, "A": 2, "B": 1, "C": 4}
    total_records = 1000
    recovery_priority = {"root": 0.1, "A": 0.2, "B": 0.3, "C": 0.4}

    # Pheromone store (empty at start)
    pheromone_store: Dict[str, Dict[str, float]] = {}

    # Compute fused healths
    healths = compute_fused_health(
        nodes=nodes,
        edges=edges,
        root=root_id,
        counts=counts,
        failures=failures,
        failure_threshold=failure_threshold,
        unique_qi=unique_qi,
        total_records=total_records,
        recovery_priority=recovery_priority,
        rlct_factor=rlct,
        pheromone_store=pheromone_store,
    )
    print("Raw fused healths:", healths)

    # Allocate work share
    work_share = allocate_work_share(healths)
    print("Work‑share fractions:", work_share)

    # Apply a global pheromone decay step and show updated values
    update_pheromone_store(pheromone_store, decay_seconds=5.0)
    print("Pheromone store after decay:", pheromone_store)