CREATE TABLE IF NOT EXISTS lucidota_runtime.model_startup_receipt (
    receipt_uuid uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    model_name text NOT NULL,
    backend text NOT NULL CHECK (backend IN ('llama_cpp', 'ollama', 'groq', 'mistral', 'local_python')),
    command_hash text,
    instance_id text,
    slots integer,
    ctx_per_slot integer,
    ctx_total integer GENERATED ALWAYS AS (slots * ctx_per_slot) STORED,
    n_gpu_layers integer,
    cache_ram_mb integer,
    startup_started_at timestamptz NOT NULL DEFAULT now(),
    health_passed_at timestamptz,
    startup_spike_duration_ms integer,
    peak_ram_mb numeric(8,1),
    peak_vram_mb numeric(8,1),
    steady_ram_mb numeric(8,1),
    steady_vram_mb numeric(8,1),
    kv_cache_total_mb numeric(8,1) GENERATED ALWAYS AS (slots * ctx_per_slot * 0.0723) STORED,
    compute_buffer_mb numeric(8,1),
    exit_code integer,
    oom_killed boolean DEFAULT false,
    accepted boolean,
    rejection_reason text,
    corpus_quality_gate_passed boolean,
    corpus_quality_pct numeric(5,2),
    detail jsonb DEFAULT '{}'
);
