-- Runtime-only Percyphon village matrix and current surface.
-- Percyphon remains procedural-scaffold-only; UUID is identity, slots are routing coordinates.

BEGIN;

CREATE SCHEMA IF NOT EXISTS lucidota_go;
CREATE SCHEMA IF NOT EXISTS lucidota_runtime;
CREATE SCHEMA IF NOT EXISTS lucidota_canon;

CREATE TABLE IF NOT EXISTS lucidota_go.percyphon_village (
    vuuid           TEXT        NOT NULL,
    name            TEXT        NOT NULL,
    persona         TEXT        NOT NULL,
    alias           TEXT        NOT NULL,
    ternary_state   SMALLINT    NOT NULL CHECK (ternary_state IN (-1, 0, 1)),
    slots           JSONB       NOT NULL DEFAULT '[]'::jsonb,
    relevance_confidence_bps    SMALLINT NOT NULL DEFAULT 0 CHECK (relevance_confidence_bps BETWEEN 0 AND 10000),
    seed            TEXT        NOT NULL,
    authority       TEXT        NOT NULL DEFAULT 'procedural_scaffold_candidate_not_truth' CHECK (authority = 'procedural_scaffold_candidate_not_truth'),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (vuuid)
);

CREATE INDEX IF NOT EXISTS percyphon_village_persona_idx
    ON lucidota_go.percyphon_village (persona);

CREATE INDEX IF NOT EXISTS percyphon_village_ternary_idx
    ON lucidota_go.percyphon_village (ternary_state);

CREATE INDEX IF NOT EXISTS percyphon_village_updated_idx
    ON lucidota_go.percyphon_village (updated_at DESC);

CREATE INDEX IF NOT EXISTS percyphon_village_slots_gin_idx
    ON lucidota_go.percyphon_village USING gin (slots);

CREATE OR REPLACE VIEW lucidota_canon.percyphon_village_matrix AS
SELECT
    vuuid,
    name,
    persona,
    alias,
    ternary_state,
    relevance_confidence_bps,
    seed,
    authority,
    slots,
    updated_at,
    slots->0 AS slot_001,
    slots->1 AS slot_002,
    slots->2 AS slot_003,
    slots->3 AS slot_004,
    slots->4 AS slot_005,
    slots->5 AS slot_006,
    slots->6 AS slot_007,
    slots->7 AS slot_008,
    slots->8 AS slot_009,
    slots->9 AS slot_010,
    slots->10 AS slot_011,
    slots->11 AS slot_012,
    slots->12 AS slot_013,
    slots->13 AS slot_014,
    slots->14 AS slot_015,
    slots->15 AS slot_016,
    slots->16 AS slot_017,
    slots->17 AS slot_018,
    slots->18 AS slot_019,
    slots->19 AS slot_020,
    slots->20 AS slot_021,
    slots->21 AS slot_022,
    slots->22 AS slot_023,
    slots->23 AS slot_024,
    slots->24 AS slot_025,
    slots->25 AS slot_026,
    slots->26 AS slot_027,
    slots->27 AS slot_028,
    slots->28 AS slot_029,
    slots->29 AS slot_030,
    slots->30 AS slot_031,
    slots->31 AS slot_032,
    slots->32 AS slot_033,
    slots->33 AS slot_034,
    slots->34 AS slot_035,
    slots->35 AS slot_036,
    slots->36 AS slot_037,
    slots->37 AS slot_038,
    slots->38 AS slot_039,
    slots->39 AS slot_040,
    slots->40 AS slot_041,
    slots->41 AS slot_042,
    slots->42 AS slot_043,
    slots->43 AS slot_044,
    slots->44 AS slot_045,
    slots->45 AS slot_046,
    slots->46 AS slot_047,
    slots->47 AS slot_048,
    slots->48 AS slot_049,
    slots->49 AS slot_050,
    slots->50 AS slot_051,
    slots->51 AS slot_052,
    slots->52 AS slot_053,
    slots->53 AS slot_054,
    slots->54 AS slot_055,
    slots->55 AS slot_056,
    slots->56 AS slot_057,
    slots->57 AS slot_058,
    slots->58 AS slot_059,
    slots->59 AS slot_060,
    slots->60 AS slot_061,
    slots->61 AS slot_062,
    slots->62 AS slot_063,
    slots->63 AS slot_064,
    slots->64 AS slot_065,
    slots->65 AS slot_066,
    slots->66 AS slot_067,
    slots->67 AS slot_068,
    slots->68 AS slot_069,
    slots->69 AS slot_070,
    slots->70 AS slot_071,
    slots->71 AS slot_072,
    slots->72 AS slot_073,
    slots->73 AS slot_074,
    slots->74 AS slot_075,
    slots->75 AS slot_076,
    slots->76 AS slot_077,
    slots->77 AS slot_078,
    slots->78 AS slot_079,
    slots->79 AS slot_080,
    slots->80 AS slot_081,
    slots->81 AS slot_082,
    slots->82 AS slot_083,
    slots->83 AS slot_084,
    slots->84 AS slot_085,
    slots->85 AS slot_086,
    slots->86 AS slot_087,
    slots->87 AS slot_088,
    slots->88 AS slot_089,
    slots->89 AS slot_090,
    slots->90 AS slot_091,
    slots->91 AS slot_092,
    slots->92 AS slot_093,
    slots->93 AS slot_094,
    slots->94 AS slot_095,
    slots->95 AS slot_096,
    slots->96 AS slot_097,
    slots->97 AS slot_098,
    slots->98 AS slot_099,
    slots->99 AS slot_100,
    slots->100 AS slot_101,
    slots->101 AS slot_102,
    slots->102 AS slot_103,
    slots->103 AS slot_104,
    slots->104 AS slot_105,
    slots->105 AS slot_106,
    slots->106 AS slot_107,
    slots->107 AS slot_108,
    slots->108 AS slot_109,
    slots->109 AS slot_110,
    slots->110 AS slot_111,
    slots->111 AS slot_112,
    slots->112 AS slot_113,
    slots->113 AS slot_114,
    slots->114 AS slot_115,
    slots->115 AS slot_116,
    slots->116 AS slot_117,
    slots->117 AS slot_118,
    slots->118 AS slot_119,
    slots->119 AS slot_120,
    slots->120 AS slot_121,
    slots->121 AS slot_122,
    slots->122 AS slot_123,
    slots->123 AS slot_124,
    slots->124 AS slot_125,
    slots->125 AS slot_126,
    slots->126 AS slot_127,
    slots->127 AS slot_128,
    jsonb_build_object(
        'vuuid', vuuid,
        'name', name,
        'persona', persona,
        'alias', alias,
        'ternary_state', ternary_state,
        'relevance_confidence_bps', relevance_confidence_bps,
        'seed', seed,
        'authority', authority,
        'slot_count', jsonb_array_length(slots),
        'identity_slot_count', LEAST(28, jsonb_array_length(slots)),
        'procedural_slot_count', GREATEST(0, jsonb_array_length(slots) - 28),
        'slot_001', slots->0,
        'slot_028', slots->27,
        'slot_029', slots->28,
        'slot_128', slots->127,
        'updated_at', updated_at
    ) AS packet
FROM lucidota_go.percyphon_village;

DROP VIEW IF EXISTS lucidota_canon.percyphon_current CASCADE;
CREATE VIEW lucidota_canon.percyphon_current AS
WITH latest AS (
    SELECT *
    FROM lucidota_canon.percyphon_village_matrix
    ORDER BY updated_at DESC, vuuid DESC
    LIMIT 1
)
SELECT
    vuuid,
    name,
    persona,
    alias,
    ternary_state,
    relevance_confidence_bps,
    seed,
    authority,
    slots,
        slot_001,
        slot_002,
        slot_003,
        slot_004,
        slot_005,
        slot_006,
        slot_007,
        slot_008,
        slot_009,
        slot_010,
        slot_011,
        slot_012,
        slot_013,
        slot_014,
        slot_015,
        slot_016,
        slot_017,
        slot_018,
        slot_019,
        slot_020,
        slot_021,
        slot_022,
        slot_023,
        slot_024,
        slot_025,
        slot_026,
        slot_027,
        slot_028,
        slot_029,
        slot_030,
        slot_031,
        slot_032,
        slot_033,
        slot_034,
        slot_035,
        slot_036,
        slot_037,
        slot_038,
        slot_039,
        slot_040,
        slot_041,
        slot_042,
        slot_043,
        slot_044,
        slot_045,
        slot_046,
        slot_047,
        slot_048,
        slot_049,
        slot_050,
        slot_051,
        slot_052,
        slot_053,
        slot_054,
        slot_055,
        slot_056,
        slot_057,
        slot_058,
        slot_059,
        slot_060,
        slot_061,
        slot_062,
        slot_063,
        slot_064,
        slot_065,
        slot_066,
        slot_067,
        slot_068,
        slot_069,
        slot_070,
        slot_071,
        slot_072,
        slot_073,
        slot_074,
        slot_075,
        slot_076,
        slot_077,
        slot_078,
        slot_079,
        slot_080,
        slot_081,
        slot_082,
        slot_083,
        slot_084,
        slot_085,
        slot_086,
        slot_087,
        slot_088,
        slot_089,
        slot_090,
        slot_091,
        slot_092,
        slot_093,
        slot_094,
        slot_095,
        slot_096,
        slot_097,
        slot_098,
        slot_099,
        slot_100,
        slot_101,
        slot_102,
        slot_103,
        slot_104,
        slot_105,
        slot_106,
        slot_107,
        slot_108,
        slot_109,
        slot_110,
        slot_111,
        slot_112,
        slot_113,
        slot_114,
        slot_115,
        slot_116,
        slot_117,
        slot_118,
        slot_119,
        slot_120,
        slot_121,
        slot_122,
        slot_123,
        slot_124,
        slot_125,
        slot_126,
        slot_127,
        slot_128,
    jsonb_build_object(
        'vuuid', vuuid,
        'name', name,
        'persona', persona,
        'alias', alias,
        'ternary_state', ternary_state,
        'relevance_confidence_bps', relevance_confidence_bps,
        'seed', seed,
        'authority', authority,
        'slot_count', jsonb_array_length(slots),
        'identity_slot_count', LEAST(28, jsonb_array_length(slots)),
        'procedural_slot_count', GREATEST(0, jsonb_array_length(slots) - 28),
        'slot_001', slot_001,
        'slot_028', slot_028,
        'slot_029', slot_029,
        'slot_128', slot_128,
        'updated_at', updated_at
    ) AS packet,
    updated_at
FROM latest;

INSERT INTO lucidota_canon.schema_owner_manifest (
    surface_id, canonical_owner, packet_class, surface_kind, approval_required, notes, detail
) VALUES
    ('percyphon_village_matrix', 'lucidota_canon', 'runtime_packet', 'view', false, 'Percyphon matrix view with 128 slot columns; UUID is identity and slots are routing coordinates.', '{"source":"runtime"}'::jsonb),
    ('percyphon_current', 'lucidota_canon', 'runtime_packet', 'view', false, 'Latest Percyphon current row for attention routing.', '{"source":"runtime"}'::jsonb)
ON CONFLICT (surface_id) DO UPDATE SET
    canonical_owner = EXCLUDED.canonical_owner,
    packet_class = EXCLUDED.packet_class,
    surface_kind = EXCLUDED.surface_kind,
    approval_required = EXCLUDED.approval_required,
    notes = EXCLUDED.notes,
    detail = EXCLUDED.detail,
    updated_at = now();

INSERT INTO lucidota_canon.api_route_catalog (
    route_id,
    method,
    path_pattern,
    description,
    target,
    sample_request,
    sample_response,
    status
) VALUES
    (
        'percyphon_village_matrix',
        'GET',
        '/percyphon_village_matrix',
        'Percyphon village matrix view with 128 slot columns.',
        'lucidota_canon.percyphon_village_matrix',
        '{"limit":"1"}',
        '{"authority":"procedural_scaffold_candidate_not_truth"}',
        'implemented'
    ),
    (
        'percyphon_current',
        'GET',
        '/percyphon_current',
        'Latest Percyphon current row for attention routing.',
        'lucidota_canon.percyphon_current',
        '{"limit":"1"}',
        '{"authority":"procedural_scaffold_candidate_not_truth"}',
        'implemented'
    )
ON CONFLICT (route_id) DO UPDATE SET
    method = EXCLUDED.method,
    path_pattern = EXCLUDED.path_pattern,
    description = EXCLUDED.description,
    target = EXCLUDED.target,
    sample_request = EXCLUDED.sample_request,
    sample_response = EXCLUDED.sample_response,
    status = EXCLUDED.status,
    updated_at = now();

GRANT SELECT ON lucidota_go.percyphon_village TO lucidota_postgrest_anon, mfspx;
GRANT SELECT ON lucidota_canon.percyphon_village_matrix, lucidota_canon.percyphon_current TO lucidota_postgrest_anon, mfspx;
GRANT SELECT ON lucidota_canon.schema_owner_manifest, lucidota_canon.api_route_catalog TO lucidota_postgrest_anon, mfspx;

COMMIT;
