# DARWIN HAMMER — match 1658, survivor 2
# gen: 4
# parent_a: hybrid_hybrid_fractional_hd_hybrid_korpus_text_h_m125_s1.py (gen3)
# parent_b: hybrid_hybrid_hybrid_worksh_hybrid_geometric_pro_m36_s3.py (gen3)
# born: 2026-05-29T23:38:05Z

"""
Hybrid Hyperdimensional-Allocation Module

This module integrates the Hyperdimensional Computing (HDC) and text analysis operations
from hybrid_hybrid_fractional_hd_hybrid_korpus_text_h_m125_s1.py with the
Hybrid Allocation-LTC-Geometric Product operations from hybrid_hybrid_hybrid_worksh_hybrid_geometric_pro_m36_s3.py.
The mathematical bridge between these structures is the application of HDC's binding operator
to encode the multivector's components in the Hybrid Geometric Product Model and the use
of fractional power binding to model the strength of these relationships. The compact
representation of text data generated by the minhash operation is used as input to
the brain_xyz function.

The module fuses:
1. The HDC and text analysis operations from PARENT ALGORITHM A.
2. The geometric product and LTC-modulated multivector updates from PARENT ALGORITHM B.

The three public functions demonstrate the hybrid operation:
- `init_hybrid_hdc_ltc_gp` – initialise HDC, LTC and geometric product parameters for a single-dimensional day-of-week input.
- `hybrid_allocate_by_dates` – compute per-day, per-group allocations using the LTC-modulated LLM share and the geometric product.
- `summarize_hybrid_savings` – aggregate baseline vs. LTC-modulated allocations and report a savings percentage.
"""

import numpy as np
import math
import random
import sys
from datetime import date
from pathlib import Path

def minhash_for_text(text: str, k: int = 64) -> list[int]:
    """
    Generate a compact representation of the text data using the minhash operation.

    Parameters
    ----------
    text : str
        The input text data.
    k : int, optional
        The number of hash values to generate, by default 64

    Returns
    -------
    list[int]
        A list of hash values representing the compact representation of the text data.
    """
    text = re.sub(r"\s+", " ", text or "").strip().lower()
    shingles = [text[i:i+5] for i in range(len(text)-4)]
    signature = np.random.randint(0, 2**32, size=k)
    return [min(signature[j] for j, shingle in enumerate(shingles) if shingle in text) for j in range(k)]

def random_hv(dim: int) -> np.ndarray:
    """
    Generate a random hyperdimensional vector.

    Parameters
    ----------
    dim : int
        The dimension of the hyperdimensional vector.

    Returns
    -------
    np.ndarray
        A random hyperdimensional vector.
    """
    return np.random.randint(0, 2, size=dim)

def bind(hv1: np.ndarray, hv2: np.ndarray) -> np.ndarray:
    """
    Bind two hyperdimensional vectors using the binding operator.

    Parameters
    ----------
    hv1 : np.ndarray
        The first hyperdimensional vector.
    hv2 : np.ndarray
        The second hyperdimensional vector.

    Returns
    -------
    np.ndarray
        The bound hyperdimensional vector.
    """
    return np.logical_xor(hv1, hv2)

def init_hybrid_hdc_ltc_gp(text: str, dim: int = 256, k: int = 64) -> (np.ndarray, np.ndarray):
    """
    Initialise HDC, LTC and geometric product parameters for a single-dimensional day-of-week input.

    Parameters
    ----------
    text : str
        The input text data.
    dim : int, optional
        The dimension of the hyperdimensional vector, by default 256
    k : int, optional
        The number of hash values to generate, by default 64

    Returns
    -------
    tuple[np.ndarray, np.ndarray]
        A tuple containing the HDC vector and the LTC-modulated multivector.
    """
    hv = random_hv(dim)
    minhash = minhash_for_text(text, k)
    return hv, np.array(minhash)

def hybrid_allocate_by_dates(hv: np.ndarray, ltc_mv: np.ndarray, day_of_week: int) -> np.ndarray:
    """
    Compute per-day, per-group allocations using the LTC-modulated LLM share and the geometric product.

    Parameters
    ----------
    hv : np.ndarray
        The HDC vector.
    ltc_mv : np.ndarray
        The LTC-modulated multivector.
    day_of_week : int
        The day of the week.

    Returns
    -------
    np.ndarray
        The allocated multivector.
    """
    # Apply geometric product
    gp = np.logical_xor(hv, ltc_mv)
    # Modulate by day of week
    modulated_gp = gp * (day_of_week / 7)
    return modulated_gp

def summarize_hybrid_savings(baseline_alloc: np.ndarray, hybrid_alloc: np.ndarray) -> float:
    """
    Aggregate baseline vs. LTC-modulated allocations and report a savings percentage.

    Parameters
    ----------
    baseline_alloc : np.ndarray
        The baseline allocation.
    hybrid_alloc : np.ndarray
        The hybrid allocation.

    Returns
    -------
    float
        The savings percentage.
    """
    savings = np.mean(baseline_alloc - hybrid_alloc) / np.mean(baseline_alloc) * 100
    return savings

if __name__ == "__main__":
    text = "This is a sample text."
    hv, ltc_mv = init_hybrid_hdc_ltc_gp(text)
    day_of_week = date.today().weekday()
    hybrid_alloc = hybrid_allocate_by_dates(hv, ltc_mv, day_of_week)
    baseline_alloc = np.random.rand(len(hybrid_alloc))
    savings = summarize_hybrid_savings(baseline_alloc, hybrid_alloc)
    print(f"Savings: {savings}%")