# DARWIN HAMMER — match 905, survivor 3
# gen: 4
# parent_a: hybrid_hybrid_hybrid_worksh_hybrid_hybrid_ternar_m333_s2.py (gen3)
# parent_b: hybrid_ssim_hybrid_decision_hygi_m9_s2.py (gen2)
# born: 2026-05-29T23:31:31Z

"""Hybrid Workshare-Calender, Liquid-Time-Constant, MinHash & Variational Free-Energy, 
Similarity-based Text Analysis & Decision-Hygiene Fusion

This module merges the two parent algorithms:

* **Parent A** – Hybrid workshare-calendar allocator + Liquid-Time-Constant (LTC) network 
  whose gating depends on a weekday-dependent weight vector *w(d)* and a MinHash similarity *s*.
* **Parent B** – Ternary router evaluated by a variational free-energy (VFE) metric, 
  and a hybrid similarity and decision-hygiene module based on statistical moments.

**Mathematical Bridge**: 
The weekday weight vector `w(d)` is used in two places:
1. **LTC gating** – the effective time constant τ is modulated by a sigmoid of the 
   inner product between `w(d)` and the MinHash similarity vector `s⃗`:
   `g = σ( α·w(d)·s⃗ ) , τ = τ₀ / g`.

2. **VFE weighting** – the KL-term of the variational free-energy is weighted by the same 
   vector, yielding a scalar `KL_w = w(d)·KL(q‖p)`.  
   The total free-energy is `F = 𝔼_q[log p(x|z)] – λ·KL_w`.

3. **Similarity-based Text Analysis** – the SSIM formula is applied to the feature vectors 
   of two texts, treating them as two signals. The resulting similarity index is then 
   combined with the individual hygiene scores and entropy values.

4. **Decision-Hygiene** – the weights of the feature vector are scaled by a linear 
   positive/negative weight, and the Shannon entropy is computed.

The module implements:
* ``hybrid_workshare_ltc_minhash`` – full hybrid operation of the two parents.
* ``text_similarity`` – SSIM on numeric vectors for text analysis.
* ``hygiene_and_entropy`` – hygiene score, raw entropy and normalised entropy for decision-hygiene.
"""

import sys
import math
import random
import json
from pathlib import Path
from datetime import date, datetime, timezone
from typing import Any, Dict, List, Set, Tuple

import numpy as np

# ----------------------------------------------------------------------
# Core constants
# ----------------------------------------------------------------------
GROUPS: Tuple[str, ...] = ("codex", "groq", "cohere", "local_models")
BASE_TAU: float = 1.0          # baseline liquid time constant
ALPHA: float = 5.0             # gating steepness
LAMBDA: float = 0.7            # VFE weighting factor
MINHASH_K: int = 64            # number of hash functions for MinHash
MAX64: int = (1 << 64) - 1     # mask for 64-bit hashing
BINS: int = 9                  # number of bins for decision-hygiene

# ----------------------------------------------------------------------
# Utility: weekday-dependent weight vector (Parent A)
# ----------------------------------------------------------------------
def weekday_weight_vector(groups: Tuple[str, ...], dow: int) -> np.ndarray:
    """
    Normalised weight vector w(d) for the given weekday index ``dow`` (0=Sun … 6=Sat).

    The vector is generated by a sinusoidal pattern whose phase follows a daily cycle.
    """
    weights = np.empty(len(groups))
    for i, group in enumerate(groups):
        weights[i] = math.sin(2 * math.pi * dow / 7 + i * math.pi / len(groups))
    return weights / np.linalg.norm(weights)

# ----------------------------------------------------------------------
# Parent B – regexes and raw count extraction
# ----------------------------------------------------------------------
EVIDENCE_RE = re.compile(
    r"\b(?:evidence|verify|verified|confirm|confirmed|source|sourced|citation|receipt|hash|sha256|screenshot|record|log|document|proof|fact|facts|check|checked|audit)\b",
    re.I,
)
PLANNING_RE = re.compile(
    r"\b(?:plan|checklist|steps?|sequence|timeline|roadmap|phase|priority|prioritize|triage|criteria|protocol|procedure|schedule|budget|scope|test|smoke)\b",
    re.I,
)
DELAY_RE = re.compile(
    r"\b(?:pause|sleep|wait|tomorrow|later|hold|cool down|de[- ]?escalate|not now|before i|first|after|review)\b",
    re.I,
)
SUPPORT_RE = re.compile(
    r"\b(?:ask|call|text|friend|friends|rowyn|kai|chance|doctor|therapist|lawyer|advocate|support|help|community|team|handoff|delegate)\b",
    re.I,
)
BOUNDARY_RE = re.compile(
    r"\b(?:boundary|boundaries|walk away|no contact|do not|don't|stop|limit|refuse|protect|safe|safety|lock|redact|privacy|permission|decline|deny)\b",
    re.I,
)

# ----------------------------------------------------------------------
# Similarity-based Text Analysis (Parent B)
# ----------------------------------------------------------------------
def ssim_vector(a: np.ndarray, b: np.ndarray) -> float:
    """
    Structural similarity index between two numeric vectors.

    The formula is:
    SSIM(a, b) = (2μaμb + c1)(2σab + c2) / ((μa)^2 + (μb)^2 + c1)(σa^2 + σb^2 + c2)
    """
    a_mean, a_var, a_cov = np.mean(a), np.var(a), np.cov(a, b)[0, 1]
    b_mean, b_var, b_cov = np.mean(b), np.var(b), np.cov(b, a)[0, 1]
    c1, c2 = 0.01, 0.03
    return ((2 * a_mean * b_mean + c1) * (2 * a_cov + c2)) / (
        (a_mean ** 2 + b_mean ** 2 + c1) * (a_var + b_var + c2)
    )

# ----------------------------------------------------------------------
# Decision-Hygiene (Parent B)
# ----------------------------------------------------------------------
def hygiene_and_entropy(text: str) -> Tuple[float, float, float]:
    """
    Hygiene score, raw entropy, and normalised entropy for a given text.

    The hygiene score is the sum of the weights of the feature vector.
    The raw entropy is the Shannon entropy of the weights.
    The normalised entropy is the raw entropy divided by the maximum possible entropy.
    """
    weights = np.array([
        1.0 if EVIDENCE_RE.search(text) else 0.0,
        1.0 if PLANNING_RE.search(text) else 0.0,
        1.0 if DELAY_RE.search(text) else 0.0,
        1.0 if SUPPORT_RE.search(text) else 0.0,
        1.0 if BOUNDARY_RE.search(text) else 0.0,
    ])
    hygiene = np.sum(weights)
    entropy = -np.sum(weights * np.log2(weights + 1e-6))
    return hygiene, entropy, entropy / np.log2(len(weights))

# ----------------------------------------------------------------------
# Hybrid Workshare-LTC-MinHash (Parent A)
# ----------------------------------------------------------------------
def hybrid_workshare_ltc_minhash(groups: Tuple[str, ...], dow: int, s: np.ndarray) -> float:
    """
    Hybrid operation of the two parents.

    The weekday weight vector `w(d)` is used in two places:
    1. **LTC gating** – the effective time constant τ is modulated by a sigmoid of the 
       inner product between `w(d)` and the MinHash similarity vector `s⃗`:
       `g = σ( α·w(d)·s⃗ ) , τ = τ₀ / g`.
    2. **VFE weighting** – the KL-term of the variational free-energy is weighted by the same 
       vector, yielding a scalar `KL_w = w(d)·KL(q‖p)`.  
       The total free-energy is `F = 𝔼_q[log p(x|z)] – λ·KL_w`.
    """
    w = weekday_weight_vector(groups, dow)
    g = 1 / (1 + np.exp(-ALPHA * np.dot(w, s)))
    tau = BASE_TAU / g
    kl_w = np.dot(w, np.log(s + 1e-6) - np.log(np.mean(s) + 1e-6))
    return tau, kl_w

# ----------------------------------------------------------------------
# Hybrid Text Similarity
# ----------------------------------------------------------------------
def hybrid_text_similarity(text1: str, text2: str) -> Tuple[float, float, float]:
    """
    Full fusion of the two parents for a pair of texts, returning a detailed report.

    The similarity index is the SSIM between the feature vectors of the two texts.
    The hygiene scores and entropy values are computed separately.
    """
    a = np.array([
        1.0 if EVIDENCE_RE.search(text1) else 0.0,
        1.0 if PLANNING_RE.search(text1) else 0.0,
        1.0 if DELAY_RE.search(text1) else 0.0,
        1.0 if SUPPORT_RE.search(text1) else 0.0,
        1.0 if BOUNDARY_RE.search(text1) else 0.0,
    ])
    b = np.array([
        1.0 if EVIDENCE_RE.search(text2) else 0.0,
        1.0 if PLANNING_RE.search(text2) else 0.0,
        1.0 if DELAY_RE.search(text2) else 0.0,
        1.0 if SUPPORT_RE.search(text2) else 0.0,
        1.0 if BOUNDARY_RE.search(text2) else 0.0,
    ])
    ssim = ssim_vector(a, b)
    h1, e1, _ = hygiene_and_entropy(text1)
    h2, e2, _ = hygiene_and_entropy(text2)
    return ssim, h1, e1, h2, e2

# ----------------------------------------------------------------------
# Smoke test
# ----------------------------------------------------------------------
if __name__ == "__main__":
    text1 = "This is a sample text."
    text2 = "This is another sample text."
    ssim, h1, e1, h2, e2 = hybrid_text_similarity(text1, text2)
    print(f"SSIM: {ssim:.4f}, Hygiene 1: {h1:.4f}, Entropy 1: {e1:.4f}, Hygiene 2: {h2:.4f}, Entropy 2: {e2:.4f}")