# DARWIN HAMMER — match 159, survivor 1
# gen: 4
# parent_a: hybrid_hybrid_hybrid_sketch_dense_associative_me_m32_s1.py (gen3)
# parent_b: hybrid_ternary_lens_router_hybrid_decision_hygi_m44_s1.py (gen2)
# born: 2026-05-29T23:27:19Z

"""
Hybrid Module: hybrid_hybrid_sketch_dense_ternary_entropy.py

This module fuses the mathematical cores of two parent algorithms:

* **Parent A** – a sheaf‑theoretic wrapper around a Dense Associative Memory (DAM).  
  The sheaf stores *sections* (vectors) on nodes and *restriction maps* on edges.
  Retrieval is performed by the DAM energy  
  `E(x) = - (1/β) * logsumexp(β * M @ x) + 0.5 * ||x||²`.

* **Parent B** – a ternary lens router that produces ternary vectors (elements in
  `{‑1, 0, 1}`) and analyses them with Shannon entropy.

**Mathematical Bridge**

We treat each sheaf section as a *ternary query vector* generated by the
lens‑router.  The Shannon entropy `H(v)` of the ternary symbol distribution is
used to modulate the DAM temperature parameter `β`.  High entropy (more
uncertainty) yields a larger `β`, sharpening the energy landscape, while low
entropy yields a softer landscape.  The restriction maps are updated using the
same entropy‑scaled energy gradient, thus coupling the sheaf topology with the
information‑theoretic properties of the ternary vectors.

The resulting hybrid provides:
1. Generation of ternary vectors for sheaf sections.
2. Entropy‑aware DAM energy computation.
3. Entropy‑scaled restriction‑map updates.
"""

import numpy as np
import math
import random
import sys
import pathlib
from collections import Counter

# ----------------------------------------------------------------------
# Sheaf infrastructure (from Parent A)
# ----------------------------------------------------------------------
class Sheaf:
    def __init__(self, node_dims, edges):
        """
        node_dims: dict {node_id: dimension}
        edges: list of (src, dst) tuples
        """
        self.node_dims = dict(node_dims)
        self.edges = list(edges)
        self._restrictions = {}   # (u,v) -> (src_map, dst_map)
        self._sections = {}       # node -> vector

    def set_restriction(self, edge, src_map, dst_map):
        u, v = edge
        src_map = np.asarray(src_map, dtype=float)
        dst_map = np.asarray(dst_map, dtype=float)
        if src_map.shape[1] != self.node_dims[u]:
            raise ValueError("src_map column dimension must match dim(node u)")
        if dst_map.shape[1] != self.node_dims[v]:
            raise ValueError("dst_map column dimension must match dim(node v)")
        if src_map.shape[0] != dst_map.shape[0]:
            raise ValueError("src_map and dst_map must have the same row dimension")
        self._restrictions[(u, v)] = (src_map, dst_map)

    def set_section(self, node, value):
        if node not in self.node_dims:
            raise KeyError(f"Node {node} not defined in sheaf")
        vec = np.asarray(value, dtype=float)
        if vec.shape[0] != self.node_dims[node]:
            raise ValueError("Section vector length must match node dimension")
        self._sections[node] = vec

    def get_section(self, node):
        return self._sections[node]

    def get_restriction(self, edge):
        return self._restrictions[edge]

# ----------------------------------------------------------------------
# Ternary lens router utilities (from Parent B)
# ----------------------------------------------------------------------
def generate_ternary_vector(dim, seed=None):
    """
    Produce a random ternary vector of given dimension.
    Elements are drawn uniformly from {-1, 0, 1}.
    """
    rng = np.random.default_rng(seed)
    return rng.choice([-1, 0, 1], size=dim)

def shannon_entropy(vector):
    """
    Compute Shannon entropy of the empirical distribution of symbols in a
    ternary vector. Zero probabilities are ignored.
    """
    counts = Counter(vector.tolist())
    total = len(vector)
    entropy = 0.0
    for cnt in counts.values():
        p = cnt / total
        entropy -= p * math.log(p, 2)  # bits
    return entropy

# ----------------------------------------------------------------------
# Dense Associative Memory core (from Parent A)
# ----------------------------------------------------------------------
def _logsumexp(z):
    """
    Numerically stable log-sum-exp.
    """
    m = np.max(z)
    return m + np.log(np.exp(z - m).sum())

def dam_energy(xi, M, beta=1.0):
    """
    Energy of a query vector xi under weight matrix M.
    """
    xi = np.asarray(xi, dtype=float)
    M = np.asarray(M, dtype=float)
    scores = beta * (M @ xi)
    lse = _logsumexp(scores) / beta
    quad = 0.5 * xi @ xi
    return -lse + quad

def hybrid_energy(sheaf, query_node, M, base_beta=1.0):
    """
    Compute DAM energy where the temperature β is scaled by the Shannon entropy
    of the node's ternary section.
    """
    vec = sheaf.get_section(query_node)
    if not np.all(np.isin(vec, [-1, 0, 1])):
        raise ValueError("Section vector must be ternary for entropy scaling")
    H = shannon_entropy(vec)
    beta = base_beta * (1.0 + H)   # entropy‑aware scaling
    return dam_energy(vec, M, beta)

# ----------------------------------------------------------------------
# Hybrid update rule tying restriction maps to entropy‑scaled gradients
# ----------------------------------------------------------------------
def update_restriction_entropy(sheaf, edge, M, base_beta=1.0, lr=0.01):
    """
    Perform a single gradient‑like update of the restriction maps on the given edge.
    The gradient is approximated by the derivative of the DAM energy w.r.t. the
    source section, scaled by the edge's entropy factor.
    """
    u, v = edge
    src_map, dst_map = sheaf.get_restriction(edge)
    src_vec = sheaf.get_section(u)

    # Compute entropy‑scaled beta for the source node
    H = shannon_entropy(src_vec)
    beta = base_beta * (1.0 + H)

    # Energy gradient w.r.t. src_vec (∂E/∂x ≈ x - Mᵀ·softmax(β·M·x))
    scores = beta * (M @ src_vec)
    probs = np.exp(scores - np.max(scores))
    probs /= probs.sum()
    grad = src_vec - M.T @ probs

    # Apply gradient to restriction maps (simple outer‑product style update)
    delta_src = -lr * np.outer(grad, np.ones(src_map.shape[0]))
    delta_dst = -lr * np.outer(grad, np.ones(dst_map.shape[0]))

    sheaf._restrictions[(u, v)] = (src_map + delta_src, dst_map + delta_dst)

# ----------------------------------------------------------------------
# Higher‑level hybrid operation
# ----------------------------------------------------------------------
def route_and_update(sheaf, M, base_beta=1.0, lr=0.01):
    """
    For every edge:
      1. Generate a fresh ternary section on the source node.
      2. Compute entropy‑aware energy.
      3. Update restriction maps using the entropy‑scaled gradient.
    Returns a dict mapping edge -> energy value.
    """
    energies = {}
    for edge in sheaf.edges:
        u, _ = edge
        # generate new ternary section for source node
        dim = sheaf.node_dims[u]
        new_section = generate_ternary_vector(dim)
        sheaf.set_section(u, new_section)

        # compute energy
        E = hybrid_energy(sheaf, u, M, base_beta)
        energies[edge] = E

        # update restrictions
        update_restriction_entropy(sheaf, edge, M, base_beta, lr)

    return energies

# ----------------------------------------------------------------------
# Smoke test
# ----------------------------------------------------------------------
if __name__ == "__main__":
    # Simple sheaf with two nodes and a single directed edge
    node_dims = {0: 5, 1: 5}
    edges = [(0, 1)]

    sheaf = Sheaf(node_dims, edges)

    # Initialise random restriction maps (same row count for compatibility)
    rng = np.random.default_rng(42)
    src_map = rng.normal(size=(3, node_dims[0]))
    dst_map = rng.normal(size=(3, node_dims[1]))
    sheaf.set_restriction((0, 1), src_map, dst_map)

    # Initialise a ternary section on node 0 and a zero section on node 1
    sheaf.set_section(0, generate_ternary_vector(node_dims[0], seed=1))
    sheaf.set_section(1, np.zeros(node_dims[1]))

    # Random DAM weight matrix
    M = rng.normal(size=(node_dims[0], node_dims[0]))

    # Run hybrid routing and updating
    energies = route_and_update(sheaf, M, base_beta=0.5, lr=0.05)

    # Print results (ensuring the script runs without exception)
    for edge, E in energies.items():
        print(f"Edge {edge} – Energy: {E:.4f}")

    # Verify that restriction maps have been altered
    src_updated, dst_updated = sheaf.get_restriction((0, 1))
    assert not np.allclose(src_updated, src_map), "Source map should have changed"
    assert not np.allclose(dst_updated, dst_map), "Destination map should have changed"

    print("Hybrid module smoke test completed successfully.")