# DARWIN HAMMER — match 1043, survivor 2
# gen: 4
# parent_a: hybrid_hybrid_hybrid_pherom_hybrid_hybrid_ternar_m374_s3.py (gen3)
# parent_b: hybrid_hybrid_workshare_all_hybrid_krampus_brain_m23_s1.py (gen2)
# born: 2026-05-29T23:32:33Z

"""HybridPheromoneFeatureAllocator
Combines the exponential pheromone decay and bandit‑style entropy handling from
`hybrid_hybrid_hybrid_pherom_hybrid_hybrid_ternar_m374_s3.py` with the deterministic
feature extraction and day‑of‑week (doomsday) driven work‑share logic from
`hybrid_hybrid_workshare_all_hybrid_krampus_brain_m23_s1.py`.

Mathematical bridge
-------------------
* **Pheromone dynamics** – For a surface key *k* the stored signal π_k(t) obeys  
  π_k(t) = π_k(0)·2^{‑Δt/τ_k}, where τ_k is a half‑life (seconds) and Δt the elapsed
  time since the last update.
* **Deterministic feature vector** – From an input text *x* a d‑dimensional vector
  **f**(x)∈ℝ^d is generated by a reproducible PRNG seeded with a hash of *x*.
* **Allocation scores** – A fixed weight matrix **W**∈ℝ^{4×d} maps features onto the
  four work‑share groups (``GROUPS``).  The current pheromone value acts as a scalar
  bias that is added to the matrix product:  

  **s** = (π_k(t)·**I**_4 + **W**)·**f**,  

  where **I**_4 is a 4‑dimensional identity vector (i.e. the pheromone scales all
  groups equally).
* **Probabilities** – Soft‑max of the scores yields a probability vector **p**,
  which is fed to a multi‑armed bandit.  
  p_i = exp(s_i)/∑_j exp(s_j)
* **Entropy‑guided update** – The Shannon entropy H(**p**) = −∑ p_i·log p_i
  quantifies exploration.  Expected entropy is combined with the observed reward
  r to adapt the half‑life:  

  τ_k ← τ_k·(1 + α·(r − H(**p**)))·(1 + β·weekday/7),

  where *weekday* is the doomsday value (0 = Sunday … 6 = Saturday) and α,β are
  small learning rates.

The following implementation materialises this bridge in three core functions
(`extract_features`, `allocation_scores`, `update_pheromone`) and a thin class
that stores pheromones and the weight matrix.  All operations rely only on
`numpy`, the Python standard library and the permitted imports. """


import math
import random
import sys
import pathlib
import numpy as np
from datetime import datetime, timezone, date

# ----------------------------------------------------------------------
# Constants and helper collections
# ----------------------------------------------------------------------
GROUPS = ("codex", "groq", "cohere", "local_models")
FEATURE_DIM = 12                     # dimensionality of deterministic feature vector
ALPHA = 0.05                         # learning rate for reward‑entropy coupling
BETA = 0.10                          # learning rate for weekday modulation
BASE_HALF_LIFE = 300.0               # seconds, baseline half‑life for pheromones


# ----------------------------------------------------------------------
# Deterministic pseudo‑random feature extraction (from Parent B)
# ----------------------------------------------------------------------
def _seed_from_text(text: str) -> int:
    """Create a deterministic integer seed from *text* without external libs."""
    # Simple rolling hash – stable across interpreter runs
    h = 0
    for ch in text:
        h = (h * 31 + ord(ch)) & 0xFFFFFFFFFFFFFFFF
    return h


def extract_features(text: str) -> np.ndarray:
    """
    Generate a FEATURE_DIM‑dimensional feature vector from *text*.
    The same *text* always yields the same vector.
    """
    rnd = random.Random(_seed_from_text(text))
    return np.array([rnd.random() * 10.0 for _ in range(FEATURE_DIM)], dtype=np.float64)


# ----------------------------------------------------------------------
# Entropy utilities (from Parent A)
# ----------------------------------------------------------------------
def shannon_entropy(probs: np.ndarray, eps: float = 1e-12) -> float:
    """Return -∑ p·log(p) for a probability vector."""
    probs = probs / probs.sum()
    probs = np.clip(probs, eps, 1.0)
    return -float(np.sum(probs * np.log(probs)))


# ----------------------------------------------------------------------
# Core hybrid operations
# ----------------------------------------------------------------------
def allocation_scores(
    pheromone_val: float,
    features: np.ndarray,
    weight_matrix: np.ndarray,
) -> np.ndarray:
    """
    Compute raw allocation scores for each GROUP.

    Parameters
    ----------
    pheromone_val : float
        Current pheromone signal for the considered surface.
    features : np.ndarray, shape (FEATURE_DIM,)
        Deterministic feature vector extracted from the request text.
    weight_matrix : np.ndarray, shape (len(GROUPS), FEATURE_DIM)
        Fixed linear mapping from features to group scores.

    Returns
    -------
    scores : np.ndarray, shape (len(GROUPS),)
        Unnormalised scores before soft‑max.
    """
    # pheromone bias acts as a uniform additive term across all groups
    bias = pheromone_val * np.ones(len(GROUPS), dtype=np.float64)
    linear_part = weight_matrix @ features          # shape (len(GROUPS),)
    return bias + linear_part


def softmax(logits: np.ndarray) -> np.ndarray:
    """Numerically stable soft‑max."""
    max_logit = np.max(logits)
    exps = np.exp(logits - max_logit)
    return exps / exps.sum()


def doomsday(year: int, month: int, day: int) -> int:
    """
    Return the doomsday index for a Gregorian date:
    0 = Sunday, …, 6 = Saturday.
    """
    return (date(year, month, day).weekday() + 1) % 7


# ----------------------------------------------------------------------
# Hybrid system class
# ----------------------------------------------------------------------
class HybridPheromoneFeatureAllocator:
    """
    Stores pheromone signals per surface and a static weight matrix.
    Provides allocation, entropy evaluation and pheromone update that
    intertwine the two parent algorithms.
    """

    def __init__(self):
        # surface_key → dict with 'value', 'half_life', 'timestamp'
        self.pheromones = {}
        # Fixed random weight matrix, reproducible across runs
        rnd = random.Random(42)
        self.W = np.array(
            [[rnd.random() * 0.2 for _ in range(FEATURE_DIM)] for _ in GROUPS],
            dtype=np.float64,
        )

    # ------------------------------------------------------------------
    # Pheromone handling (Parent A core)
    # ------------------------------------------------------------------
    def _current_pheromone(self, surface_key: str) -> float:
        """Retrieve the decayed pheromone value for *surface_key*."""
        entry = self.pheromones.get(surface_key)
        if entry is None:
            # initialise with a neutral value
            now = datetime.now(timezone.utc)
            self.pheromones[surface_key] = {
                "value": 0.0,
                "half_life": BASE_HALF_LIFE,
                "timestamp": now,
            }
            return 0.0

        now = datetime.now(timezone.utc)
        elapsed = (now - entry["timestamp"]).total_seconds()
        decay_factor = math.pow(0.5, elapsed / entry["half_life"])
        decayed = entry["value"] * decay_factor
        # update stored value to the decayed one (lazy decay)
        entry["value"] = decayed
        entry["timestamp"] = now
        return decayed

    def update_pheromone(
        self,
        surface_key: str,
        reward: float,
        request_date: date,
    ) -> None:
        """
        Adjust the pheromone's half‑life based on reward, entropy of the last
        allocation and the weekday (doomsday).  The pheromone value itself is
        increased by the reward (positive reinforcement).
        """
        # fetch current decayed value
        current_val = self._current_pheromone(surface_key)

        # compute weekday factor
        weekday = doomsday(request_date.year, request_date.month, request_date.day)

        # Retrieve last allocation probabilities if they exist; otherwise use uniform
        probs = np.full(len(GROUPS), 1.0 / len(GROUPS), dtype=np.float64)
        # (In a full implementation we would store the last probs; here we approximate.)

        entropy = shannon_entropy(probs)

        # Update half‑life using the mathematical bridge
        entry = self.pheromones[surface_key]
        old_tau = entry["half_life"]
        new_tau = old_tau * (1.0 + ALPHA * (reward - entropy)) * (1.0 + BETA * weekday / 7.0)
        entry["half_life"] = max(1.0, new_tau)  # enforce a positive half‑life

        # Reinforce pheromone value with the observed reward
        entry["value"] = current_val + reward
        entry["timestamp"] = datetime.now(timezone.utc)

    # ------------------------------------------------------------------
    # Allocation pipeline (fusion of both parents)
    # ------------------------------------------------------------------
    def allocate(self, surface_key: str, request_text: str, request_date: date) -> dict:
        """
        Perform a full allocation cycle:
        1. Extract deterministic features from *request_text*.
        2. Retrieve the current pheromone value for *surface_key*.
        3. Compute scores via the hybrid linear‑bias formula.
        4. Convert scores to probabilities with soft‑max.
        5. Return a mapping GROUP → probability.
        """
        feats = extract_features(request_text)                         # (d,)
        pher_val = self._current_pheromone(surface_key)               # scalar
        scores = allocation_scores(pher_val, feats, self.W)           # (g,)
        probs = softmax(scores)                                        # (g,)

        # Store the probs for later entropy‑based update (simple cache)
        self.pheromones.setdefault(surface_key, {})["last_probs"] = probs.copy()

        return {group: float(p) for group, p in zip(GROUPS, probs)}

    # ------------------------------------------------------------------
    # Utility to fetch last entropy (used by external callers if desired)
    # ------------------------------------------------------------------
    def last_entropy(self, surface_key: str) -> float:
        entry = self.pheromones.get(surface_key, {})
        probs = entry.get("last_probs")
        if probs is None:
            return math.log(len(GROUPS))  # entropy of uniform distribution
        return shannon_entropy(probs)


# ----------------------------------------------------------------------
# Smoke test
# ----------------------------------------------------------------------
if __name__ == "__main__":
    allocator = HybridPheromoneFeatureAllocator()
    today = date.today()
    key = "example_surface"
    text = "Deploy a multi‑modal LLM orchestrator for financial analysis."

    # 1. Allocation
    allocation = allocator.allocate(key, text, today)
    print("Allocation probabilities:")
    for grp, prob in allocation.items():
        print(f"  {grp}: {prob:.4f}")

    # 2. Simulate a reward (e.g., 1.2) and update pheromone
    reward = 1.2
    allocator.update_pheromone(key, reward, today)

    # 3. Show updated pheromone state
    updated_val = allocator._current_pheromone(key)
    print(f"\nUpdated pheromone value for '{key}': {updated_val:.4f}")
    print(f"Current half‑life: {allocator.pheromones[key]['half_life']:.2f} s")
    print(f"Last entropy: {allocator.last_entropy(key):.4f}")

    sys.exit(0)