# DARWIN HAMMER — match 2788, survivor 5
# gen: 7
# parent_a: hybrid_hybrid_hybrid_hybrid_hybrid_hybrid_hybrid_m1216_s6.py (gen6)
# parent_b: hybrid_hybrid_hybrid_decisi_hybrid_hybrid_liquid_m39_s1.py (gen3)
# born: 2026-05-29T23:45:56Z

"""Hybrid Fusion of:
- Parent A: Bandit‑Router / Store update with B‑spline signature (dance signal d)
- Parent B: Decision‑hygiene regex filtering + Liquid‑time diffusion forcing

Mathematical Bridge
------------------
The scalar *dance signal* `d` generated by Parent A is used to dynamically scale the
diffusion time‑constant `τ` of Parent B:

    τ' = τ · (1 + tanh(d))

Thus the store’s internal state influences how aggressively the diffusion forcing
perturbs the input tokens.  
Conversely, the regex‑based evidence score `e` (a scalar in [0,1]) rescales the
bandit propensity update, closing a bidirectional loop:

    π_i' = π_i · (1 + e) · ŵ_{group(i)}

where `ŵ` is the work‑share vector obtained after the diffusion‑scaled allocation.

The code below implements this closed‑loop system with three demonstrative
functions:
1. `lead_lag_bspline_signature` – builds a B‑spline‑like signature from a time
   series.
2. `store_update_from_signature` – updates the dance signal `d` using the signature
   and a tree‑metric matrix `M`.
3. `process_text_with_diffusion` – filters text with regex hygiene patterns,
   computes a diffusion step whose time‑constant is scaled by `d`, and returns the
   noisy representation together with an updated bandit propensity vector.

A lightweight smoke test runs the full pipeline without external data."""

import numpy as np
import math
import random
import sys
from pathlib import Path
from typing import List, Tuple, Dict

# ----------------------------------------------------------------------
# Parent A – B‑spline signature & store update
# ----------------------------------------------------------------------
def lead_lag_bspline_signature(series: np.ndarray, knots: int = 5) -> np.ndarray:
    """
    Approximate a B‑spline signature of a 1‑D time series.
    The implementation uses a simple moving‑average basis as a stand‑in
    for real B‑spline evaluation.

    Parameters
    ----------
    series : np.ndarray
        Input time‑series (shape: (T,)).
    knots : int
        Number of basis functions (default 5).

    Returns
    -------
    signature : np.ndarray
        Vector of length `knots` containing the aggregated basis responses.
    """
    T = series.shape[0]
    if T < knots:
        raise ValueError("Series length must exceed number of knots.")
    # Uniform knot positions
    positions = np.linspace(0, T - 1, knots, dtype=int)
    # Simple triangular basis around each knot
    sig = np.zeros(knots)
    width = max(1, T // (2 * knots))
    for i, pos in enumerate(positions):
        left = max(0, pos - width)
        right = min(T, pos + width + 1)
        weights = np.linspace(0, 1, right - left)
        sig[i] = np.dot(series[left:right], weights) / (right - left + 1e-9)
    # Normalise to unit L2 norm
    norm = np.linalg.norm(sig) + 1e-12
    return sig / norm

def store_update_from_signature(
    d: float,
    signature: np.ndarray,
    M: np.ndarray,
    dt: float = 1.0,
) -> float:
    """
    Perform one store update step:
        d_{t+1} = d_t + dt * (sᵀ·M)

    Parameters
    ----------
    d : float
        Current dance signal.
    signature : np.ndarray
        Signature vector `s`.
    M : np.ndarray
        Tree‑metric matrix (size len(s) × len(s)).
    dt : float
        Integration timestep.

    Returns
    -------
    d_next : float
        Updated dance signal.
    """
    if signature.shape[0] != M.shape[0] or M.shape[0] != M.shape[1]:
        raise ValueError("Signature length must match dimensions of M (square).")
    increment = dt * float(signature @ M @ np.ones_like(signature))
    return d + increment

# ----------------------------------------------------------------------
# Parent B – Regex hygiene + diffusion forcing
# ----------------------------------------------------------------------
# Regex feature set (same as original parent)
EVIDENCE_RE = re.compile(
    r"\b(?:evidence|verify|verified|confirm|confirmed|source|sourced|citation|receipt|hash|sha256|screenshot|record|log|document|proof|fact|facts|check|checked|audit)\b",
    re.I,
)
PLANNING_RE = re.compile(
    r"\b(?:plan|checklist|steps?|sequence|timeline|roadmap|phase|priority|prioritize|triage|criteria|protocol|procedure|schedule|budget|scope|test|smoke)\b",
    re.I,
)
DELAY_RE = re.compile(
    r"\b(?:pause|sleep|wait|tomorrow|later|hold|cool down|de[- ]?escalate|not now|before i|first|after|review)\b",
    re.I,
)
SUPPORT_RE = re.compile(
    r"\b(?:ask|call|text|friend|friends|rowyn|kai|chance|doctor|therapist|lawyer|advocate|support|help|community|team|handoff|delegate)\b",
    re.I,
)

def regex_evidence_score(text: str) -> float:
    """
    Compute a scalar evidence score in [0,1] based on the presence of
    predefined regex patterns. The score is the proportion of pattern
    matches relative to the total number of patterns.

    Parameters
    ----------
    text : str
        Input text to evaluate.

    Returns
    -------
    score : float
        Evidence score ∈ [0,1].
    """
    patterns = [EVIDENCE_RE, PLANNING_RE, DELAY_RE, SUPPORT_RE]
    matches = sum(bool(p.search(text)) for p in patterns)
    return matches / len(patterns)

def diffusion_forcing(
    x: np.ndarray,
    I: np.ndarray,
    tau: float,
    A: np.ndarray,
    s: float,
    d: float,
    alpha_schedule: List[float],
) -> Tuple[np.ndarray, float]:
    """
    Perform one diffusion forcing step with the dance signal `d`
    scaling the time‑constant `τ`.

    The governing equations are:
        f = σ( W·[x; I; s] + b )
        τ' = τ·(1 + tanh(d))
        dx/dt = -(1/τ' + f)·x + f·A
        t_i = round( (1 - s) * T )
        x_noisy_i = √α[t_i]·I_i + √(1-α[t_i])·ε_i

    For simplicity we set W = identity (augmented) and b = 0,
    and treat `s` as a scalar scaling factor (0≤s≤1).

    Parameters
    ----------
    x : np.ndarray
        Current state vector.
    I : np.ndarray
        Input token vector (same shape as x).
    tau : float
        Base time constant.
    A : np.ndarray
        Attractor vector.
    s : float
        Similarity scalar ∈ [0,1] (e.g. signature similarity).
    d : float
        Dance signal from Parent A.
    alpha_schedule : List[float]
        Cumulative diffusion schedule (values in (0,1)).

    Returns
    -------
    x_next : np.ndarray
        Updated state after diffusion.
    noisy_norm : float
        L2 norm of the noisy input (diagnostic).
    """
    # 1. Scale τ with dance signal
    tau_prime = tau * (1.0 + math.tanh(d))

    # 2. Simple sigmoid activation on concatenated vector
    concat = np.concatenate([x, I, np.array([s])])
    # Identity weights + zero bias
    f = 1.0 / (1.0 + np.exp(-concat.mean()))  # scalar between 0 and 1

    # 3. Differential update (Euler step, dt=1)
    dx = -(1.0 / tau_prime + f) * x + f * A
    x_next = x + dx

    # 4. Diffusion noise injection
    T = len(alpha_schedule)
    ti = int(round((1.0 - s) * (T - 1)))
    alpha_t = alpha_schedule[ti]
    eps = np.random.randn(*I.shape)
    x_noisy = math.sqrt(alpha_t) * I + math.sqrt(1.0 - alpha_t) * eps
    noisy_norm = np.linalg.norm(x_noisy)

    # Combine deterministic and noisy parts (simple average)
    x_next = 0.5 * (x_next + x_noisy)

    return x_next, noisy_norm

# ----------------------------------------------------------------------
# Fusion – allocation & bandit propensity adjustment
# ----------------------------------------------------------------------
def allocate_workshare(U: float, p: np.ndarray, d: float) -> np.ndarray:
    """
    Allocate total workload `U` across groups using a target percentage vector `p`,
    scaled by the bounded dance signal.

        p̂ = p · (1 + tanh(d))
        ŵ = U · p̂ / sum(p̂)

    Parameters
    ----------
    U : float
        Total workload.
    p : np.ndarray
        Target percentage vector (sums to 1).
    d : float
        Dance signal.

    Returns
    -------
    w_hat : np.ndarray
        Work‑share vector for each group.
    """
    scale = 1.0 + math.tanh(d)
    p_hat = p * scale
    w_hat = U * p_hat / (p_hat.sum() + 1e-12)
    return w_hat

def adjust_bandit_propensities(
    pi: np.ndarray,
    groups: List[int],
    workshare: np.ndarray,
    evidence_score: float,
) -> np.ndarray:
    """
    Adjust bandit propensities using both the work‑share allocation and the
    regex evidence score.

        π_i' = π_i · (1 + evidence_score) · ŵ_{group(i)}

    Parameters
    ----------
    pi : np.ndarray
        Original propensity vector (length N).
    groups : List[int]
        Group index for each arm (values in 0..G-1).
    workshare : np.ndarray
        Work‑share vector for each group (length G).
    evidence_score : float
        Regex‑based evidence score ∈ [0,1].

    Returns
    -------
    pi_prime : np.ndarray
        Updated propensities.
    """
    factor = 1.0 + evidence_score
    pi_prime = np.empty_like(pi, dtype=float)
    for i, g in enumerate(groups):
        pi_prime[i] = pi[i] * factor * workshare[g]
    # Normalise to keep a probability distribution
    total = pi_prime.sum() + 1e-12
    return pi_prime / total

# ----------------------------------------------------------------------
# Demonstration pipeline
# ----------------------------------------------------------------------
def process_text_with_diffusion(
    text: str,
    x: np.ndarray,
    I: np.ndarray,
    tau: float,
    A: np.ndarray,
    d: float,
    alpha_schedule: List[float],
) -> Tuple[np.ndarray, float]:
    """
    Full hybrid step:
    1. Compute regex evidence score.
    2. Derive similarity scalar `s` from signature‑to‑store match.
    3. Run diffusion forcing with τ scaled by `d`.
    4. Return updated state and the evidence score.

    The similarity scalar `s` is mocked as the cosine similarity between
    the B‑spline signature of the text length and a fixed reference vector.
    """
    # Evidence score from regexes
    e_score = regex_evidence_score(text)

    # Mock signature: treat text length as a scalar series
    series = np.arange(len(text)) % 10 + 1.0
    sig = lead_lag_bspline_signature(series)
    # Reference signature (random but fixed for reproducibility)
    rng = np.random.default_rng(42)
    ref_sig = rng.random(sig.shape)
    ref_sig /= np.linalg.norm(ref_sig) + 1e-12
    s = float(sig @ ref_sig)  # cosine similarity ∈ [0,1] after clipping
    s = max(0.0, min(1.0, s))

    # Diffusion step
    x_next, noisy_norm = diffusion_forcing(x, I, tau, A, s, d, alpha_schedule)

    return x_next, e_score

# ----------------------------------------------------------------------
# Smoke test
# ----------------------------------------------------------------------
if __name__ == "__main__":
    # 1. Initialise store (dance signal) and matrix M
    d = 0.0
    dim = 6
    rng = np.random.default_rng(0)
    M = rng.random((dim, dim))
    M = (M + M.T) / 2.0  # make symmetric

    # 2. Generate synthetic time series and update dance signal
    series = np.sin(np.linspace(0, 4 * np.pi, 120)) + 0.1 * rng.standard_normal(120)
    sig = lead_lag_bspline_signature(series, knots=dim)
    d = store_update_from_signature(d, sig, M, dt=0.05)

    # 3. Bandit setup
    N = 12  # number of arms
    G = 3   # groups
    pi = rng.random(N)
    pi /= pi.sum()
    groups = [i % G for i in range(N)]

    # 4. Allocation
    U = 100.0
    p_target = np.array([0.5, 0.3, 0.2])  # sums to 1
    workshare = allocate_workshare(U, p_target, d)

    # 5. Text processing + diffusion
    sample_text = "Please verify the source and provide a screenshot of the evidence."
    x = rng.random(dim)
    I = rng.random(dim)
    tau = 2.0
    A = rng.random(dim)
    alpha_sched = np.linspace(0.1, 0.9, 10).tolist()
    x_next, evidence = process_text_with_diffusion(
        sample_text, x, I, tau, A, d, alpha_sched
    )

    # 6. Adjust propensities with both bridges
    pi_prime = adjust_bandit_propensities(pi, groups, workshare, evidence)

    # 7. Output diagnostics
    print(f"Dance signal d: {d:.4f}")
    print(f"Workshare vector: {workshare}")
    print(f"Evidence score: {evidence:.2f}")
    print(f"Updated state norm: {np.linalg.norm(x_next):.4f}")
    print(f"Propensities before: {pi[:5]}")
    print(f"Propensities after : {pi_prime[:5]}")
    sys.exit(0)