# DARWIN HAMMER — match 4276, survivor 1
# gen: 7
# parent_a: hybrid_hybrid_hybrid_ternar_hybrid_hybrid_sketch_m965_s0.py (gen4)
# parent_b: hybrid_hybrid_hybrid_hybrid_hybrid_hybrid_hybrid_m1257_s0.py (gen6)
# born: 2026-05-29T23:54:41Z

"""
Hybrid Algorithm Fusion of:
- Parent A: hybrid_hybrid_hybrid_ternar_hybrid_hybrid_sketch_m965_s0.py
- Parent B: hybrid_hybrid_hybrid_hybrid_hybrid_hybrid_hybrid_m1257_s0.py

Mathematical Bridge
-------------------
Parent A supplies *sketching* primitives (Count‑Min Sketch, HyperLogLog) that
compress a multiset of items into a low‑dimensional integer vector.
Parent B provides a *RBF surrogate* that maps a low‑dimensional vector to a
scalar score using a Gaussian radial basis function, together with linear
system utilities for semiseparable matrix handling.

The fusion treats the sketch vector as the feature space on which the RBF
surrogate operates.  The surrogate output is then used as the “score” for
each candidate configuration generated by the ternary router.  The best
configuration (maximum surrogate score) is selected as the routing decision.
Thus the dimensionality‑reduction pipeline of Parent A feeds directly into the
surrogate‑based scoring pipeline of Parent B, creating a unified hybrid
system.

The module implements:
1. Count‑Min sketch and HyperLogLog (from Parent A).
2. Gaussian RBF evaluation and a simple linear solver (from Parent B).
3. A ternary router that enumerates all possible input→output mappings.
4. A Voronoi‑style assignment that can be used to cluster sketch vectors
   (demonstrating the Voronoi concept of Parent A).
5. The hybrid routing function that fuses the two topologies.
"""

import hashlib
import math
import random
import sys
from pathlib import Path
import numpy as np

# ----------------------------------------------------------------------
# Parent A primitives
# ----------------------------------------------------------------------
def count_min_sketch(items, width: int = 64, depth: int = 4):
    """Return a Count‑Min sketch table for *items*."""
    table = [[0] * width for _ in range(depth)]
    for item in items:
        for d in range(depth):
            h = int(hashlib.sha256(f"{d}:{item}".encode()).hexdigest(), 16)
            table[d][h % width] += 1
    return table


def hyperloglog(items, p: int = 14):
    """Return the HyperLogLog cardinality estimate (E) and the raw register sum (V)."""
    m = 1 << p
    M = [0] * m
    for item in items:
        x = int(hashlib.sha256(str(item).encode()).hexdigest(), 16)
        j = x >> (64 - p)                     # bucket index
        w = x & ((1 << (64 - p)) - 1)         # remaining bits
        rho = (w.bit_length() - (64 - p)) + 1  # position of first 1
        M[j] = max(M[j], rho)
    E = m * (1.0 / sum(2.0 ** -v for v in M))
    V = sum(M)
    return E, V


def ternary_router(num_inputs: int = 3, num_outputs: int = 3):
    """
    Enumerate all possible ternary routing configurations.
    Each configuration is a list of length *num_inputs* where each entry is an
    integer in [0, num_outputs).
    """
    configs = []
    total = num_outputs ** num_inputs
    for idx in range(total):
        cfg = []
        remainder = idx
        for _ in range(num_inputs):
            cfg.append(remainder % num_outputs)
            remainder //= num_outputs
        configs.append(cfg)
    return configs


def voronoi_partition(points: np.ndarray, centroids: np.ndarray):
    """
    Assign each point to the nearest centroid (Euclidean distance).
    Returns an array of cluster indices with shape (len(points),).
    """
    if points.ndim != 2 or centroids.ndim != 2:
        raise ValueError("points and centroids must be 2‑D arrays")
    dists = np.linalg.norm(points[:, None, :] - centroids[None, :, :], axis=2)
    return np.argmin(dists, axis=1)


# ----------------------------------------------------------------------
# Parent B primitives
# ----------------------------------------------------------------------
def gaussian_rbf(r: float, epsilon: float = 1.0) -> float:
    """Gaussian radial basis function."""
    return math.exp(-((epsilon * r) ** 2))


def euclidean(a: np.ndarray, b: np.ndarray) -> float:
    """Euclidean distance between two 1‑D arrays."""
    if a.shape != b.shape:
        raise ValueError("vectors must have same dimension")
    return np.sqrt(np.sum((a - b) ** 2))


def solve_linear(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    """
    Solve the linear system A x = b using Gaussian elimination with partial pivoting.
    a: (n, n) matrix, b: (n,) vector.
    Returns x as an (n,) ndarray.
    """
    n = b.shape[0]
    # Build augmented matrix
    aug = np.hstack([a.astype(float), b.reshape(-1, 1)])
    for col in range(n):
        # Pivot
        pivot_row = np.argmax(np.abs(aug[col:, col])) + col
        if abs(aug[pivot_row, col]) < 1e-12:
            raise ValueError("singular system")
        # Swap rows
        if pivot_row != col:
            aug[[col, pivot_row]] = aug[[pivot_row, col]]
        # Normalize pivot row
        aug[col] = aug[col] / aug[col, col]
        # Eliminate other rows
        for row in range(n):
            if row != col:
                aug[row] -= aug[row, col] * aug[col]
    return aug[:, -1]


def rbf_surrogate_predict(x: np.ndarray, centers: np.ndarray, weights: np.ndarray, epsilon: float = 1.0):
    """
    Compute the RBF surrogate output:
        f(x) = Σ_i w_i * φ(||x - c_i||)
    where φ is the Gaussian RBF.
    """
    if centers.shape[0] != weights.shape[0]:
        raise ValueError("number of centers must match number of weights")
    vals = np.array([gaussian_rbf(euclidean(x, c), epsilon) for c in centers])
    return np.dot(weights, vals)


# ----------------------------------------------------------------------
# Hybrid core functions
# ----------------------------------------------------------------------
def sketch_to_feature_vector(sketch_table):
    """
    Convert a Count‑Min sketch (list of lists) into a fixed‑size feature vector.
    The conversion concatenates the rows and normalises by the total count.
    """
    flat = np.array(sketch_table).flatten().astype(float)
    total = flat.sum()
    if total == 0:
        return flat
    return flat / total


def hybrid_score_matrix(sketch_vec: np.ndarray, configs, centers, weights, epsilon=1.0):
    """
    Build a score matrix where each row corresponds to a routing configuration
    and each column corresponds to a surrogate component (here we use a single
    scalar per configuration).  The matrix is semiseparable in the sense that
    it can be expressed as U * V^T with U derived from config vectors and V
    derived from the RBF surrogate evaluated on the sketch vector.
    """
    # Encode each configuration as a binary (one‑hot) vector of length depth*width
    # for simplicity we reuse the sketch dimension.
    depth = len(configs[0])
    width = 1  # we treat each routing decision as a scalar feature
    encoded = np.zeros((len(configs), depth * width))
    for i, cfg in enumerate(configs):
        encoded[i, :depth] = cfg  # pad/truncate to depth
    # Compute surrogate scores for the *same* sketch vector (treated as x)
    surrogate_score = rbf_surrogate_predict(sketch_vec, centers, weights, epsilon)
    # Form a rank‑1 (semiseparable) matrix: U * V^T
    U = encoded
    V = np.full((1, depth * width), surrogate_score)
    return U @ V.T  # shape (n_configs, n_configs)


def hybrid_route(items, centers, weights, num_inputs=3, num_outputs=3, epsilon=1.0):
    """
    End‑to‑end hybrid routing:
    1. Sketch the input items.
    2. Convert the sketch to a normalised feature vector.
    3. Enumerate all ternary routing configurations.
    4. Score each configuration with the RBF surrogate (using the sketch vector).
    5. Return the configuration with the highest score.
    """
    # 1‑2. Sketch → feature vector
    sketch = count_min_sketch(items)
    feat_vec = sketch_to_feature_vector(sketch)

    # 3. Configurations
    configs = ternary_router(num_inputs, num_outputs)

    # 4. Score each configuration
    scores = []
    for cfg in configs:
        cfg_vec = np.array(cfg, dtype=float)
        # Pad to same dimension as feature vector for distance computation
        if cfg_vec.shape[0] < feat_vec.shape[0]:
            pad = np.zeros(feat_vec.shape[0] - cfg_vec.shape[0])
            cfg_vec = np.concatenate([cfg_vec, pad])
        elif cfg_vec.shape[0] > feat_vec.shape[0]:
            cfg_vec = cfg_vec[: feat_vec.shape[0]]
        score = rbf_surrogate_predict(cfg_vec, centers, weights, epsilon)
        scores.append(score)

    # 5. Select best configuration
    best_idx = int(np.argmax(scores))
    best_cfg = configs[best_idx]
    return {
        "best_configuration": best_cfg,
        "best_score": float(scores[best_idx]),
        "all_scores": scores,
        "sketch_feature_vector": feat_vec.tolist(),
    }


# ----------------------------------------------------------------------
# Smoke test
# ----------------------------------------------------------------------
if __name__ == "__main__":
    # Generate synthetic items
    random.seed(42)
    items = [random.randint(0, 1000) for _ in range(200)]

    # Create random RBF centers and weights matching the sketch dimension
    dummy_sketch = count_min_sketch(items)
    feat_dim = np.prod(np.array(dummy_sketch).shape)
    centers = np.random.rand(5, feat_dim)  # 5 RBF centers
    weights = np.random.rand(5)

    result = hybrid_route(
        items,
        centers,
        weights,
        num_inputs=3,
        num_outputs=3,
        epsilon=0.5,
    )
    print("Best configuration:", result["best_configuration"])
    print("Best score:", result["best_score"])
    print("Sketch feature vector (first 10):", result["sketch_feature_vector"][:10])