# DARWIN HAMMER — match 4227, survivor 5
# gen: 7
# parent_a: hybrid_hybrid_hybrid_hybrid_hybrid_hybrid_hybrid_m1742_s1.py (gen6)
# parent_b: hybrid_xgboost_objective_hybrid_hybrid_hybrid_m2130_s1.py (gen5)
# born: 2026-05-29T23:54:21Z

"""HybridSheaf-XGBoost Fusion Module
Parents:
- hybrid_hybrid_hybrid_hybrid_hybrid_hybrid_hybrid_m1742_s1.py (HybridSheaf with Gini analysis)
- hybrid_xgboost_objective_hybrid_hybrid_hybrid_m2130_s1.py (XGBoost objective with Ollivier‑Ricci curvature)

Mathematical Bridge:
The Gini coefficient computed on the burst‑signal counts generated by the
HybridSheaf is used as a *inequality scaling factor* for the Ollivier‑Ricci
curvature that modulates XGBoost split‑gain and leaf‑weight calculations.
Thus the hybrid split‑gain becomes:

    G_hybrid = split_gain(...) * (1 + Gini) * (1 + curvature)

where `curvature` is obtained from the XGBoost‑derived features scaled by the
same Gini factor. This single scalar unifies the two topologies:
the sheaf‑theoretic restriction/section maps produce the burst statistics,
and the gradient‑based tree objective supplies curvature‑aware regularisation.
"""

import math
import random
import sys
import pathlib
import numpy as np
from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Tuple

# ----------------------------------------------------------------------
# Core data structures from Parent A
# ----------------------------------------------------------------------
@dataclass(frozen=True)
class Entity:
    id: str
    lat: float
    lon: float
    category: str
    score: float = 0.0
    address_signature: str = ""

@dataclass(frozen=True)
class BurstSignal:
    key: str
    count: int
    z_score: float

class HybridSheaf:
    """Minimal representation of the HybridSheaf topology."""
    def __init__(self, node_dims: Dict[Any, int], edges: List[Tuple[Any, Any]], patterns: np.ndarray):
        self.node_dims = node_dims                # dimension per node
        self.edges = edges                        # list of (u, v)
        self.patterns = patterns                  # abstract pattern matrix
        self._restrictions: Dict[Tuple[Any, Any], Tuple[np.ndarray, np.ndarray]] = {}
        self._sections: Dict[Any, np.ndarray] = {}

    def set_restriction(self, edge: Tuple[Any, Any], src_map: np.ndarray, dst_map: np.ndarray) -> None:
        u, v = edge
        if src_map.shape[1] != self.node_dims[u]:
            raise ValueError("src_map column dimension must match dim(node u)")
        if dst_map.shape[1] != self.node_dims[v]:
            raise ValueError("dst_map column dimension must match dim(node v)")
        if src_map.shape[0] != dst_map.shape[0]:
            raise ValueError("src_map and dst_map must have the same row dimension")
        self._restrictions[(u, v)] = (np.asarray(src_map, dtype=float),
                                      np.asarray(dst_map, dtype=float))

    def set_section(self, node: Any, value: np.ndarray) -> None:
        if value.shape[0] != self.node_dims[node]:
            raise ValueError("Section vector size must equal node dimension")
        self._sections[node] = np.asarray(value, dtype=float)

    def project_pattern(self, edge: Tuple[Any, Any]) -> np.ndarray:
        """Project the internal pattern matrix onto an edge using its restriction maps."""
        if edge not in self._restrictions:
            raise KeyError(f"No restriction defined for edge {edge}")
        src_map, dst_map = self._restrictions[edge]
        # Simple linear projection: patterns @ src_map.T -> intermediate,
        # then intermediate @ dst_map
        intermediate = self.patterns @ src_map.T
        projected = intermediate @ dst_map
        return projected

    def generate_burst_signals(self, edge: Tuple[Any, Any], n: int = 10) -> List[BurstSignal]:
        """Create synthetic burst signals based on projected patterns."""
        proj = self.project_pattern(edge)
        # Use absolute values as pseudo‑counts
        counts = np.abs(proj).flatten()
        # Pad or trim to length n
        if counts.size < n:
            counts = np.pad(counts, (0, n - counts.size), constant_values=0)
        else:
            counts = counts[:n]
        mean, std = counts.mean(), counts.std(ddof=1) if counts.size > 1 else 1.0
        signals = []
        for i, cnt in enumerate(counts):
            z = (cnt - mean) / (std if std > 0 else 1.0)
            signals.append(BurstSignal(key=f"{edge}_{i}", count=int(cnt), z_score=z))
        return signals

# ----------------------------------------------------------------------
# Gini coefficient (Parent A utility)
# ----------------------------------------------------------------------
def gini_coefficient(values: Iterable[float]) -> float:
    """Return the Gini coefficient of a 1‑D list/array of values."""
    arr = np.asarray(list(values), dtype=float)
    if arr.size == 0:
        return 0.0
    # Ensure non‑negative
    arr = np.abs(arr)
    sorted_arr = np.sort(arr)
    n = arr.size
    cumulative = np.cumsum(sorted_arr)
    gini = (n + 1 - 2 * np.sum(cumulative) / cumulative[-1]) / n
    return float(gini)

# ----------------------------------------------------------------------
# Core functions from Parent B (XGBoost + curvature)
# ----------------------------------------------------------------------
def extract_features(X: np.ndarray) -> Dict[str, float]:
    """Placeholder feature extractor that returns random scalars."""
    features: Dict[str, float] = {}
    features.update({
        "xgb_split_ratio": random.random(),
        "xgb_depth_ratio": random.random(),
        "oric_curvature": random.random(),
        "bayes_evidence": random.random(),
    })
    return features

def calculate_oric_curvature(features: Dict[str, float]) -> Dict[str, float]:
    """Map XGBoost‑related features to a curvature‑like space."""
    oric: Dict[str, float] = {}
    for k, v in features.items():
        if k.startswith("xgb"):
            oric[k] = v * 0.1               # shrink XGB ratios
        elif "oric" in k:
            oric[k] = v                     # keep curvature term
    return oric

def optimal_leaf_weight(gradient_sum: float, hessian_sum: float, reg_lambda: float = 1.0) -> float:
    """Standard XGBoost leaf weight with L2 regularisation."""
    return -float(gradient_sum) / (float(hessian_sum) + float(reg_lambda))

def split_gain(
    left_gradient: float,
    left_hessian: float,
    right_gradient: float,
    right_hessian: float,
    *,
    reg_lambda: float = 1.0,
    gamma: float = 0.0,
) -> float:
    """XGBoost split‑gain formula."""
    gl, hl = float(left_gradient), float(left_hessian)
    gr, hr = float(right_gradient), float(right_hessian)
    parent = (gl + gr) ** 2 / (hl + hr + reg_lambda)
    children = gl ** 2 / (hl + reg_lambda) + gr ** 2 / (hr + reg_lambda)
    return 0.5 * (children - parent) - gamma

def sigmoid(x: np.ndarray | float) -> np.ndarray | float:
    return 1.0 / (1.0 + np.exp(-x))

# ----------------------------------------------------------------------
# Hybrid Operations (the new unified system)
# ----------------------------------------------------------------------
def hybrid_curvature_factor(sheaf: HybridSheaf, edge: Tuple[Any, Any]) -> float:
    """
    Compute a scalar factor that combines:
    - Gini coefficient of burst‑signal counts on `edge`
    - Average Ollivier‑Ricci curvature derived from XGBoost features
    The factor is 1 + gini + curvature_mean.
    """
    # 1. Burst signals → Gini
    burst_signals = sheaf.generate_burst_signals(edge, n=12)
    counts = [bs.count for bs in burst_signals]
    gini = gini_coefficient(counts)

    # 2. XGBoost‑style features → curvature
    dummy_X = np.random.rand(1, sheaf.patterns.shape[1])  # placeholder input
    feats = extract_features(dummy_X)
    oric = calculate_oric_curvature(feats)
    curvature_vals = [v for k, v in oric.items() if "oric" in k]
    curvature_mean = float(np.mean(curvature_vals)) if curvature_vals else 0.0

    return 1.0 + gini + curvature_mean

def hybrid_split_gain(
    sheaf: HybridSheaf,
    edge: Tuple[Any, Any],
    left_gradient: float,
    left_hessian: float,
    right_gradient: float,
    right_hessian: float,
    *,
    reg_lambda: float = 1.0,
    gamma: float = 0.0,
) -> float:
    """
    XGBoost split gain modulated by the HybridSheaf‑Gini‑curvature factor.
    """
    base_gain = split_gain(
        left_gradient,
        left_hessian,
        right_gradient,
        right_hessian,
        reg_lambda=reg_lambda,
        gamma=gamma,
    )
    factor = hybrid_curvature_factor(sheaf, edge)
    return base_gain * factor

def hybrid_optimal_leaf_weight(
    sheaf: HybridSheaf,
    edge: Tuple[Any, Any],
    gradient_sum: float,
    hessian_sum: float,
    reg_lambda: float = 1.0,
) -> float:
    """
    Adjust the regularisation term of the leaf weight by the Gini‑curvature factor.
    """
    factor = hybrid_curvature_factor(sheaf, edge)
    adjusted_lambda = reg_lambda * factor
    return optimal_leaf_weight(gradient_sum, hessian_sum, adjusted_lambda)

def hybrid_update_curvature_matrix(
    curvature_matrix: np.ndarray,
    sheaf: HybridSheaf,
    edge: Tuple[Any, Any],
    bayes_evidence: float,
) -> np.ndarray:
    """
    Bayesian update of the curvature matrix using evidence scaled by the Gini factor.
    """
    factor = hybrid_curvature_factor(sheaf, edge)
    update = bayes_evidence * factor
    # Simple additive update; ensure shape compatibility
    if curvature_matrix.shape != (1, 1):
        raise ValueError("Expected a 1x1 curvature matrix for demo purposes.")
    return curvature_matrix + np.array([[update]])

# ----------------------------------------------------------------------
# Smoke test
# ----------------------------------------------------------------------
if __name__ == "__main__":
    # Construct a tiny HybridSheaf instance
    node_dims = {"A": 3, "B": 2}
    edges = [("A", "B")]
    patterns = np.random.rand(4, 3)  # 4 patterns, 3‑dim node A
    sheaf = HybridSheaf(node_dims, edges, patterns)

    # Define simple restriction maps (identity‑like)
    src_map = np.eye(3, 3)  # from A (3) to intermediate (3)
    dst_map = np.random.rand(3, 2)  # from intermediate (3) to B (2)
    sheaf.set_restriction(("A", "B"), src_map, dst_map)

    # Demonstrate hybrid split gain
    gain = hybrid_split_gain(
        sheaf,
        ("A", "B"),
        left_gradient=1.2,
        left_hessian=0.8,
        right_gradient=-0.4,
        right_hessian=0.5,
        reg_lambda=1.0,
        gamma=0.1,
    )
    print(f"Hybrid split gain: {gain:.6f}")

    # Demonstrate hybrid leaf weight
    leaf_w = hybrid_optimal_leaf_weight(
        sheaf,
        ("A", "B"),
        gradient_sum=0.7,
        hessian_sum=0.9,
        reg_lambda=1.0,
    )
    print(f"Hybrid leaf weight: {leaf_w:.6f}")

    # Demonstrate curvature matrix update
    curv_mat = np.array([[0.3]])
    updated_mat = hybrid_update_curvature_matrix(
        curv_mat,
        sheaf,
        ("A", "B"),
        bayes_evidence=0.05,
    )
    print(f"Updated curvature matrix: {updated_mat}")