# DARWIN HAMMER — match 4848, survivor 2
# gen: 7
# parent_a: hybrid_hybrid_hybrid_hybrid_hybrid_hybrid_hybrid_m1771_s2.py (gen6)
# parent_b: hybrid_hybrid_temporal_moti_hybrid_doomsday_cale_m218_s0.py (gen2)
# born: 2026-05-29T23:58:21Z

"""
This module fuses the Hybrid Hammer algorithm (hybrid_hybrid_hybrid_hybrid_hybrid_hybrid_hybrid_m1771_s2.py) 
and the Hybrid Temporal Motif algorithm with Doomsday Calendar (hybrid_hybrid_temporal_moti_hybrid_doomsday_cale_m218_s0.py).
The mathematical bridge between the two algorithms lies in the application of the Gini Coefficient 
to the pheromone signals generated by the Hybrid Hammer algorithm. The Gini Coefficient is used to 
measure the inequality of the pheromone signals, which can help in identifying significant patterns.

The governing equations of the Hybrid Hammer algorithm are used to generate pheromone signals, 
while the Gini Coefficient is applied to these signals to measure their inequality.
"""

import numpy as np
import math
import random
import sys
import pathlib
import time

class StrikeState:
    def __init__(self, velocity: float, distance: float, peak_velocity: float):
        self.velocity = velocity
        self.distance = distance
        self.peak_velocity = peak_velocity


class PheromoneEntry:
    def __init__(self, surface_key: str, signal_kind: str, signal_value: float, half_life_seconds: int):
        self.surface_key = surface_key
        self.signal_kind = signal_kind
        self.signal_value = signal_value
        self.half_life_seconds = half_life_seconds
        self.created_at = time.time()
        self.last_decay = self.created_at

    def age_seconds(self) -> float:
        return time.time() - self.last_decay

    def decay_factor(self) -> float:
        if self.half_life_seconds <= 0:
            return 0.0
        return 0.5 ** (self.age_seconds() / self.half_life_seconds)

    def apply_decay(self):
        factor = self.decay_factor()
        self.signal_value *= factor
        self.last_decay = time.time()


class Entity:
    def __init__(self, id: str, lat: float, lon: float, category: str, score: float = 0.0, address_signature: str = ""):
        self.id = id
        self.lat = lat
        self.lon = lon
        self.category = category
        self.score = score
        self.address_signature = address_signature


class BurstSignal:
    def __init__(self, key: str, count: int, z_score: float):
        self.key = key
        self.count = count
        self.z_score = z_score


def haversine(a: tuple[float, float], b: tuple[float, float]) -> float:
    lat1, lon1 = map(math.radians, a)
    lat2, lon2 = map(math.radians, b)
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    h = math.sin(dlat / 2) ** 2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2) ** 2
    return 2 * 6_371_000.0 * math.asin(min(1.0, math.sqrt(h)))


def gini_coefficient(values: list[float]) -> float:
    if not values:
        return 0.0
    values = sorted(values)
    if values[0] < 0:
        raise ValueError("values must be non-negative")
    n = len(values)
    i = list(range(1, n + 1))  # 1-based index
    numerator = sum((2 * x - n - 1) * y for x, y in zip(i, values))
    denominator = n * sum(values)
    return numerator / denominator


def detect_bursts(events: list[dict], key: str = 'category') -> list[BurstSignal]:
    counter = {}
    for event in events:
        if key not in event:
            continue
        category = event[key]
        if category not in counter:
            counter[category] = 0
        counter[category] += 1
    mean = sum(counter.values()) / len(counter)
    variance = sum((count - mean) ** 2 for count in counter.values()) / len(counter)
    bursts = []
    for k, count in counter.items():
        z_score = (count - mean) / math.sqrt(variance)
        bursts.append(BurstSignal(k, count, z_score))
    return bursts


def generate_pheromone_signals(strike_states: list[StrikeState]) -> list[PheromoneEntry]:
    pheromone_signals = []
    for strike_state in strike_states:
        surface_key = f"{strike_state.velocity}_{strike_state.distance}_{strike_state.peak_velocity}"
        signal_kind = "velocity"
        signal_value = strike_state.velocity
        half_life_seconds = 3600  # 1 hour
        pheromone_signals.append(PheromoneEntry(surface_key, signal_kind, signal_value, half_life_seconds))
    return pheromone_signals


def apply_gini_coefficient(pheromone_signals: list[PheromoneEntry]) -> float:
    signal_values = [signal.signal_value for signal in pheromone_signals]
    return gini_coefficient(signal_values)


def hybrid_operation(strike_states: list[StrikeState], events: list[dict]) -> tuple[list[PheromoneEntry], list[BurstSignal], float]:
    pheromone_signals = generate_pheromone_signals(strike_states)
    bursts = detect_bursts(events)
    gini = apply_gini_coefficient(pheromone_signals)
    return pheromone_signals, bursts, gini


if __name__ == "__main__":
    strike_states = [StrikeState(10.0, 100.0, 20.0), StrikeState(20.0, 200.0, 30.0)]
    events = [{"category": "A"}, {"category": "B"}, {"category": "A"}]
    pheromone_signals, bursts, gini = hybrid_operation(strike_states, events)
    print(f"Pheromone signals: {len(pheromone_signals)}")
    print(f"Bursts: {len(bursts)}")
    print(f"Gini coefficient: {gini}")